
DROP TABLE IF EXISTS `bot_fortunes_education`;
CREATE TABLE `bot_fortunes_education` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `quote` text NOT NULL,
  `props` int(10) NOT NULL default 0,
  PRIMARY KEY  (`id`)
); 

INSERT INTO `bot_fortunes_education` VALUES
(NULL, "A book is the work of a mind, doing its work in the way that a mind deemsbest.  That's dangerous.  Is the work of some mere individual mind likely toserve the aims of collectively accepted compromises, which are known in theschools as 'standards'?  Any mind that would audaciously put itself forth towork all alone is surely a bad example for the students, and probably, ifnot downright antisocial, at least a little off-center, self-indulgent,elitist.  ... It's just good pedagogy, therefore, to stay away from suchstuff, and use instead, if film-strips and rap-sessions must besupplemented, 'texts,' selected, or prepared, or adapted, by realprofessionals.  Those texts are called 'reading material.'  They are theacademic equivalent of the 'listening material' that fills waiting-rooms,and the 'eating material' that you can buy in thousands of convenient eatingresource centers along the roads.		-- The Underground Grammarian", NULL),
(NULL, "A definition of teaching: casting fake pearls before real swine.		-- Bill Cain, \"Stand Up Tragedy\"", NULL),
(NULL, "A fool's brain digests philosophy into folly, science into superstition, andart into pedantry.  Hence University education.		-- G. B. Shaw", NULL),
(NULL, "A good question is never answered.  It is not a bolt to be tightenedinto place but a seed to be planted and to bear more seed toward thehope of greening the landscape of idea.		-- John Ciardi", NULL),
(NULL, "A grammarian's life is always in tense.", NULL),
(NULL, "A great many people think they are thinking when they are merelyrearranging their prejudices.		-- William James", NULL),
(NULL, "A mother mouse was taking her large brood for a stroll across the kitchenfloor one day when the local cat, by a feat of stealth unusual even forits species, managed to trap them in a corner.  The children cowered,terrified by this fearsome beast, plaintively crying, \"Help, Mother!Save us!  Save us!  We're scared, Mother!\"	Mother Mouse, with the hopeless valor of a parent protecting itschildren, turned with her teeth bared to the cat, towering huge above them,and suddenly began to bark in a fashion that would have done any Dobermanproud.  The startled cat fled in fear for its life.	As her grateful offspring flocked around her shouting \"Oh, Mother,you saved us!\" and \"Yay!  You scared the cat away!\" she turned to thempurposefully and declared, \"You see how useful it is to know a secondlanguage?\"", NULL),
(NULL, "A Parable of Modern Research:	Bob has lost his keys in a room which is dark except for onebrightly lit corner.	\"Why are you looking under the light, you lost them in the dark!\"	\"I can only see here.\"", NULL),
(NULL, "A pencil with no point needs no eraser.", NULL),
(NULL, "	 A Plan for the Improvement of English Spelling			  by Mark Twain	For example, in Year 1 that useless letter \"c\" would be droppedto be replased either by \"k\" or \"s\", and likewise \"x\" would no longerbe part of the alphabet.  The only kase in which \"c\" would be retainedwould be the \"ch\" formation, which will be dealt with later.  Year 2might reform \"w\" spelling, so that \"which\" and \"one\" would take thesame konsonant, wile Year 3 might well abolish \"y\" replasing it with\"i\" and Iear 4 might fiks the \"g/j\" anomali wonse and for all.	Jenerally, then, the improvement would kontinue iear bai iearwith Iear 5 doing awai with useless double konsonants, and Iears 6-12or so modifaiing vowlz and the rimeining voist and unvoist konsonants.Bai Iear 15 or sou, it wud fainali bi posibl tu meik ius ov thiridandant letez \"c\", \"y\" and \"x\" -- bai now jast a memori in the maindzov ould doderez -- tu riplais \"ch\", \"sh\", and \"th\" rispektivli.	Fainali, xen, aafte sam 20 iers ov orxogrefkl riform, wi wudhev a lojikl, kohirnt speling in ius xrewawt xe Ingliy-spiking werld.", NULL),
(NULL, "A professor is one who talks in someone else's sleep.", NULL),
(NULL, "	A reader reports that when the patient died, the attending doctorrecorded the following on the patient's chart:  \"Patient failed to fulfillhis wellness potential.\"	Another doctor reports that in a recent issue of the *American Journalof Family Practice* fleas were called \"hematophagous arthropod vectors.\"	A reader reports that the Army calls them \"vertically deployed anti-personnel devices.\"  You probably call them bombs.	At McClellan Air Force base in Sacramento, California, civilianmechanics were placed on \"non-duty, non-pay status.\"  That is, they were fired.	After taking the trip of a lifetime, our reader sent his twelve rollsof film to Kodak for developing (or \"processing,\" as Kodak likes to call it)only to receive the following notice:  \"We must report that during the handlingof your twelve 35mm Kodachrome slide orders, the films were involved in anunusual laboratory experience.\"  The use of the passive is a particularly nicetouch, don't you think?  Nobody did anything to the films; they just had a badexperience.  Of course our reader can always go back to Tibet and take his pictures all over again, using the twelve replacement rolls Kodak so generouslysent him.		-- Quarterly Review of Doublespeak (NCTE)", NULL),
(NULL, "A student who changes the course of history is probably taking an exam.", NULL),
(NULL, "A synonym is a word you use when you can't spell the word you firstthought of.		-- Burt Bacharach", NULL),
(NULL, "A tautology is a thing which is tautological.", NULL),
(NULL, "A university is what a college becomes when the faculty loses interestin students.		-- John Ciardi", NULL),
(NULL, "\"A University without students is like an ointment without a fly.\"	-- Ed Nather, professor of astronomy at UT Austin", NULL),
(NULL, "About all some men accomplish in life is to send a son to Harvard.", NULL),
(NULL, "Abstract:	This study examined the incidence of neckwear tightness among a groupof 94 white-collar working men and the effect of a tight business-shirt collarand tie on the visual performance of 22 male subjects.  Of the white-collarmen measured, 67% were found to be wearing neckwear that was tighter thantheir neck circumference.  The visual discrimination of the 22 subjects wasevaluated using a critical flicker frequency (CFF) test.  Results of the CFFtest indicated that tight neckwear significantly decreased the visualperformance of the subjects and that visual performance did not improveimmediately when tight neckwear was removed.		-- Langan, L.M. and Watkins, S.M. \"Pressure of Menswear on the		   Neck in Relation to Visual Performance.\"  Human Factors 29,		   #1 (Feb. 1987), pp. 67-71.", NULL),
(NULL, "Academic politics is the most vicious and bitter form of politics,because the stakes are so low.		-- Wallace Sayre", NULL),
(NULL, "Academicians care, that's who.", NULL),
(NULL, "=============== ALL FRESHMEN PLEASE NOTE ===============To minimize scheduling confusion, please realize that if you are taking onecourse which is offered at only one time on a given day, and another which isoffered at all times on that day, the second class will be arranged as to afford maximum inconvenience to the student.  For example, if you happento work on campus, you will have 1-2 hours between classes.  If you commute,there will be a minimum of 6 hours between the two classes.", NULL),
(NULL, "An investment in knowledge always pays the best interest.		-- Benjamin Franklin", NULL),
(NULL, "Any two philosophers can tell each other all they know in two hours.		-- Oliver Wendell Holmes, Jr.", NULL),
(NULL, "As Gen. de Gaulle occassionally acknowledges America to be the daughterof Europe, so I am pleased to come to Yale, the daughter of Harvard.		-- J.F. Kennedy", NULL),
(NULL, "As long as the answer is right, who cares if the question is wrong?", NULL),
(NULL, "Briefly stated, the findings are that when presented with an array ofdata or a sequence of events in which they are instructed to discoveran underlying order, subjects show strong tendencies to perceive orderand causality in random arrays, to perceive a pattern or correlationwhich seems a priori intuitively correct even when the actual correlationin the data is counterintuitive, to jump to conclusions about the correcthypothesis, to seek and to use only positive or confirmatory evidence, toconstrue evidence liberally as confirmatory, to fail to generate or toassess alternative hypotheses, and having thus managed to expose themselvesonly to confirmatory instances, to be fallaciously confident of the validityof their judgments (Jahoda, 1969; Einhorn and Hogarth, 1978).  In theanalyzing of past events, these tendencies are exacerbated by failure toappreciate the pitfalls of post hoc analyses.		-- A. Benjamin", NULL),
(NULL, "British education is probably the best in the world, if you can surviveit.  If you can't there is nothing left for you but the diplomatic corps.		-- Peter Ustinov", NULL),
(NULL, "... But if we laugh with derision, we will never understand.  Humanintellectual capacity has not altered for thousands of years so far aswe can tell.  If intelligent people invested intense energy in issuesthat now seem foolish to us, then the failure lies in our understandingof their world, not in their distorted perceptions.  Even the standardexample of ancient nonsense -- the debate about angels on pinheads --makes sense once you realize that theologians were not discussingwhether five or eighteen would fit, but whether a pin could house afinite or an infinite number.		-- S. J. Gould, \"Wide Hats and Narrow Minds\"", NULL),
(NULL, "Campus sidewalks never exist as the straightest line between two points.		-- M. M. Johnston", NULL),
(NULL, "Comparing information and knowledge is like asking whether the fatnessof a pig is more or less green than the designated hitter rule.\"		-- David Guaspari", NULL),
(NULL, "Dear Freshman,	You don't know who I am and frankly shouldn't care, butunknown to you we have something in common.  We are both ratherprone to mistakes.  I was elected Student Government President bymistake, and you came to school here by mistake.", NULL),
(NULL, "Dear Miss Manners:	My home economics teacher says that one must never place one'selbows on the table.  However, I have read that one elbow, in betweencourses, is all right.  Which is correct?Gentle Reader:	For the purpose of answering examinations in your home economicsclass, your teacher is correct.  Catching on to this principle ofeducation may be of even greater importance to you now than learningcorrect current table manners, vital as Miss Manners believes that is.", NULL),
(NULL, "Department chairmen never die, they just lose their faculties.", NULL),
(NULL, "Did you know the University of Iowa closed down after someone stole the book?", NULL),
(NULL, "Do not clog intellect's sluices with bits of knowledge of questionable uses.", NULL),
(NULL, "Do you know the difference between education and experience?  Educationis what you get when you read the fine print; experience is what you getwhen you don't.		-- Pete Seeger", NULL),
(NULL, "Do you think that illiterate people get the full effect of alphabet soup?", NULL),
(NULL, "Education and religion are two things not regulated by supply anddemand.  The less of either the people have, the less they want.		-- Charlotte Observer, 1897", NULL),
(NULL, "Education is an admirable thing, but it is well to remember from time totime that nothing that is worth knowing can be taught.		-- Oscar Wilde, \"The Critic as Artist\"", NULL),
(NULL, "Education is learning what you didn't even know you didn't know.		-- Daniel J. Boorstin", NULL),
(NULL, "Education is the process of casting false pearls before real swine.		-- Irwin Edman", NULL),
(NULL, "Education is what survives when what has been learnt has been forgotten.		-- B.F. Skinner", NULL),
(NULL, "Educational television should be absolutely forbidden.  It can only leadto unreasonable disappointment when your child discovers that the lettersof the alphabet do not leap up out of books and dance around withroyal-blue chickens.		-- Fran Lebowitz, \"Social Studies\"", NULL),
(NULL, "Eloquence is logic on fire.", NULL),
(NULL, "Encyclopedia for sale by father.  Son knows everything.", NULL),
(NULL, "Engineering:    \"How will this work?\"Science:        \"Why will this work?\"Management:     \"When will this work?\"Liberal Arts:   \"Do you want fries with that?\"", NULL),
(NULL, "Even if you do learn to speak correct English, whom are you going to speakit to?		-- Clarence Darrow", NULL),
(NULL, "Everywhere I go I'm asked if I think the university stifles writers.  Myopinion is that they don't stifle enough of them.  There's many a bestsellerthat could have been prevented by a good teacher.		-- Flannery O'Connor", NULL),
(NULL, "Examinations are formidable even to the best prepared, foreven the greatest fool may ask more the the wisest man can answer.		-- C.C. Colton", NULL),
(NULL, "Experience is the worst teacher.  It always gives the test first andthe instruction afterward.", NULL),
(NULL, "F u cn rd ths u cnt spl wrth a dm!", NULL),
(NULL, "f u cn rd ths, itn tyg h myxbl cd.", NULL),
(NULL, "f u cn rd ths, u cn gt a gd jb n cmptr prgrmmng.", NULL),
(NULL, "f u cn rd ths, u r prbbly a lsy spllr.", NULL),
(NULL, "Fortune's Guide to Freshman Notetaking:WHEN THE PROFESSOR SAYS:			YOU WRITE:Probably the greatest quality of the poetry	John Milton -- born 1608of John Milton, who was born in 1608, is thecombination of beauty and power.  Few haveexcelled him in the use of the English language,or for that matter, in lucidity of verse form,'Paradise Lost' being said to be the greatestsingle poem ever written.\"Current historians have come to			Most of the problems that nowdoubt the complete advantageousness		face the United States areof some of Roosevelt's policies...		directly traceable to the						bungling and greed of President						Roosevelt.... it is possible that we simply do		Professor Mitchell is anot understand the Russian viewpoint...		communist.", NULL),
(NULL, "Fourteen years in the professor dodge has taught me that one can argueingeniously on behalf of any theory, applied to any piece of literature.This is rarely harmful, because normally no-one reads such essays.		-- Robert Parker, quoted in \"Murder Ink\",  ed. D. Wynn", NULL),
(NULL, "Going to church does not make a person religious, nor does going to schoolmake a person educated, any more than going to a garage makes a person a car.", NULL),
(NULL, "Good day to avoid cops.  Crawl to school.", NULL),
(NULL, "Good teaching is one-fourth preparation and three-fourths good theatre.		-- Gail Godwin", NULL),
(NULL, "Graduate life: It's not just a job.  It's an indenture.", NULL),
(NULL, "Graduate students and most professors are no smarter than undergrads.They're just older.", NULL),
(NULL, "He that teaches himself has a fool for a master.		-- Benjamin Franklin", NULL),
(NULL, "\"He was a modest, good-humored boy.  It was Oxford that made him insufferable.\"", NULL),
(NULL, "He who writes with no misspelled words has prevented a first suspicionon the limits of his scholarship or, in the social world, of his generaleducation and culture.		-- Julia Norton McCorkle", NULL),
(NULL, "[He] took me into his library and showed me his books, of which he hada complete set.		-- Ring Lardner", NULL),
(NULL, "Higher education helps your earning capacity.  Ask any college professor.", NULL),
(NULL, "History books which contain no lies are extremely dull.", NULL),
(NULL, "History is nothing but a collection of fables and useless trifles,cluttered up with a mass of unnecessary figures and proper names.		-- Leo Tolstoy", NULL),
(NULL, "How do you explain school to a higher intelligence?		-- Elliot, \"E.T.\"", NULL),
(NULL, "I am a bookaholic.  If you are a decent person, you will not sell meanother book.", NULL),
(NULL, "\"I am not sure what this is, but an `F' would only dignify it.\"		-- English Professor", NULL),
(NULL, "I am returning this otherwise good typing paper to you because someonehas printed gibberish all over it and put your name at the top.		-- Professor Lowd, English, Ohio University", NULL),
(NULL, "I appreciate the fact that this draft was done in haste, but some of thesentences that you are sending out in the world to do your work for you areloitering in taverns or asleep beside the highway.		-- Dr. Dwight Van de Vate, Professor of Philosophy,		   University of Tennessee at Knoxville", NULL),
(NULL, "I came out of twelve years of college and I didn't even know how to sew.All I could do was account -- I couldn't even account for myself.		-- Firesign Theatre", NULL),
(NULL, "I came to MIT to get an education for myself and a diploma for my mother.", NULL),
(NULL, "I have made this letter longer than usual because I lack the time tomake it shorter.		-- Blaise Pascal", NULL),
(NULL, "\"I have to convince you, or at least snow you ...\"		-- Prof. Romas Aleliunas, CS 435", NULL),
(NULL, "I heard a definition of an intellectual, that I thought was very interesting:a man who takes more words than are necessary to tell more than he knows.		-- Dwight D. Eisenhower", NULL),
(NULL, "I respect faith, but doubt is what gives you an education.		-- Wilson Mizner", NULL),
(NULL, "I think your opinions are reasonable, except for the one about my mentalinstability.		-- Psychology Professor, Farifield University", NULL),
(NULL, "\"I'm returning this note to you, instead of your paper, because it (your paper)presently occupies the bottom of my bird cage.\"		-- English Professor, Providence College", NULL),
(NULL, "If any man wishes to be humbled and mortified, let him become presidentof Harvard.		-- Edward Holyoke", NULL),
(NULL, "If he had only learnt a little less, how infinitely better he might havetaught much more!", NULL),
(NULL, "If ignorance is bliss, why aren't there more happy people?", NULL),
(NULL, "If little else, the brain is an educational toy.		-- Tom Robbins", NULL),
(NULL, "If someone had told me I would be Pope one day, I would have studied harder.		-- Pope John Paul I", NULL),
(NULL, "If the colleges were better, if they really had it, you would need to getthe police at the gates to keep order in the inrushing multitude.  See incollege how we thwart the natural love of learning by leaving the naturalmethod of teaching what each wishes to learn, and insisting that you shalllearn what you have no taste or capacity for.  The college, which shouldbe a place of delightful labor, is made odious and unhealthy, and theyoung men are tempted to frivolous amusements to rally their jaded spirits.I would have the studies elective.  Scholarship is to be created notby compulsion, but by awakening a pure interest in knowledge.  The wiseinstructor accomplishes this by opening to his pupils precisely theattractions the study has for himself.  The marking is a system for schools,not for the college; for boys, not for men; and it is an ungracious work toput on a professor.		-- Ralph Waldo Emerson", NULL),
(NULL, "If truth is beauty, how come no one has their hair done in the library?		-- Lily Tomlin", NULL),
(NULL, "If we spoke a different language, we would perceive a somewhat different world.		-- Wittgenstein", NULL),
(NULL, "If while you are in school, there is a shortage of qualified personnelin a particular field, then by the time you graduate with the necessaryqualifications, that field's employment market is glutted.		-- Marguerite Emmons", NULL),
(NULL, "If you are too busy to read, then you are too busy.", NULL),
(NULL, "If you can't read this, blame a teacher.", NULL),
(NULL, "If you resist reading what you disagree with, how will you ever acquiredeeper insights into what you believe?  The things most worth readingare precisely those that challenge our convictions.", NULL),
(NULL, "If you think education is expensive, try ignorance.		-- Derek Bok, president of Harvard", NULL),
(NULL, "If you took all the students that felt asleep in class and laid them end toend, they'd be a lot more comfortable.		-- \"Graffiti in the Big Ten\"", NULL),
(NULL, "\"If you understand what you're doing, you're not learning anything.\"		-- A. L.", NULL),
(NULL, "Ignorance is never out of style.  It was in fashion yesterday, it is therage today, and it will set the pace tomorrow.		-- Franklin K. Dane", NULL),
(NULL, "Ignorance is when you don't know anything and somebody finds it out.", NULL),
(NULL, "Ignorance must certainly be bliss or there wouldn't be so many peopleso resolutely pursuing it. ", NULL),
(NULL, "Illiterate?  Write today, for free help!", NULL),
(NULL, "	In a forest a fox bumps into a little rabbit, and says, \"Hi,Junior, what are you up to?\"	\"I'm writing a dissertation on how rabbits eat foxes,\" said therabbit.	\"Come now, friend rabbit, you know that's impossible!  No onewill publish such rubbish!\"	\"Well, follow me and I'll show you.\"	They both go into the rabbit's dwelling and after a while therabbit emerges with a satisfied expression on his face.  Comes along awolf.  \"Hello, little buddy, what are we doing these days?\"	\"I'm writing the 2'nd chapter of my thesis, on how rabbits devourwolves.\"	\"Are you crazy?  Where's your academic honesty?\"	\"Come with me and I'll show you.\"	As before, the rabbit comes out with a satisfied look on his faceand a diploma in his paw.  Finally, the camera pans into the rabbit's caveand, as everybody should have guessed by now, we see a mean-looking, hugelion, sitting, picking his teeth and belching, next to some furry, bloodyremnants of the wolf and the fox.	The moral: It's not the contents of your thesis that areimportant -- it's your PhD advisor that really counts.", NULL),
(NULL, "In California, Bill Honig, the Superintendent of Public Instruction, said hethought the general public should have a voice in defining what an excellentteacher should know.  \"I would not leave the definition of math,\" Dr. Honigsaid, \"up to the mathematicians.\"		-- The New York Times, October 22, 1985", NULL),
(NULL, "Instead of giving money to found colleges to promote learning, why don'tthey pass a constitutional amendment prohibiting anybody from learninganything?  If it works as good as the Prohibition one did, why, in fiveyears we would have the smartest race of people on earth.		-- The Best of Will Rogers", NULL),
(NULL, "Iowa State -- the high school after high school!		-- Crow T. Robot", NULL),
(NULL, "It has been said [by Anatole France], \"it is not by amusing oneselfthat one learns,\" and, in reply: \"it is *____only* by amusing oneself thatone can learn.\"		-- Edward Kasner and James R. Newman", NULL),
(NULL, "It has long been an article of our folklore that too much knowledge or skill,or especially consummate expertise, is a bad thing.  It dehumanizes those whoachieve it, and makes difficult their commerce with just plain folks, in whomgood old common sense has not been obliterated by mere book learning or fancynotions.  This popular delusion flourishes now more than ever, for we are allinfected with it in the schools, where educationists have elevated it fromfolklore to Article of Belief.  It enhances their self-esteem and lightenstheir labors by providing theoretical justification for deciding thatappreciation, or even simple awareness, is more to be prized than knowledge,and relating (to self and others), more than skill, in which minimumcompetence will be quite enough.		-- The Underground Grammarian", NULL),
(NULL, "	It is a profoundly erroneous truism, repeated by all copy-books andby eminent people when they are making speeches, that we should cultivatethe habit of thinking about what we are doing.  The precise opposite is thecase.  Civilization advances by extending the numbers of important operationswhich we can perform without thinking about them.  Operations of thought arelike cavalry charges in battle -- they are strictly limited in number, theyrequire fresh horses, and must only be made at decisive moments.		-- Alfred North Whitehead", NULL),
(NULL, "			It's grad exam time...COMPUTER SCIENCE	Inside your desk you'll find a listing of the DEC/VMS operatingsystem in IBM 1710 machine code. Show what changes are necessary to convertthis code into a UNIX Berkeley 7 operating system.  Prove that these fixes arebug free and run correctly. You should gain at least 150% efficiency in thenew system.  (You should take no more than 10 minutes on this question.)MATHEMATICS	If X equals PI times R^2, construct a formula showing how longit would take a fire ant to drill a hole through a dill pickle, if thelength-girth ratio of the ant to the pickle were 98.17:1.GENERAL KNOWLEDGEDescribe the Universe.  Give three examples.", NULL),
(NULL, "			It's grad exam time...MEDICINE	You have been provided with a razor blade, a piece of gauze, and abottle of Scotch.  Remove your appendix.  Do not suture until your work hasbeen inspected.  (You have 15 minutes.)HISTORY	Describe the history of the papacy from its origins to the presentday, concentrating especially, but not exclusively, on its social, political,economic, religious and philisophical impact upon Europe, Asia, America, andAfrica.  Be brief, concise, and specific.BIOLOGY	Create life.  Estimate the differences in subsequent human cultureif this form of life had been created 500 million years ago or earlier, withspecial attention to its probable effect on the English parliamentary system.", NULL),
(NULL, "It's is not, it isn't ain't, and it's it's, not its, if you mean itis.  If you don't, it's its.  Then too, it's hers.  It isn't her's.  Itisn't our's either.  It's ours, and likewise yours and theirs.		-- Oxford University Press, Edpress News", NULL),
(NULL, "Joe Cool always spends the first two weeks at college sailing his frisbee.		-- Snoopy", NULL),
(NULL, "Learned men are the cisterns of knowledge, not the fountainheads.", NULL),
(NULL, "Learning at some schools is like drinking from a firehose.", NULL),
(NULL, "Learning without thought is labor lost;thought without learning is perilous.		-- Confucius", NULL),
(NULL, "Maybe ain't ain't so correct, but I notice that lots of folks who ain'tusing ain't ain't eatin' well.		-- Will Rogers", NULL),
(NULL, "Most seminars have a happy ending.  Everyone's glad when they're over.", NULL),
(NULL, "My father, a good man, told me, \"Never lose your ignorance; you cannotreplace it.\"		-- Erich Maria Remarque", NULL),
(NULL, "Never have so many understood so little about so much.		-- James Burke", NULL),
(NULL, "Never let your schooling interfere with your education.", NULL),
(NULL, "No discipline is ever requisite to force attendance upon lectures which arereally worth the attending.		-- Adam Smith, \"The Wealth of Nations\"", NULL),
(NULL, "No matter who you are, some scholar can show you the great idea you hadwas had by someone before you.", NULL),
(NULL, "No wonder you're tired!  You understood so much today.", NULL),
(NULL, "Normally our rules are rigid; we tend to discretion, if for no other reasonthan self-protection.  We never recommend any of our graduates, although wecheerfully provide information as to those who have failed their courses.		-- Jack Vance, \"Freitzke's Turn\"", NULL),
(NULL, "Not only is this incomprehensible, but the ink is ugly and the paperis from the wrong kind of tree.		-- Professor, EECS, George Washington UniversityI'm looking forward to working with you on this next year.		-- Professor, Harvard, on a  senior thesis.", NULL),
(NULL, "		`O' LEVEL COUNTER CULTURETimewarp allowed: 3 hours.  Do not scrawl situationalist graffiti in themargins or stub your rollups in the inkwells.  Orange may be worn.  Creditwill be given to candidates who self-actualise.	(1) Compare and contrast Pink Floyd with Black Sabbath and say why	    neither has street credibility.	(2) \"Even Buddha would have been hard pushed to reach Nirvana squatting	    on a juggernaut route.\"  Consider the dialectic of inner truth	    and inner city.	(3) Discuss degree of hassle involved in paranoia about being sucked	    into a black hole.	(4) \"The Egomaniac's Liberation Front were a bunch of revisionist	    ripoff merchants.\"  Comment on this insult.	(5) Account for the lack of references to brown rice in Dylan's lyrics.	(6) \"Castenada was a bit of a bozo.\"  How far is this a fair summing	    up of western dualism?	(7) Hermann Hesse was a Pisces.  Discuss.", NULL),
(NULL, "\"OK, now let's look at four dimensions on the blackboard.\"		-- Dr. Joy", NULL),
(NULL, "OK, so you're a Ph.D.  Just don't touch anything.", NULL),
(NULL, "One cannot make an omelette without breaking eggs -- but it is amazinghow many eggs one can break without making a decent omelette.		-- Professor Charles P. Issawi", NULL),
(NULL, "Periphrasis is the putting of things in a round-about way.  \"The cost may beupwards of a figure rather below 10m#.\" is a periphrasis for The cost may benearly 10m#.  \"In Paris there reigns a complete absence of really reliablenews\" is a periphrasis for There is no reliable news in Paris.  \"Rarely doesthe 'Little Summer' linger until November, but at times its stay has beenprolonged until quite late in the year's penultimate month\" contains aperiphrasis for November, and another for lingers.  \"The answer is in thenegative\" is a periphrasis for No.  \"Was made the recipient of\" is aperiphrasis for Was presented with.  The periphrasis style is hardly possibleon any considerable scale without much use of abstract nouns such as \"basis,case, character, connexion, dearth, description, duration, framework, lack,nature, reference, regard, respect\".  The existence of abstract nouns is aproof that abstract thought has occurred; abstract thought is a mark ofcivilized man; and so it has come about that periphrasis and civilization areby many held to be inseparable.  These good people feel that there is an almostindecent nakedness, a reversion to barbarism, in saying No news is good newsinstead of \"The absence of intelligence is an indication of satisfactorydevelopments.\"		-- Fowler's English Usage", NULL),
(NULL, "\"Plaese porrf raed.\"		-- Prof. Michael O'Longhlin, S.U.N.Y. Purchase", NULL),
(NULL, "Practice is the best of all instructors.		-- Publilius", NULL),
(NULL, "Princeton's taste is sweet like a strawberry tart.  Harvard's is a subtletaste, like whiskey, coffee, or tobacco.  It may even be a bad habit, forall I know.		-- Prof. J.H. Finley '25", NULL),
(NULL, "Professor Gorden Newell threw another shutout in last week's Chem Eng. 130midterm.  Once again a student did not receive a single point on his exam.Newell has now tossed 5 shutouts this quarter.  Newell's earned exam averagehas now dropped to a phenomenal 30%.", NULL),
(NULL, "Reading is thinking with someone else's head instead of one's own.", NULL),
(NULL, "Reading is to the mind what exercise is to the body.", NULL),
(NULL, "Reporter:   \"How did you like school when you were growing up, Yogi?\"Yogi Berra: \"Closed.\"", NULL),
(NULL, "Rules for Good Grammar #4.	 (1) Don't use no double negatives.	 (2) Make each pronoun agree with their antecedents.	 (3) Join clauses good, like a conjunction should.	 (4) About them sentence fragments.	 (5) When dangling, watch your participles.	 (6) Verbs has got to agree with their subjects.	 (7) Just between you and i, case is important.	 (8) Don't write run-on sentences when they are hard to read.	 (9) Don't use commas, which aren't necessary.	(10) Try to not ever split infinitives.	(11) It is important to use your apostrophe's correctly.	(12) Proofread your writing to see if you any words out.	(13) Correct speling is essential.	(14) A preposition is something you never end a sentence with.	(15) While a transcendant vocabulary is laudable, one must be eternally	     careful so that the calculated objective of communication does not	     become ensconsed in obscurity.  In other words, eschew obfuscation.", NULL),
(NULL, "Smartness runs in my family.  When I went to school I was so smart myteacher was in my class for five years.		-- George Burns", NULL),
(NULL, "Some scholars are like donkeys, they merely carry a lot of books.		-- Folk saying", NULL),
(NULL, "\"Speed is subsittute fo accurancy.\"", NULL),
(NULL, "Spelling is a lossed art.", NULL),
(NULL, "Suddenly, Professor Liebowitz realizes he has come to the seminarwithout his duck ...", NULL),
(NULL, "Teachers have class.", NULL),
(NULL, "The 'A' is for content, the 'minus' is for not typing it.  Don't ever dothis to my eyes again.		-- Professor Ronald Brady, Philosophy, Ramapo State College", NULL),
(NULL, "The alarm clock that is louder than God's own belongs to the roommate withthe earliest class.", NULL),
(NULL, "The average Ph.D thesis is nothing but the transference of bones fromone graveyard to another.		-- J. Frank Dobie, \"A Texan in England\"", NULL),
(NULL, "The avocation of assessing the failures of better men can be turnedinto a comfortable livelihood, providing you back it up with a Ph.D.		-- Nelson Algren, \"Writers at Work\"", NULL),
(NULL, "	\"The best thing for being sad,\" replied Merlin, beginning to puffand blow, \"is to learn something.  That's the only thing that never fails.You may grow old and trembling in your anatomies, you may lie awake atnight listening to the disorder of your veins, you may miss your only love,you may see the world about you devastated by evil lunatics, or know yourhonour trampled in the sewers of baser minds. There is only one thing forit then -- to learn.  Learn why the world wags and what wags it.  That isthe only thing which the mind can never exhaust, never alienate, never betortured by, never fear or distrust, and never dream of regretting.  Learningis the only thing for you.  Look what a lot of things there are to learn.\"		-- T.H. White, \"The Once and Future King\"", NULL),
(NULL, "The brain is a wonderful organ; it starts working the moment you get upin the morning, and does not stop until you get to school.", NULL),
(NULL, "The college graduate is presented with a sheepskin to cover hisintellectual nakedness.		-- Robert M. Hutchins", NULL),
(NULL, "The end of the world will occur at three p.m., this Friday, withsymposium to follow.", NULL),
(NULL, "The future is a race between education and catastrophe.		-- H.G. Wells", NULL),
(NULL, "The important thing is not to stop questioning.", NULL),
(NULL, "The man who has never been flogged has never been taught.		-- Menander", NULL),
(NULL, "The only thing that experience teaches us is that experience teaches us nothing.		-- Andre Maurois (Emile Herzog)", NULL),
(NULL, "The only thing we learn from history is that we do not learn.		-- Earl WarrenThat men do not learn very much from history is the most important of allthe lessons that history has to teach.		-- Aldous HuxleyWe learn from history that we do not learn from history.		-- Georg HegelHISTORY:  Papa Hegel he say that all we learn from history is that we learnnothing from history.  I know people who can't even learn from what happenedthis morning.  Hegel must have been taking the long view.		-- Chad C. Mulligan, \"The Hipcrime Vocab\"", NULL),
(NULL, "The only thing we learn from history is that we learn nothing from history.		-- HegelI know guys can't learn from yesterday ... Hegel must be taking the long view.		-- John Brunner, \"Stand on Zanzibar\"", NULL),
(NULL, "The problem with graduate students, in general, is that they haveto sleep every few days.", NULL),
(NULL, "The ratio of literacy to illiteracy is a constant, but nowadays theilliterates can read.		-- Alberto Moravia", NULL),
(NULL, "The real purpose of books is to trap the mind into doing its own thinking.		-- Christopher Morley", NULL),
(NULL, "\"The student in question is performing minimally for his peer group andis an emerging underachiever.\"", NULL),
(NULL, "The sum of the intelligence of the world is constant.  The population is,of course, growing.", NULL),
(NULL, "The sunlights differ, but there is only one darkness.		-- Ursula K. LeGuin, \"The Dispossessed\"", NULL),
(NULL, "The test of a first-rate intelligence is the ability to hold two opposedideas in the mind at the same time and still retain the ability to function.		-- F. Scott Fitzgerald", NULL),
(NULL, "The three best things about going to school are June, July, and August.", NULL),
(NULL, "The Tree of Learning bears the noblest fruit, but noble fruit tastes bad.", NULL),
(NULL, "The USA is so enormous, and so numerous are its schools, colleges and religiousseminaries, many devoted to special religious beliefs ranging from theunorthodox to the dotty, that we can hardly wonder at its yielding a morebounteous harvest of gobbledegook than the rest of the world put together.		-- Sir Peter Medawar", NULL),
(NULL, "The world is coming to an end!  Repent and return those library books!", NULL),
(NULL, "The world is full of people who have never, since childhood, met anopen doorway with an open mind.		-- E.B. White", NULL),
(NULL, "There are no answers, only cross-references.		-- Weiner", NULL),
(NULL, "This is the sort of English up with which I will not put.		-- Winston Churchill", NULL),
(NULL, "Those who educate children well are more to be honored than parents, forthese only gave life, those the art of living well.		-- Aristotle", NULL),
(NULL, "Time is a great teacher, but unfortunately it kills all its pupils.		-- Hector Berlioz", NULL),
(NULL, "To accuse others for one's own misfortunes is a sign of want of education.To accuse oneself shows that one's education has begun.  To accuse neitheroneself nor others shows that one's education is complete.		-- Epictetus", NULL),
(NULL, "To craunch a marmoset.		-- Pedro Carolino, \"English as She is Spoke\"", NULL),
(NULL, "To teach is to learn twice.		-- Joseph Joubert", NULL),
(NULL, "To teach is to learn.", NULL),
(NULL, "Try not to have a good time ... This is supposed to be educational.		-- Charles Schulz", NULL),
(NULL, "Trying to get an education here is like trying to get a drink from a fire hose.", NULL),
(NULL, "Universities are places of knowledge.  The freshman each bring a littlein with them, and the seniors take none away, so knowledge accumulates.", NULL),
(NULL, "University politics are vicious precisely because the stakes are so small.		-- C. P. Snow", NULL),
(NULL, "Walt:	Dad, what's gradual school?Garp:	Gradual school?Walt:	Yeah.  Mom says her work's more fun now that she's teaching	gradual school.Garp:	Oh.  Well, gradual school is someplace you go and gradually	find out that you don't want to go to school anymore.		-- The World According To Garp", NULL),
(NULL, "\"We demand rigidly defined areas of doubt and uncertainty!\"		-- Vroomfondel", NULL),
(NULL, "We know next to nothing about virtually everything.  It is not necessaryto know the origin of the universe; it is necessary to want to know.Civilization depends not on any particular knowledge, but on the dispositionto crave knowledge.		-- George Will", NULL),
(NULL, "We're fantastically incredibly sorry for all these extremely unreasonablethings we did.  I can only plead that my simple, barely-sentient friendand myself are underprivileged, deprived and also college students.		-- Waldo D.R. Dobbs", NULL),
(NULL, "	\"We're running out of adjectives to describe our situation.  Wehad crisis, then we went into chaos, and now what do we call this?\" saidNicaraguan economist Francisco Mayorga, who holds a doctorate from Yale.		-- The Washington Post, February, 1988The New Yorker's comment:	At Harvard they'd call it a noun.", NULL),
(NULL, "What does education often do?  It makes a straight cut ditch of afree meandering brook.		-- Henry David Thoreau", NULL),
(NULL, "		What I Did During My Fall SemesterOn the first day of my fall semester, I got up.Then I went to the library to find a thesis topic.Then I hung out in front of the Dover.On the second day of my fall semester, I got up.Then I went to the library to find a thesis topic.Then I hung out in front of the Dover.On the third day of my fall semester, I got up.Then I went to the library to find a thesis topic.I found a thesis topic:	How to keep people from hanging out in front of the Dover.		-- Sister Mary Elephant, \"Student Statement for Black Friday\"", NULL),
(NULL, "What makes you think graduate school is supposed to be satisfying?		-- Erica Jong, \"Fear of Flying\"", NULL),
(NULL, "What passes for optimism is most often the effect of an intellectual error.		-- Raymond Aron, \"The Opium of the Intellectuals\"", NULL),
(NULL, "What we do not understand we do not possess.		-- Goethe", NULL),
(NULL, "What's page one, a preemptive strike?		-- Professor Freund, Communication, Ramapo State College", NULL),
(NULL, "When I was in school, I cheated on my metaphysics exam: I looked intothe soul of the boy sitting next to me.		-- Woody Allen", NULL),
(NULL, "Whenever anyone says, \"theoretically,\" they really mean, \"not really.\"		-- Dave Parnas", NULL),
(NULL, "Where do I find the time for not reading so many books?		-- Karl Kraus", NULL),
(NULL, "\"Whom are you?\" said he, for he had been to night school.		-- George Ade", NULL),
(NULL, "	Wouldn't the sentence \"I want to put a hyphen between the words Fishand And and And and Chips in my Fish-And-Chips sign\" have been clearer ifquotation marks had been placed before Fish, and between Fish and and, andand and And, and And and and, and and and And, and And and and, and and andChips, as well as after Chips?", NULL),
(NULL, "You can't expect a boy to be vicious till he's been to a good school.		-- H.H. Munro", NULL),
(NULL, "You don't have to think too hard when you talk to teachers.		-- J. D. Salinger", NULL),
(NULL, "You may have heard that a dean is to faculty as a hydrant is to a dog.		-- Alfred Kahn", NULL),
(NULL, "\"You should, without hesitation, pound your typewriter into a plowshare,your paper into fertilizer, and enter agriculture\"		-- Business Professor, University of Georgia", NULL),
(NULL, "Your education begins where what is called your education is over.", NULL),
(NULL, "", NULL)
