
DROP TABLE IF EXISTS `bot_fortunes_linux`;
CREATE TABLE `bot_fortunes_linux` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `quote` text NOT NULL,
  `props` int(10) NOT NULL default 0,
  PRIMARY KEY  (`id`)
); 

INSERT INTO `bot_fortunes_linux` VALUES
(NULL, "\"How do you pronounce SunOS?\"  \"Just like you hear it, with a big SOS\"	-- dedicated to Roland Kaltefleiter", NULL),
(NULL, "finlandia:~> apropos winwin: nothing appropriate.", NULL),
(NULL, "C:\> WINBad command or filenameC:\> LOSELoading Microsoft Windows ...", NULL),
(NULL, "Linux ext2fs has been stable for a long time, now it's time to break it	-- Linuxkongreß '95 in Berlin", NULL),
(NULL, "The state of some commercial Un*x is more unsecure than any Linux boxwithout a root password...	-- Bernd Eckenfels", NULL),
(NULL, "Less is more or less more	-- Y_Plentyn on #LinuxGER", NULL),
(NULL, "Let's call it an accidental feature.	--Larry Wall", NULL),
(NULL, ".........    Escape the 'Gates' of Hell  `:::'                  .......  ......   :::  *                  `::.    ::'   ::: .::  .:.::.  .:: .::  `::. :'   :::  ::   ::  ::  ::  ::    :::.   ::: .::. .::  ::.  `::::. .:'  ::....:::.....................::'   .::::..	-- William E. Roadcap", NULL),
(NULL, "Win95 is not a virus; a virus does something.	-- unknown source", NULL),
(NULL, "Machine Always Crashes, If Not, The Operating System Hangs (MACINTOSH)	-- Topic on #Linux", NULL),
(NULL, "Except for Great Britain. According to ISO 9166 and Internet realityGreat Britain's toplevel domain should be _gb_.  Instead, Great Britainand Nortern Ireland (the United Kingdom) use the toplevel domain _uk_.They drive on the wrong side of the road, too.	-- PERL book (or DNS and BIND book)", NULL),
(NULL, "Save yourself from the 'Gates' of hell, use Linux.\"  -- like that one.	-- The_Kind @ LinuxNet", NULL),
(NULL, "I did this 'cause Linux gives me a woody.  It doesn't generate revenue.	-- Dave '-ddt->` Taylor, announcing DOOM for Linux", NULL),
(NULL, "Feel free to contact me (flames about my english and the useless of thisdriver will be redirected to /dev/null, oh no, it's full...).	-- Michael Beck, describing the PC-speaker sound device", NULL),
(NULL, "    if (argc > 1 && strcmp(argv[1], \"-advice\") == 0) {	printf(\"Don't Panic!\n\");	exit(42);    }	-- Arnold Robbins in the LJ of February '95, describing RCS", NULL),
(NULL, "lp1 on fire	-- One of the more obfuscated kernel messages", NULL),
(NULL, "A Linux machine!  Because a 486 is a terrible thing to waste!	-- Joe Sloan, jjs@wintermute.ucr.edu", NULL),
(NULL, "Microsoft is not the answer.Microsoft is the question.NO (or Linux) is the answer.	-- Taken from a .signature from someone from the UK, source unknown", NULL),
(NULL, "In most countries selling harmful things like drugs is punishable.Then howcome people can sell Microsoft software and go unpunished?	-- Hasse Skrifvars, hasku@rost.abo.fi, ", NULL),
(NULL, "Windows without the X is like making love without a partner.	-- MaDsen Wikholm, mwikholm@at8.abo.fi", NULL),
(NULL, "Sex, Drugs & Linux Rules	-- MaDsen Wikholm, mwikholm@at8.abo.fi", NULL),
(NULL, "win-nt from the people who invented edlin.	-- MaDsen Wikholm, mwikholm@at8.abo.fi", NULL),
(NULL, "Apples  have  meant  trouble  since  eden.	-- MaDsen Wikholm, mwikholm@at8.abo.fi", NULL),
(NULL, "Linux, the way to get rid of boot viruses	-- MaDsen Wikholm, mwikholm@at8.abo.fi", NULL),
(NULL, "Once upon a time there was a DOS user who saw Unix, and saw that it wasgood.  After typing cp on his DOS machine at home, he downloaded GNU'sunix tools ported to DOS and installed them.  He rm'd, cp'd, and mv'dhappily for many days, and upon finding elvis, he vi'd and was happy.  Aftera long day at work (on a Unix box) he came home, started editing a file,and couldn't figure out why he couldn't suspend vi (w/ ctrl-z) to doa compile.	-- Erik Troan, ewt@tipper.oit.unc.edu", NULL),
(NULL, "We are MicroSoft.  You will be assimilated.  Resistance is futile.	-- Attributed to B.G., Gill Bates", NULL),
(NULL, "Avoid the Gates of Hell.  Use Linux	-- unknown source", NULL),
(NULL, "Intel engineering seem to have misheard Intel marketing strategy.  Thephrase was \"Divide and conquer\" not \"Divide and cock up\"	-- Alan Cox, iialan@www.linux.org.uk", NULL),
(NULL, "Linux!  Guerrilla UNIX Development     Venimus, Vidimus, Dolavimus.	-- Mark A. Horton KA4YBR, mah@ka4ybr.com", NULL),
(NULL, "----==-- _                     / /  \---==---(_)__  __ ____  __    / / /\ \--==---/ / _ \/ // /\ \/ /   / /_/\ \ \-=====/_/_//_/\_,_/ /_/\_\  /______\ \ \A proud member of TeamLinux \_________\/	-- CHaley (HAC), haley@unm.edu, ch008cth@pi.lanl.gov)", NULL),
(NULL, "\"Who is General Failure and why is he reading my hard disk?\"Microsoft spel chekar vor sail, worgs grate !!	-- Felix von Leitner, leitner@inf.fu-berlin.de", NULL),
(NULL, "Personally, I think my choice in the mostest-superlative-computer wars has tobe the HP-48 series of calculators.  They'll run almost anything.  And if theycan't, while I'll just plug a Linux box into the serial port and load up theHP-48 VT-100 emulator.	-- Jeff Dege, jdege@winternet.com", NULL),
(NULL, "/* * Oops. The kernel tried to access some bad page. We'll have to * terminate things with extreme prejudice.*/die_if_kernel(\"Oops\", regs, error_code);	-- From linux/arch/i386/mm/fault.c", NULL),
(NULL, "Linux: because a PC is a terrible thing to waste	-- ksh@cis.ufl.edu put this on Tshirts in '93", NULL),
(NULL, "Linux: the choice of a GNU generation	-- ksh@cis.ufl.edu put this on Tshirts in '93", NULL),
(NULL, "There are two types of Linux developers - those who can spell, andthose who can't.  There is a constant pitched battle between the two.	-- From one of the post-1.1.54 kernel update messages posted to c.o.l.a", NULL),
(NULL, "> > Other than the fact Linux has a cool name, could someone explain why I> > should use Linux over BSD?>> No.  That's it.  The cool name, that is.  We worked very hard on> creating a name that would appeal to the majority of people, and it> certainly paid off: thousands of people are using linux just to be able> to say \"OS/2? Hah.  I've got Linux.  What a cool name\".  386BSD made the> mistake of putting a lot of numbers and weird abbreviations into the> name, and is scaring away a lot of people just because it sounds too> technical.	-- Linus Torvalds' follow-up to a question about Linux", NULL),
(NULL, "> The day people think linux would be better served by somebody else (FSF> being the natural alternative), I'll \"abdicate\".  I don't think that> it's something people have to worry about right now - I don't see it> happening in the near future.  I enjoy doing linux, even though it does> mean some work, and I haven't gotten any complaints (some almost timid> reminders about a patch I have forgotten or ignored, but nothing> negative so far).>> Don't take the above to mean that I'll stop the day somebody complains:> I'm thick-skinned (Lasu, who is reading this over my shoulder commented> that \"thick-HEADED is closer to the truth\") enough to take some abuse.> If I weren't, I'd have stopped developing linux the day ast ridiculed me> on c.o.minix.  What I mean is just that while linux has been my baby so> far, I don't want to stand in the way if people want to make something> better of it (*).>>                 Linus>> (*) Hey, maybe I could apply for a saint-hood from the Pope.  Does> somebody know what his email-address is? I'm so nice it makes you puke.	-- Taken from Linus's reply to someone worried about the future of Linux", NULL),
(NULL, "> : Any porters out there should feel happier knowing that DEC is shipping> : me an AlphaPC that I intend to try getting linux running on: this will> : definitely help flush out some of the most flagrant unportable stuff.> : The Alpha is much more different from the i386 than the 68k stuff is, so> : it's likely to get most of the stuff fixed.>> It's posts like this that almost convince us non-believers that there> really is a god.	-- Anthony Lovell, to Linus's remarks about porting", NULL),
(NULL, "When you say \"I wrote a program that crashed Windows\", people just stare atyou blankly and say \"Hey, I got those with the system, *for free*\".	-- Linus Torvalds", NULL),
(NULL, "We come to bury DOS, not to praise it.	-- Paul Vojta, vojta@math.berkeley.edu", NULL),
(NULL, "Be warned that typing \fBkillall \fIname\fP may not have the desiredeffect on non-Linux systems, especially when done by a privileged user.	-- From the killall manual page", NULL),
(NULL, "Note that if I can get you to \"su and say\" something just by asking,you have a very serious security problem on your system and you shouldlook into it.	-- Paul Vixie, vixie-cron 3.0.1 installation notes", NULL),
(NULL, "How should I know if it works?  That's what beta testers are for.  Ionly coded it.	-- Attributed to Linus Torvalds, somewhere in a posting", NULL),
(NULL, "I develop for Linux for a living, I used to develop for DOS.Going from DOS to Linux is like trading a glider for an F117.	-- Lawrence Foard, entropy@world.std.com", NULL),
(NULL, "Absolutely nothing should be concluded from these figures except thatno conclusion can be drawn from them.	-- Joseph L. Brothers, Linux/PowerPC Project)", NULL),
(NULL, "If the future navigation system [for interactive networked services onthe NII] looks like something from Microsoft, it will never work.	-- Chairman of Walt Disney Television & Telecommunications", NULL),
(NULL, "Problem solving under Linux has never been the circus that it is underAIX.	-- Pete Ehlke in comp.unix.aix", NULL),
(NULL, "I don't know why, but first C programs tend to look a lot worse thanfirst programs in any other language (maybe except for fortran, but thenI suspect all fortran programs look like `firsts')	-- Olaf Kirch", NULL),
(NULL, "On a normal ascii line, the only safe condition to detect is a 'BREAK'- everything else having been assigned functions by Gnu EMACS.	-- Tarl Neustaedter", NULL),
(NULL, "By golly, I'm beginning to think Linux really *is* the best thing sincesliced bread.	-- Vance Petree, Virginia Power", NULL),
(NULL, "I'd crawl over an acre of 'Visual This++' and 'Integrated DevelopmentThat' to get to gcc, Emacs, and gdb.  Thank you.	-- Vance Petree, Virginia Power", NULL),
(NULL, "Oh, I've seen copies [of Linux Journal] around the terminal room at The Labs.	-- Dennis Ritchie", NULL),
(NULL, "If you want to travel around the world and be invited to speak at a lotof different places, just write a Unix operating system.	-- Linus Torvalds", NULL),
(NULL, "...and scantily clad females, of course.  Who cares if it's below zerooutside.	-- Linus Torvalds", NULL),
(NULL, "...you might as well skip the Xmas celebration completely, and insteadsit in front of your linux computer playing with the all-new-and-improved linux kernel version.	-- Linus Torvalds", NULL),
(NULL, "Besides, I think Slackware sounds better than 'Microsoft,' don't you?	-- Patrick Volkerding", NULL),
(NULL, "All language designers are arrogant. Goes with the territory...	-- Larry Wall", NULL),
(NULL, "And the next time you consider complaining that running Lucid Emacs19.05 via NFS from a remote Linux machine in Paraguay doesn't seem toget the background colors right, you'll know who to thank.	-- Matt Welsh", NULL),
(NULL, "Are Linux users lemmings collectively jumping off of the cliff ofreliable, well-engineered commercial software?	-- Matt Welsh", NULL),
(NULL, "Even more amazing was the realization that God has Internet access.  Iwonder if He has a full newsfeed?	-- Matt Welsh", NULL),
(NULL, "I once witnessed a long-winded, month-long flamewar over the use ofmice vs. trackballs... It was very silly.	-- Matt Welsh", NULL),
(NULL, "Linux poses a real challenge for those with a taste for late-nighthacking (and/or conversations with God).	-- Matt Welsh", NULL),
(NULL, "What you end up with, after running an operating system concept throughthese many marketing coffee filters, is something not unlike plain hotwater.	-- Matt Welsh", NULL),
(NULL, "...Deep Hack Mode -- that mysterious and frightening state ofconsciousness where Mortal Users fear to tread.	-- Matt Welsh", NULL),
(NULL, "...Unix, MS-DOS, and Windows NT (also known as the Good, the Bad, andthe Ugly).	-- Matt Welsh", NULL),
(NULL, "...very few phenomena can pull someone out of Deep Hack Mode, with twonoted exceptions: being struck by lightning, or worse, your *computer*being struck by lightning.	-- Matt Welsh", NULL),
(NULL, "..you could spend *all day* customizing the title bar.  Believe me.  Ispeak from experience.	-- Matt Welsh", NULL),
(NULL, "[In 'Doctor' mode], I spent a good ten minutes telling Emacs what Ithought of it.  (The response was, 'Perhaps you could try to be lessabusive.')	-- Matt Welsh", NULL),
(NULL, "I would rather spend 10 hours reading someone else's source code than10 minutes listening to Musak waiting for technical support which isn't.	-- Dr. Greg Wettstein, Roger Maris Cancer Center", NULL),
(NULL, "...[Linux's] capacity to talk via any medium except smoke signals.	-- Dr. Greg Wettstein, Roger Maris Cancer Center", NULL),
(NULL, "Whip me.  Beat me.  Make me maintain AIX.	-- Stephan Zielinski", NULL),
(NULL, "Your job is being a professor and researcher: That's one hell of a good excusefor some of the brain-damages of minix.	-- Linus Torvalds to Andrew Tanenbaum", NULL),
(NULL, "I still maintain the point that designing a monolithic kernel in 1991 is afundamental error.  Be thankful you are not my student.  You would not get ahigh grade for such a design :-)	-- Andrew Tanenbaum to Linus Torvalds", NULL),
(NULL, "We use Linux for all our mission-critical applications.  Having the source codemeans that we are not held hostage by anyone's support department.	-- Russell Nelson, President of Crynwr Software", NULL),
(NULL, "Linux is obsolete	-- Andrew Tanenbaum", NULL),
(NULL, "Dijkstra probably hates me.	-- Linus Torvalds, in kernel/sched.c", NULL),
(NULL, "And 1.1.81 is officially BugFree(tm), so if you receive any bug-reportson it, you know they are just evil lies.	-- Linus Torvalds", NULL),
(NULL, "We are Pentium of Borg.  Division is futile.  You will be approximated.	-- seen in someone's .signature", NULL),
(NULL, "Linux: the operating system with a CLUE... Command Line User Environment.	-- seen in a posting in comp.software.testing", NULL),
(NULL, "quit   When the quit statement is read, the  bc  processor       is  terminated, regardless of where the quit state-       ment is found.  For example, \"if  (0  ==  1)  quit\"       will cause bc to terminate.	-- seen in the manpage for \"bc\". Note the \"if\" statement's logic", NULL),
(NULL, "Sic transit discus mundi	-- From the System Administrator's Guide, by Lars Wirzenius", NULL),
(NULL, "Sigh.  I like to think it's just the Linux people who want to be onthe \"leading edge\" so bad they walk right off the precipice.	-- Craig E. Groeschel", NULL),
(NULL, "We all know Linux is great... it does infinite loops in 5 seconds.	- Linus Torvalds about the superiority of Linux on the Amterdam Linux Symposium", NULL),
(NULL, "Waving away a cloud of smoke, I look up, and am blinded by a bright, whitelight.  It's God. No, not Richard Stallman, or Linus Torvalds, but God. Ina booming voice, He says: \"THIS IS A SIGN. USE LINUX, THE FREE UNIX SYSTEMFOR THE 386.	-- Matt Welsh", NULL),
(NULL, "The chat program is in public domain.  This is not the GNU public license.If it breaks then you get to keep both pieces.	-- Copyright notice for the chat program", NULL),
(NULL, "'Mounten' wird für drei Dinge benutzt: 'Aufsitzen' auf Pferde, 'einklinken'von Festplatten in Dateisysteme, und, nun, 'besteigen' beim Sex.	-- Christa Keil", NULL),
(NULL, "Manchmal stehe nachts auf und installier's mir einfach...	-- H0arry @ IRC", NULL),
(NULL, "'Mounting' is used for three things: climbing on a horse, linking in ahard disk unit in data systems, and, well, mounting during sex.	-- Christa Keil", NULL),
(NULL, "We are using Linux daily to UP our productivity - so UP yours!	-- Adapted from Pat Paulsen by Joe Sloan", NULL),
(NULL, "But what can you do with it?	-- ubiquitous cry from Linux-user partner", NULL),
(NULL, "/* * [...] Note that 120 sec is defined in the protocol as the maximum * possible RTT.  I guess we'll have to use something other than TCP * to talk to the University of Mars. * PAWS allows us longer timeouts and large windows, so once implemented * ftp to mars will work nicely. */	-- from /usr/src/linux/net/inet/tcp.c, concerning RTT [round trip time]", NULL),
(NULL, "DOS: n., A small annoying boot virus that causes random spontaneous system     crashes, usually just before saving a massive project.  Easily cured by     UNIX.  See also MS-DOS, IBM-DOS, DR-DOS.	-- David Vicker's .plan", NULL),
(NULL, "MSDOS didn't get as bad as it is overnight -- it took over ten yearsof careful development.	-- dmeggins@aix1.uottawa.ca", NULL),
(NULL, "LILO, you've got me on my knees!	-- David Black, dblack@pilot.njin.net, with apologies to Derek and theDominos, and Werner Almsberger", NULL),
(NULL, "I've run DOOM more in the last few days than I have the last fewmonths.  I just love debugging ;-)	-- Linus Torvalds", NULL),
(NULL, "Microsoft Corp., concerned by the growing popularity of the free 32-bitoperating system for Intel systems, Linux, has employed a number of topprogrammers from the underground world of virus development.  Bill Gates statedyesterday: \"World domination, fast -- it's either us or Linus\".  Mr. Torvaldswas unavailable for comment ...	-- Robert Manners, rjm@swift.eng.ox.ac.uk, in comp.os.linux.setup", NULL),
(NULL, "The only \"intuitive\" interface is the nipple.  After that, it's all learned.	-- Bruce Ediger, bediger@teal.csn.org, on X interfaces", NULL),
(NULL, "After watching my newly-retired dad spend two weeks learning how to make a newfolder, it became obvious that \"intuitive\" mostly means \"what the writer orspeaker of intuitive likes\".	-- Bruce Ediger, bediger@teal.csn.org, on X the intuitiveness of a Mac interface", NULL),
(NULL, "Now I know someone out there is going to claim, \"Well then, UNIX is intuitive,because you only need to learn 5000 commands, and then everything else followsfrom that! Har har har!\"	-- Andy Bates on \"intuitive interfaces\", slightly defending Macs", NULL),
(NULL, "> No manual is ever necessary.May I politely interject here: BULLSHIT.  That's the biggest Apple lie of all!	-- Discussion in comp.os.linux.misc on the intuitiveness of interfaces", NULL),
(NULL, "How do I type \"for i in *.dvi do xdvi $i done\" in a GUI?	-- Discussion in comp.os.linux.misc on the intuitiveness of interfaces", NULL),
(NULL, ">Ever heard of .cshrc?That's a city in Bosnia.  Right?	-- Discussion in comp.os.linux.misc on the intuitiveness of commands", NULL),
(NULL, "Who wants to remember that escape-x-alt-control-left shift-b puts you intosuper-edit-debug-compile mode?	-- Discussion on the intuitiveness of commands, especially Emacs", NULL),
(NULL, "Anyone who thinks UNIX is intuitive should be forced to write 5000 lines of code using nothing but vi or emacs.  AAAAACK!	-- Discussion on the intuitiveness of commands, especially Emacs", NULL),
(NULL, "Now, it we had this sort of thing:  yield -a     for yield to all traffic  yield -t     for yield to trucks  yield -f     for yield to people walking (yield foot)  yield -d t*  for yield on days starting with t...you'd have a lot of dead people at intersections, and traffic jams youwouldn't believe...	-- Discussion on the intuitiveness of commands", NULL),
(NULL, "Actually, typing random strings in the Finder does the equivalent offilename completion.	-- Discussion on file completion vs. the Mac Finder", NULL),
(NULL, "Not me, guy.  I read the Bash man page each day like a Jehovah's Witness readsthe Bible.  No wait, the Bash man page IS the bible.  Excuse me...	-- More on confusing aliases, taken from comp.os.linux.misc", NULL),
(NULL, "On the Internet, no one knows you're using Windows NT	-- Submitted by Ramiro Estrugo, restrugo@fateware.com", NULL),
(NULL, "> I'm an idiot..  At least this [bug] took about 5 minutes to find..Disquieting ...	-- Gonzalo Tornaria in response to Linus Torvalds's", NULL),
(NULL, "> I'm an idiot..  At least this [bug] took about 5 minutes to find..We need to find some new terms to describe the rest of us mere mortalsthen.	-- Craig Schlenter in response to Linus Torvalds's", NULL),
(NULL, "> I'm an idiot..  At least this [bug] took about 5 minutes to find..Surely, Linus is talking about the kind of idiocy that others aspire to :-).	-- Bruce Perens in response to Linus Torvalds's", NULL),
(NULL, "Never make any mistaeks.	-- Anonymous, in a mail discussion about to a kernel bug report", NULL),
(NULL, "+#if defined(__alpha__) && defined(CONFIG_PCI)+       /*+        * The meaning of life, the universe, and everything. Plus+        * this makes the year come out right.+        */+       year -= 42;+#endif	-- From the patch for 1.3.2: (kernel/time.c), submitted by Marcus Meissner", NULL),
(NULL, "As usual, this being a 1.3.x release, I haven't even compiled thiskernel yet.  So if it works, you should be doubly impressed.	-- Linus Torvalds, announcing kernel 1.3.3", NULL),
(NULL, "People disagree with me.  I just ignore them.	-- Linus Torvalds, regarding the use of C++ for the Linux kernel", NULL),
(NULL, "It's now the GNU Emacs of all terminal emulators.	-- Linus Torvalds, regarding the fact that Linux started off as a terminal emulator", NULL),
(NULL, "Audience: What will become of Linux when the Hurd is ready?Eric Youngdale: Err... is Richard Stallman here?	-- From the Linux conference in spring '95, Berlin", NULL),
(NULL, "Linux: The OS people choose without $200,000,000 of persuasion.	-- Mike Coleman", NULL),
(NULL, "The memory management on the PowerPC can be used to frighten small children.	-- Linus Torvalds", NULL),
(NULL, "... faster BogoMIPS calculations (yes, it now boots 2 seconds faster thanit used to: we're considering changing the name from \"Linux\" to \"InstaBOOT\"	-- Linus, in the announcement for 1.3.26", NULL),
(NULL, "... of course, this probably only happens for tcsh which uses wait4(),which is why I never saw it.  Serves people who use that abominationright 8^)	-- Linus Torvalds, about a patch that fixes getrusage for 1.3.26", NULL),
(NULL, "It's a bird..It's a plane..No, it's KernelMan, faster than a speeding bullet, to your rescue.Doing new kernel versions in under 5 seconds flat..	-- Linus, in the announcement for 1.3.27", NULL),
(NULL, "Eh, that's it, I guess.  No 300 million dollar unveiling event for thiskernel, I'm afraid, but you're still supposed to think of this as the\"happening of the century\" (at least until the next kernel comes along). 	-- Linus, in the announcement for 1.3.27", NULL),
(NULL, "Oh, and this is another kernel in that great and venerable \"BugFree(tm)\"series of kernels.  So be not afraid of bugs, but go out in the streetsand deliver this message of joy to the masses.	-- Linus, in the announcement for 1.3.27", NULL),
(NULL, "When you say 'I wrote a program that crashed Windows', people just stare atyou blankly and say 'Hey, I got those with the system, *for free*'.	-- Linus Torvalds", NULL),
(NULL, "Never trust an operating system you don't have sources for. ;-)	-- Unknown source", NULL),
(NULL, "> Linux is not user-friendly. It _is_ user-friendly.  It is not ignorant-friendly and idiot-friendly.	-- Seen somewhere on the net", NULL),
(NULL, "Keep me informed on the behaviour of this kernel..  As the \"BugFree(tm)\"series didn't turn out too well, I'm starting a new series called the\"ItWorksForMe(tm)\" series, of which this new kernel is yet anothershining example.	-- Linus, in the announcement for 1.3.29", NULL),
(NULL, "Seriously, the way I did this was by using a special /sbin/loader binarywith debugging hooks that I made (\"dd\" is your friend: binary editorsare for wimps).	-- Linus Torvalds, in an article on a dnserver", NULL),
(NULL, "(I tried to get some documentation out of Digital on this, but as far asI can tell even _they_ don't have it ;-)	-- Linus Torvalds, in an article on a dnserver", NULL),
(NULL, "Q: Why shouldn't I simply delete the stuff I never use, it's just taking up    space?A: This question is in the category of Famous Last Words..	-- From the Frequently Unasked Questions", NULL),
(NULL, "Q: What's the big deal about rm, I have been deleting stuff for years?  And    never lost anything.. oops!A: ...	-- From the Frequently Unasked Questions", NULL),
(NULL, "Linux is addictive, I'm hooked!	-- MaDsen Wikholm's .sig", NULL),
(NULL, "panic(\"Foooooooood fight!\");	-- In the kernel source aha1542.c, after detecting a bad segment list", NULL),
(NULL, "Convention organizer to Linus Torvalds: \"You might like to come with us to some licensed[1] place, and have some pizza.\"Linus: \"Oh, I did not know that you needed a license to eat pizza\".[1] Licenced - refers in Australia to a restaurant which has government licence to sell liquor.	-- Linus at a talk at the Melbourne University", NULL),
(NULL, "Footnotes are for things you believe don't really belong in LDP manuals,but want to include anyway.	-- Joel N. Weber II discussing the 'make' chapter of LPG", NULL),
(NULL, "Eh, that's it, I guess.  No 300 million dollar unveiling event for thiskernel, I'm afraid, but you're still supposed to think of this as the\"happening of the century\" (at least until the next kernel comes along).Oh, and this is another kernel in that great and venerable \"BugFree(tm)\"series of kernels. So be not afraid of bugs, but go out in the streetsand deliver this message of joy to the masses.	-- Linus Torvalds, on releasing 1.3.27", NULL),
(NULL, "Ok, I'm just uploading the new version of the kernel, v1.3.33, alsoknown as \"the buggiest kernel ever\".	-- Linus Torvalds", NULL),
(NULL, "Go not unto the Usenet for advice, for you will be told both yea and nay (andquite a few things that just have nothing at all to do with the question).	-- seen in a .sig somewhere", NULL),
(NULL, "Those who don't understand Linux are doomed to reinvent it, poorly.	-- unidentified source", NULL),
(NULL, "Look, I'm about to buy me a double barreled sawed off shotgun and showLinus what I think about backspace and delete not working.	-- some anonymous .signature", NULL),
(NULL, "I forgot to mention an important fact in the 1.3.67 announcement. In order to get a fully working kernel, you have to follow the steps below: - Walk around your computer widdershins 3 times, chanting \"Linus is   overworked, and he makes lousy patches, but we love him anyway\". Get   your spuouse to do this too for extra effect.  Children are optional. - Apply the patch included in this mail - Call your system \"Super-67\", and don't forget to unapply the patch   before you later applying the official 1.3.68 patch. - reboot	-- Linus Torvalds, announcing another kernel patch", NULL),
(NULL, "We apologize for the inconvenience, but we'd still like yout to test outthis kernel. 	-- Linus Torvalds, announcing another kernel patch", NULL),
(NULL, "The new Linux anthem will be \"He's an idiot, but he's ok\", as performed byMonthy Python.  You'd better start practicing.	-- Linus Torvalds, announcing another kernel patch", NULL),
(NULL, "How do you power off this machine?	-- Linus, when upgrading linux.cs.helsinki.fi, and after using the machine for several months", NULL),
(NULL, "Excusing bad programming is a shooting offence, no matter _what_ thecircumstances.	-- Linus Torvalds, to the linux-kernel list", NULL),
(NULL, "Linus?  Whose that?	-- clueless newbie on #Linux", NULL),
(NULL, "N: Phil LewisE: beans@bucket.ualr.eduD: Promised to send money if I would put his name in the source tree.S: PO Box 371S: North Little Rock, Arkansas 72115S: US	-- /usr/src/linux/CREDITS", NULL),
(NULL, "> You know you are \"there\" when you are known by your first name, and> are recognized.> Lemmie see, there is Madonna, and Linus, and ..... help me out here!Bill ? ;-)	-- From some postings on comp.os.linux.misc", NULL),
(NULL, "Whoa...I did a 'zcat /vmlinuz > /dev/audio' and I think I heard God...	-- mikecd on #Linux", NULL),
(NULL, "Some people have told me they don't think a fat penguin really embodies the grace of Linux, which just tells me they have never seen a angry penguin charging at them in excess of 100mph.  They'd be a lot more careful about what they say if they had. 	-- Linus Torvalds, announcing Linux v2.0", NULL),
(NULL, "MS-DOS, you can't live with it, you can live without it.	-- from Lars Wirzenius' .sig", NULL),
(NULL, "> If you don't need X then little VT-100 terminals are available for real > cheap.  Should be able to find decent ones used for around $40 each.> For that price, they're a must for the kitchen, den, bathrooms, etc.. :)You're right. Can you explain this to my wife? 	-- Seen on c.o.l.development.system, on the subject of extra terminals", NULL),
(NULL, ".. I used to get in more fights with SCO than I did my girlfriend, but now, thanks to Linux, she has more than happily accepted her place back at number one antagonist in my life.. 	-- Jason Stiefel, krypto@s30.nmex.com", NULL),
(NULL, "I mean, well, if it were not for Linux I might be roaming the streets lookingfor drugs or prostitutes or something.  Hannu and Linus have my highestadmiration (apple polishing mode off).	-- Phil Lewis, plewis@nyx.nyx.net", NULL),
(NULL, "> What does ELF stand for (in respect to Linux?)ELF is the first rock group that Ronnie James Dio performed with back in the early 1970's.  In constrast, a.out is a misspelling	 of the French word for the month of August.  What the two have in common is beyond me, but Linux users seem to use the two words together.	-- seen on c.o.l.misc", NULL),
(NULL, "\"Linux was made by foreign terrorists to take money from true US companieslike Microsoft.\" - Some AOL'er.\"To this end we dedicate ourselves...\" -Don	-- From the sig of \"Don\", don@cs.byu.edu", NULL),
(NULL, "Shoot me again.Just proving that the quickest way to solve the problem is to post awhine to the newsgroups: within moments the solution presents itself tome, and meanwhile my ass is hanging out on the Net... *sigh*... 	-- Dave Phillips, dlphilp@bright.net, about problem solving via news", NULL),
(NULL, "> Is there any hope for me? Am I just thick? Does anyone remember the> Rubiks Cube, it was easier!I found that the Rubiks cube and Linux are alike. Looks real confusinguntil you read the right book. :-)	-- seen on c.o.l.misc, about the \"Linux Learning Curve\"", NULL),
(NULL, "> I've hacked the Xaw3d library to give you a Win95 like interface and it> is named Xaw95. You can replace your Xaw3d library.Oh God, this is so disgusting!	-- seen on c.o.l.development.apps, about the \"Win95 look-alike\"", NULL),
(NULL, "Besides, its really not worthwhile to use more than two times your physical ram in swap (except in a select few situations). The performance of the system becomes so abysmal you'd rather heat pins under your toenails while reciting Windows95 source code and staring at porn flicks of Bob Dole than actually try to type something.	-- seen on c.o.l.development.system, about the size of the swap space", NULL),
(NULL, "> I get the following error messages at bootup, could anyone tell me > what they mean?> fcntl_setlk() called by process 51 (lpd) with broken flock() emulationThey mean that you have not read the documentation when upgrading thekernel.	-- seen on c.o.l.misc", NULL),
(NULL, "Only wimps use tape backup: _real_ men just upload their important stuff on ftp, and let the rest of the world mirror it ;)	-- Linus Torvalds, about his failing hard drive on linux.cs.helsinki.fi", NULL),
(NULL, "One of the things that hamper Linux's climb to world domination is theshortage of bad Computer Role Playing Games, or CRaPGs. No operating systemcan be considered respectable without one.	-- Brian O'Donnell, odonnllb@tcd.ie", NULL),
(NULL, "The game, anoraks.2.0.0.tgz, will be available from sunsite until somebodyresponsible notices it and deletes it, and shortly fromftp.mee.tcd.ie/pub/Brian, though they don't know that yet.	-- Brian O'Donnell, odonnllb@tcd.ie", NULL),
(NULL, "'Ooohh.. \"FreeBSD is faster over loopback, when compared to Linuxover the wire\". Film at 11.'	-- Linus Torvalds", NULL),
(NULL, "Q: Would you like to see the WINE list?A: What's on it, anything expensive?Q: No, just Solitaire and MineSweeper for now, but the WINE is free.	-- Kevin M. Bealer, about the WINdows Emulator", NULL),
(NULL, "So in the future, one 'client' at a time or you'll be spending CPU time with lots of little 'child processes'.	-- Kevin M. Bealer, commenting on the private life of a Linux nerd", NULL),
(NULL, "By the way, I can hardly feel sorry for you... All last night I had to listen to her tears, so great they were redirected to a stream.  What?  Of _course_ you didn't know.  You and your little group no longer have any permissions around here.  She changed her .lock files, too.	-- Kevin M. Bealer, commenting on the private life of a Linux nerd", NULL),
(NULL, "We should start referring to processes which run in the background by their correct technical name... paenguins.	-- Kevin M. Bealer, commenting on the penguin Linux logo", NULL),
(NULL, "We can use symlinks of course... syslogd would be a symlink to syslogp and ftpd and ircd would be linked to ftpp and ircp... and of course the point-to-point protocal paenguin.	-- Kevin M. Bealer, commenting on the penguin Linux logo", NULL),
(NULL, "This is a logical analogy too... anyone who's been around, knows the world is run by paenguins.  Always a paenguin behind the curtain, really getting things done.  And paenguins in politics--who can deny it?	-- Kevin M. Bealer, commenting on the penguin Linux logo", NULL),
(NULL, "Linux: Where Don't We Want To Go Today?	-- Submitted by Pancrazio De Mauro, paraphrasing some well-known sales talk", NULL),
(NULL, "The most important design issue... is the fact that Linux is supposed to be fun...	-- Linus Torvalds at the First Dutch International Symposium on Linux", NULL),
(NULL, "In short, at least give the penguin a fair viewing. If you still don'tlike it, that's ok: that's why I'm boss. I simply know better than you do.	-- Linus \"what, me arrogant?\" Torvalds, on c.o.l.advocacy", NULL),
(NULL, "<SomeLamer> what's the difference between chattr and chmod?<SomeGuru> SomeLamer: man chattr > 1; man chmod > 2; diff -u 1 2 | less	-- Seen on #linux on irc", NULL),
(NULL, "The linuX Files -- The Source is Out There.	-- Sent in by Craig S. Bell, goat@aracnet.com", NULL),
(NULL, "\"... being a Linux user is sort of like living in a house inhabitedby a large family of carpenters and architects. Every morning whenyou wake up, the house is a little different. Maybe there is a newturret, or some walls have moved. Or perhaps someone has temporarilyremoved the floor under your bed.\" - Unix for Dummies, 2nd Edition	-- found in the .sig of Rob Riggs, rriggs@tesser.com", NULL),
(NULL, "C is quirky, flawed, and an enormous success	-- Dennis M. Ritchie", NULL),
(NULL, "If Bill Gates is the Devil then Linus Torvalds must be the Messiah.	-- Unknown source", NULL),
(NULL, "Vini, vidi, Linux!	-- Unknown source", NULL),
(NULL, "Checking host system type...i586-unknown-linuxconfigure: error: sorry, this is the gnu os, not linux	-- Topic on #Linux", NULL),
(NULL, "It's easy to get on the internet and forget you have a life	-- Topic on #LinuxGER", NULL),
(NULL, "To kick or not to kick...	-- Somewhere on IRC, inspired by Shakespeare", NULL),
(NULL, "Linux - Where do you want to fly today?	-- Unknown source", NULL),
(NULL, "The easiest way to get the root password is to become system admin.	-- Unknown source", NULL),
(NULL, "The good thing about standards is that there are so many to choose from.	-- Andrew S. Tanenbaum", NULL),
(NULL, "The primary difference [...] is that the Java programm will reliably andobviously crash, whereas the C Program will do something obscure	-- Java Language Tutorial", NULL),
(NULL, "LOAD \"LINUX\",8,1	-- Topic on #LinuxGER", NULL),
(NULL, "Old MacLinus had a stack/l-i-n-u-x/and on this stack he had a trace/l-i-n-u-xwith an Oops-Oops here and an Oops-Oops therehere an Oops, there an Oops, everywhere an Oops-Oops.	-- tjimenez@site.gmu.edu, linux.dev.kernel", NULL),
(NULL, "Also another major deciding factor is availability of source code.It just gives everybody a warm fuzzy feeling knowing that there issource code available to the product you are using.  It allows everybodyto improve on the product and fix bugs etc. sooner that the author(s)would get the time/chance to.	-- Atif Khan", NULL),
(NULL, "> Also another major deciding factor is availability of source code.> It just gives everybody a warm fuzzy feeling knowing that there is> source code available to the product you are using.  It allows everybody> to improve on the product and fix bugs etc. sooner that the author(s)> would get the time/chance to.I think this is one the really BIG reasons for the snowball/onslaughtof Linux and the wealth of stuff available that gets enhanced fasterthan the real vendors can keep up.	-- Norman ", NULL),
(NULL, "Not only Guinness - Linux is good for you, too.	-- Banzai on IRC", NULL),
(NULL, "> NE-2000 clone.  Pentium optimizing gcc (pentium gcc pl8 I think).                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Build a kernel with the proper gcc. Reports with a non standard compilerare useless.	-- Alan Cox", NULL),
(NULL, "BTW: I have a better name for the software .... Microsoft InternetExploder.	-- George Bonser <grep@cris.com>", NULL),
(NULL, "Well, since MS cant be sure of the username of someone downloadingthings, they are going to play it safe and have everything dowloadedand executed by Explorer as suid root. That way, it will run on ANYsystem anywhere. :)	-- George Bonser <grep@cris.com>", NULL),
(NULL, "If you really want pure ASCII, save it as text... or browseit with your favorite browser...	-- Alexandre Maret <amaret@infomaniak.ch>", NULL),
(NULL, "Sorry for mailing this article, I've obviously made a typo (168!=186)that's the price for being up all night and doing some \"quick\"checks before you go to bed ....	-- Herbert Rosmanith <herp@wildsau.idv.uni-linz.ac.at>", NULL),
(NULL, "Just to remind everyone.  Today, Sept 17, is Linux's 5th birthday.  Sohappy birthday to all on the list.  Thanks go out to Linus and all theother hard-working maintainers for 5 wonderful fast paced years!	-- William E. Roadcap <roadcapw@cfw.com>", NULL),
(NULL, "Exporting beer from Finnland doesn't seem to be that much of a hassle,as the Lenigrad Cowboys brought a lot of their brew to the concerts inAustria.	-- Otmar Lendl <lendl@cosy.sbg.ac.at>", NULL),
(NULL, "Beeping is cute, if you are in the office ;)	-- Alan Cox", NULL),
(NULL, ">  Where in the US is Linus?He was in the \"Promise Land\".	-- David S. Miller <davem@caip.rutgers.edu>", NULL),
(NULL, ">       Yeah, Linus is in the US.>>       His source trees are in Finland.        OK, someone give him access -fast- ...... ;-)	-- babydr@nwrain.net, because of problems with the kernel", NULL),
(NULL, "Subject: Linux box finds it hard to wake up in the morningI've heard of dogs being like their owners, but Linux boxen?	-- Peter Hunter <peter.hunter@blackfriars.oxford.ac.uk>", NULL),
(NULL, "Win 95 is simplified for the user:User: What does this configuration thing do?You: It allows you to modify you settings, for networking,        hardware, protocols, ...User: Whoa! Layman's terms, please!You:  It changes stuff.User: That's what I'm looking for!  What can it change?You:  This part change IP forwarding.  It allows ...User: Simplify, simplify!  What can it do for ME?You:  Nothing, until you understand it.User: Well it makes me uncomfortable.  It looks so technical;      Get rid of it, I want a system *I* can understand.You:  But...User: Hey, who's system is this anyway?You:  (... rm this, rm that, rm /etc/* ...) \"All done.\"	-- Kevin M. Bealer <kmb203@psu.edu>", NULL),
(NULL, "*** PUBLIC flooding detected from erikyyy<lewnie> THAT's an erik, pholx.... ;)	-- Seen on #LinuxGER", NULL),
(NULL, "I've no idea when Linus is going to release 2.0.24, but if he takestoo long Im going to release a 2.0.24unoff and he can sound off allhe likes.	-- Alan Cox", NULL),
(NULL, "All the existing 2.0.x kernels are to buggy for 2.1.x to be themain goal.	-- Alan Cox", NULL),
(NULL, "Computers are useless.  They can only give you answers.	-- Pablo Picasso", NULL),
(NULL, "martin@bdsi.com (no longer valid - where are you now, Martin?)	-- from /usr/src/linux/drivers/cdrom/mcd.c", NULL),
(NULL, "[...] or some clown changed the chips on a board and not its name.(Don't laugh!  Look at the SMC etherpower for that.)	-- from /usr/src/linux/MAINTAINERS", NULL),
(NULL, "REST:P:      Linus TorvaldsS:      Buried alive in email	-- from /usr/src/linux/MAINTAINERS", NULL),
(NULL, "         Why use Windows when you can have air conditioning?         Why use Windows, when you can leave through the door?	-- Konrad Blum", NULL),
(NULL, "Netscape is not a newsreader, and probably never shall be.	-- Tom Christiansen", NULL),
(NULL, "I think it's time to remove Qt and Qt-derived applications from the distributon.By distributing it, we only encourage authors to create restrictive licenses.	-- Bruce Perens", NULL),
(NULL, "If someone can point me to a good and _FREE_ backup software that keepstrack of which files get stored on which tape, we can change to it.	-- Mike Neuffer, admin of i-Connect Corp.", NULL),
(NULL, "Whoa, first contact![...]Welcome, from the people of Terra (Sol III). We extend our hands infriendship, and sincerely hope you shall do the same with yourhand-equivelents.	-- Jason Burrell about a russian posting", NULL),
(NULL, "> Whoa, first contact!Nope, 'fraid not, Linux is still primarily used on planet Earth, I'mafraid.Our friend here sent a message in Russian (KOI8-R encoding).	-- Aleksey Kliger, explaining a russian posting", NULL),
(NULL, "There is, however, a strange, musty smell in the air that reminds me ofsomething...hmm...yes...I've got it...there's a VMS nearby, or I'm a Blit.	-- Larry Wall in Configure from the perl distribution", NULL),
(NULL, "Das ganze Saarland ist von M$ besetzt - das ganze? Nein eine kleineGruppe im Sudwesten trotzt dem ubergrosen Herrscher dank ihresZaubertrankes Linux	-- Tooster on #LinuxGER", NULL),
(NULL, "1648 files (84%) out of the files that I mirror disappeared.  Sincemy delete threshold was set at 90%, all those files are now missingfrom my hard drive.  It's going to take a loooong time to fetch thoseagain via 14.4kbps!	-- Brian C. White", NULL),
(NULL, "Whoever asked if the debian organization was dead isn't readingdebian-devel. 66 messages in one day, and it's not over. I find itdifficult to keep up.	-- Bruce Perens", NULL),
(NULL, ">    What is the status of Linux' Unicode implementation. Will Linux>    be prepared for the first contact?We have full klingon console support just in case	-- Alan Cox on linux-kernel", NULL),
(NULL, "\"You, sir, are nothing but a pathetically lame salesdroid!I fart in your general direction!\"	-- Randseed on #Linux", NULL),
(NULL, "* Jes wonders why so many people in here uses fooZZZZZ and foo_sleeping nicks<peter> Jes: Because they are sleeping?	-- Seen on #Linux", NULL),
(NULL, "* gb notes that fdisk thinks his cdrom can store one terabyte	-- Seen on #Linux", NULL),
(NULL, "Check it out, send me comments, and dance joyously in the streets,	-- Linus Torvalds announcing 2.0.27", NULL),
(NULL, "AP/STT.  Helsinki, Dec 5th, 6:22 AM.  For immediate release.In order to allay fears about the continuity of the Linux project, LinusTorvalds together with his manager Tove Monni have released \"Linusv2.0\", affectionately known as \"Kernel Hacker - The Next Generation\".Linux stock prices on Wall Street rose sharply after the announcement;as one well-known analyst who wishes to remain anonymous says - \"Itshows a long-term commitment, and while we expect a short-term decreasein productivity, we feel that this solidifies the development in thelong run\".Other analysts downplay the importance of the event, and claim that justabout anybody could have done it.  \"I'm glad somebody finally told themabout the birds and the bees\" one sceptic comments cryptically.  Buteven the skeptics agree that it is an interesting turn of events.Others bring up other issues with the new version - \"I'm especiallyintrigued by the fact that the new version is female, and look forwardto seeing what the impact of that will be on future development.  Will\"Red Hat Linux\" change to \"Pink Hat Linux\", for example?\"	-- Linus Torvalds announcing that he became father of a girl", NULL),
(NULL, "Sex dumps core(Sex is a Simple editor for X11)	-- Seen on debian bugtracking", NULL),
(NULL, "I tried the clone syscall on me, but it didn't work.	-- Mike Neuffer trying to fix a serious time problem", NULL),
(NULL, "-  long    f_ffree;    /* free file nodes in fs */+  long    f_ffree;    /* freie Dateiknoten im Dateisystem */	-- Seen in a translation", NULL),
(NULL, "* Phaedrus wishes he could get a machine that consists of Sparc IO,  Alpha Processors and sleek design of an SGI<pp> And intel prices	-- Seen on #Linux", NULL),
(NULL, "<Tazman> damn my office is cold.<Tazman> need a hot secretary to warm it up.	-- Seen on #Linux", NULL),
(NULL, "This is a scsi driver, scraes the shit out of me, therefore I tapdancedand wrote a unix clone around it (C) by linus	-- Somewhere in the kernel tree", NULL),
(NULL, " *  This is complicated.  Has to do with interrupts.  Thus, I am *  scared witless.  Therefore I refuse to write this function. :-P	-- From the maclinux patch", NULL),
(NULL, "Yes I have a Machintosh, please don't scream at me.	-- Larry Blumette on linux-kernel", NULL),
(NULL, "<miguel> any new sendmail hole I have to fix before going on vacations?	-- Seen on #Linux", NULL),
(NULL, "AUTHORFvwmAuto just appeared one day, nobody knows how.	-- FvwmAuto(1x)", NULL),
(NULL, "<lilo> Fairlight: udp is the light margarine of tcp/ip transport protocols :)	-- Seen on #Linux", NULL),
(NULL, "i dont even know if it makes sense at all :) This is an experimental patchfor an experimental kernel :))	-- Ingo Molnar on linux-kernel", NULL),
(NULL, "Linux - Das System fuer schlaue Maedchen ;)	-- banshee", NULL),
(NULL, "If loving linux is wrong, I dont wanna be right.	-- Topic for #LinuxGER", NULL),
(NULL, ">>> FreeOS is an english-centric nameHave you all been stuck in email, or have any of you tried*pronouncing* that? free-oh-ess? free-ows? fritos? :-)	-- Mark Eichin", NULL),
(NULL, "The documentation is in Japanese.  Good luck.	-- Rich $alz", NULL),
(NULL, "People are going to scream bloody murder about that.	-- Seen on linux-kernel", NULL),
(NULL, ">   1. is qmail as secure as they say?Depends on what they were saying, but most likely yes.	-- Seen on debian-devel", NULL),
(NULL, "NEVER RESPOND TO CRITICAL PRESS.  IT IS A GAME YOU CAN ONLY LOSE, AND ITMAKES US LOOK BAD.	-- Bruce Perens", NULL),
(NULL, "A feature is nothing more than a bug with seniority.	-- Unknown source", NULL),
(NULL, "Winnuke in one line?  No problem:perl -MIO::Socket -e 'IO::Socket::INET->new(PeerAddr=>\"bad.dude.com:139\")->send(\"bye\",MSG_OOB)'And formatted so it's a little easier to read:        #!/usr/bin/perl        use IO::Socket;        IO::Socket::INET                ->new(PeerAddr=>\"bad.dude.com:139\")                ->send(\"bye\", MSG_OOB);	-- Randal Schwartz", NULL),
(NULL, "(It is an old Debian tradition to leave at least twice a year ...)	-- Sven Rudolph", NULL),
(NULL, "If a 'train station' is where a train stops, what's a 'workstation'?", NULL),
(NULL, "Computers are not intelligent.  They only think they are.", NULL),
(NULL, "\"We don't do a new version to fix bugs.\" - Bill Gates\"The new version - it's not there to fix bugs.\" - Bill Gates	-- Retranslated from Focus 43/1995, pp. 206-212", NULL),
(NULL, "The POP3 server service depends on the SMTP server service, whichfailed to start because of the following error:The operation completed successfully.	-- Windows NT Server v3.51", NULL),
(NULL, "Software is like sex; it's better when it's free.	-- Linus Torvalds", NULL),
(NULL, "vi is [[13~^[[15~^[[15~^[[19~^[[18~^ amuk[^[[29~^[[34~^[[26~^[[32~^ch better editor than this emacs. I knowI^[[14~'ll get flamed for this but the truth has to besaid. ^[[D^[[D^[[D^[[D ^[[D^[^[[D^[[D^[[B^exit ^X^C quit :x :wq dang it :w:w:w :x ^C^C^Z^D	-- Jesper Lauridsen <rorschak@daimi.aau.dk> from alt.religion.emacs", NULL),
(NULL, "oh okay. my mistake.Yafcot:atj(*),mark* Yet another fool coming over this: according to joey	-- mark@mail.novare.net", NULL),
(NULL, "Sorry.  I just realized this sentance makes no sense :)	-- Ian Main", NULL),
(NULL, "Netscape is not a newsreader, and probably never shall be.	-- Tom Christiansen", NULL),
(NULL, "Stopping Apache webserver...sleeping...starting again...apache: dl-version.c:189: _dl_check_map_versions: Assertion `needed != ((void *)0)' failednoooooooooooooooooooooooooooo	-- netgod on #Debian at LISC", NULL),
(NULL, "Make it idiot-proof, and someone will breed a better idiot.	-- Oliver Elphick", NULL),
(NULL, "#Debian makes me feel all warm and fuzzy inside. :)	-- HippieGuy on #Debian", NULL),
(NULL, "<Myxie> I know. Unless htere is a cookie monster somewhere between us tat muches the amil.<Myxie> amil/mail<Myxie> muches/munches tat/that htere/there<HippieGuy> heheh<HippieGuy> problems? :)* Myxie needs an ircii addon that pipes teh command line through ispell :)	-- Seen on #Debian", NULL),
(NULL, "ECRC hat keine lynx komp. seiten, sowas MUSS ja pleite gehen ;-)=	-- Getty on #LinuxGER", NULL),
(NULL, "Uh... deity is a word, and diety isn't.Or is it supposed to be one of those recursive acronyms?  Diety IsExcellent To You.  Deity Eats Icecream That's Yellow.  Diety IsEloping To Yokohama.  I'll stop now.	-- Guy Maor", NULL),
(NULL, "Why are there always boycotts?  Shouldn't there be girlcotts too?	-- argon on #Linux", NULL),
(NULL, "<sct> Anyone want the new supermount? :)<klogd> whats new aboutit<sct> klogd: It cleans whiter than white. :)	-- Seen on #Linux", NULL),
(NULL, "Und die Tastaturabrdücke auf Ihrer Wange unterstreichen seeeeeehrvorteilhaft ihr unterschütterliches Vertrauen in die modereneTechnologie	-- Agent Gully in \"Die eXakten\"", NULL),
(NULL, "- DDD no longer requires the librx library.  Consequently, librx  errors can no more cause DDD to crash.	-- DDD", NULL),
(NULL, "snafu = Situation Normal All F%$*ed up", NULL),
(NULL, "It's computer hardware, of course it's worth having <g>	-- Espy on #Debian", NULL),
(NULL, "Alan E. Davis: Some files at llug.sep.bnl.gov/pub/debian/Incoming arestamped on 10 January 1998.  As I write, nowhere on Earth is it now 10 January.Craig Sanders: That just proves how advanced debian is, doesn't it :-)	-- debian-devel", NULL),
(NULL, "Computers are like air conditioners.  Both stop working, if you open windows.	-- Adam Heath", NULL),
(NULL, "I am NOT a kludge!  I am a computer!	-- tts", NULL),
(NULL, "<Joey> gorgo: *lol*<gorgo> joey: what's so funny? :)<Culus> shh, joey is losing all sanity from lack of sleep<Culus> 'yes joey, very funny'<Culus> Humor him :>	-- Seen on #Debian", NULL),
(NULL, "* SynrG notes that the number of configuration questions to answer in sendmail  is NON-TRIVIAL	-- Seen on #Debian", NULL),
(NULL, "My apologies if I sound angry.  I feel like I'm talking to a void.	-- Avery Pennarun", NULL),
(NULL, "RIP is irrelevant.  Spoofing is futile.  Your routes will be aggregated.	-- Alex Yuriev", NULL),
(NULL, "After 14 non-maintainer releases, I'm the S-Lang non-maintainer.	-- Ray Dassen", NULL),
(NULL, "BREAKFAST.COM Halted... Cereal Port Not Responding.", NULL),
(NULL, "* JHM wonders what Joey did to earn \"I'd just like to say, for the record,  that Joey rules.\"	-- Seen on #Debian", NULL),
(NULL, "Steal my cash, car and TV - but leave the computer!	-- Soenke Lange <soenke@escher.north.de>", NULL),
(NULL, "The only really good reason I can think to not release specs isembarrassment on just how crappy some hardware out there is, or just howbuggy it is.	-- Chris Wedgwood <cw@ix.net.nz>", NULL),
(NULL, "> Alan Cox wrote:[..]No I didnt.  Someone else wrote that.  Please keep attributionsstraight.	-- From linux-kernel", NULL),
(NULL, "Do people like check the Debian website every 5 minutes to check it hasn't morphed into another one?Not that I'm one to talk, but some people seriously need to get a life	-- james on #Debian", NULL),
(NULL, "... Linux und seine Programme sind damit so etwas wie ein real existierenderSozialismus der besseren Art ...	-- Christian Seel in der Berliner Morgenpost v. 9.3.1997", NULL),
(NULL, "* james would be more impressed if netgod's magic powers could stop the splits in the first place...* netgod notes debian developers are notoriously hard to impress	-- Seen on #Debian", NULL),
(NULL, "   * In anticipation of 2.10.02 release, updated to patchlevel     +ircu2.10.01+.config6-7.config7-8.lgline3.iwho.limit.glibc.motdcache2.trace.whois1-2.config8-9.statsw.sprintf2-3.msgtree2.memleak1-2+.msgtree2-3.gline8-9.gline9-10.invite2.rbr.stats.numclients.whisper.whisper1-2.stats1-2.nokick1-2.chroot.config9-11.snomask7-8.limi+t1-3.userip1-3.userip3-4.config11-12.config12-13.umode2-3.akillsbt.who4-5.kn.kn1-2.freebsdcore2.msgtree3-5.y2k.glibc1-2.rmfunc.msgf+lags2.who5-6.nickchange2.glibc2-3.modeless3	-- From the annoucement of ircd 2.10.01-3 for Debian GNU/Linux", NULL),
(NULL, "* Joey should not write changelog entries at 5:30am<Joey>    * DFSC Free cgi library<Joey> What's that? DFSC?<jim> Debian Free Software mroooooCows	-- Seen on #Debian", NULL),
(NULL, "<posix> this guy _is_ crazy<stargazer> posix: from the looks of Enlightenment he's on LSD<posix> LSD is nothing compared to what this guy's on..	-- Seen on #Unix", NULL),
(NULL, "On Netscape GPLing their browser: ``How can you trust a browser thatANYONE can hack? For the secure choice, choose Microsoft.''	-- <oryx@pobox.com> in a comment on slashdot.org", NULL),
(NULL, "Turn right here. No! NO! The OTHER right!", NULL),
(NULL, "#define FALSE   0               /* This is the naked Truth */#define TRUE    1               /* and this is the Light */	-- mailto.c", NULL),
(NULL, "<Stealth> How do I bind a computer to an NIS server?<Joey> Use a rope?	-- Seen on #Debian", NULL),
(NULL, "Try to remove the color-problem by restarting your computer several times.	-- Microsoft-Internet Explorer README.TXT", NULL),
(NULL, "Does biff in bo workcoz it biffin doesn't beepan if biff in bo is brokethen biff in bo I will deleteI've tried biff in bo with 'y'I've tried biff in bo with '-y'no biffin output does it showso poor wee biff is gonna go.	-- John Spence <jspence@lynx.net.au> on debian-user", NULL),
(NULL, "Real Men don't make backups.  They upload it via ftp and let the world mirror it.	-- Linus Torvalds", NULL),
(NULL, "One tree to rule them all,One tree to find them,One tree to bring them all,and to itself bind them.	-- Gavin Koch <gavin@cygnus.com>", NULL),
(NULL, "As I currently don't have a floppy drive in my computer, I'd like tomake an `emergency cdrom' ;)	-- Eugene Crosser <crosser@average.org>", NULL),
(NULL, "Alan Cox wrote:>> On any procmail new enough not to be full of security holes you set>Brain on, Imeant majordomo of course 8)You got me worried there for a brief (very brief) moment :-).	-- Stephen R. van den Berg (AKA BuGless)", NULL),
(NULL, "<grin> seen jhm<dpkg> jhm is Sarek, and jhm is on the channel right now!* JHM wonders why dpkg remembers that particular nick.<grin> dpkg: Sarek? ermm, sure, and I am Khan	-- Seen on #Debian", NULL),
(NULL, "When you have 200 programmers trying to write code for oneproduct, like Win95 or NT, what you get is a multipule personalityprogram.  By definition, the real problem is that these programs arepsychotic by nature and make people crazy when they use them.	-- Joan Brewer on alt.destroy.microsoft", NULL),
(NULL, "<igor> Hah! we have 2 Johnie Ingrams in the channel :)<igor> Hey all btw :)", NULL),
(NULL, "I just uploaded xtoolplaces-1.6. It fixes all bugs but one: It stillcoredumps instead of doing something useful.  The upstream author'se-mail address bounces, Redhat doesn't provide it and I never used it.	-- Sven Rudolph <sr1@os.inf.tu-dresden.de>", NULL),
(NULL, "> I thing you're missing the capability of Makefiles.        It takes several _hours_ to do `make' a second time on mymachine with the latest glibc sources (and no files are recompiled asecond time).  I think I'll remove `build' after changing one file ifI want to recompile it.	-- Juan Cespedes <cespedes@debian.org>", NULL),
(NULL, "<Culus> aIIIIIIIIIII!!!!!!!!!!!!!!!11<Culus> MY LIGHT JUST DIED<Culus> I AM SO SAD<Culus> I'm blind! I'm blind!<dark> Light?<dark> Turn all your xterms to black-on-white :)  Plenty of light that way.	-- Seen on #Debian", NULL),
(NULL, "| |-sshd---tcsh-+-dpkg-buildpacka---rules---sh---make---make---sh---make---sh---make---sh---make---sh---make---sh---make	-- While packaging XFree86 for Debian GNU/Linux", NULL),
(NULL, "/* *     Please skip to the bottom of this file if you ate lunch recently *                             -- Alan */	-- from Linux kernel pre-2.1.91-1", NULL),
(NULL, "#if _FP_W_TYPE_SIZE < 64#error \"Only stud muffins allowed, schmuck.\"#endif	-- linux/arch/sparc64/quad.c", NULL),
(NULL, "#if _FP_W_TYPE_SIZE < 32#error \"Here's a nickel kid.  Go buy yourself a real computer.\"#endif	-- linux/arch/sparc64/double.h", NULL),
(NULL, "<dark> eat Depends: cook | eat-out.       But eat-out is non-free so that's out.       And cook Recommends: clean-pans.	-- Seen on #Debian", NULL),
(NULL, "* Linux Viruscan.....  Windows 95 found.  Remove it? (Y/y)	-- Unknown source", NULL),
(NULL, "<sel> need help: my first packet to my provider gets lost :-(<netgod> sel:  dont send the first one, start with #2* netgod is kidding", NULL),
(NULL, "These download files are in Microsoft Word 6.0 format. Afterunzipping, these files can be viewed in any text editor, includingall versions of Microsoft Word, WordPad, and Microsoft Word Viewer	-- From Micro$oft", NULL),
(NULL, "<james> abuse me.  I'm so lame I sent a bug report to debian-devel-changes	-- Seen on #Debian", NULL),
(NULL, "Ooh, mommy, mommy, what I have now doesn't work in this extremelyunlikely circumstance, so I'll just throw it away and write somethingcompletely new.	-- Linus Torvalds", NULL),
(NULL, "#ifdef __SMP__#error \"Me no hablo Alpha SMP\"#else#define irq_enter(cpu, irq)     (++local_irq_count[cpu])#define irq_exit(cpu, irq)      (--local_irq_count[cpu])#endif	-- from kernel 2.1.90, arch/alpha/kernel/irc.c", NULL),
(NULL, "Linus Torvalds:> This is the special easter release of linux, more mundanely called 1.3.84Winfried Truemper:> Umh, oh. What do you mean by \"special easter release\"?. Will it quit> working today and rise on easter?", NULL),
(NULL, "I never thought that I'd see the day where Netscape is free software andX11 is proprietary.  We live in interesting times.	-- Matt Kimball <mkimball@xmission.com>", NULL),
(NULL, "Because I don't need to worry about finances I can ignore Microsoftand take over the (computing) world from the grassroots.	-- Linus Torvalds", NULL),
(NULL, "/* * Buddy system. Hairy. You really aren't expected to understand this * */	-- From /usr/src/linux/mm/page_alloc.cA", NULL),
(NULL, "baz bat bamus batis bant.	-- James Troup", NULL),
(NULL, "Just go ahead and write your own multitasking multiuser os!Worked for me all the times.	-- Linus Torvalds", NULL),
(NULL, "I've seen people with new children before, they go from ultra happy tolooking like something out of a zombie film in about a week.	-- Alan Cox about Linus after his 2nd daughter", NULL),
(NULL, "I expect that noone has objections.  However, if I'd only add these entriesto the list because `I think it's the right thing to do', I'd get a lot offlames afterwards :)	-- Christian Schwarz", NULL),
(NULL, "Various documentation updates and bugfixes (the best way to know that astable kernel is approaching is to notice that somebody starts tospellcheck the kernel - it has so far never failed)	-- Linus Torvalds in the annoucement for pre-2.1.99-3", NULL),
(NULL, "You will not censor me through bug terrorism.	-- James Troup", NULL),
(NULL, "<doogie> Thinking is dangerous.  It leads to ideas.	-- Seen on #Debian", NULL),
(NULL, "<james> Are we going to make an emacs out of apt?        APT - Debian in a program.  It even does your laundry	-- Seen on #Debian", NULL),
(NULL, "<joost> Do you mean to say that I can read mail with vi too? ;-)<Joey> Didn't you know that?<Joey> :r /var/spool/mail/jk	-- debian-mentors", NULL),
(NULL, "Charles Briscoe-Smith <cpbs@debian.org>:  After all, the gzip package is called `gzip', not `libz-bin'...James Troup <troup@debian.org>:  Uh, probably because the gzip binary doesn't come from the  non-existent libz package or the existent zlib package.	-- debian-bugs-dist", NULL),
(NULL, "Debian is like Suse with yast turned off, just better. :)	-- Goswin Brederlow", NULL),
(NULL, "Arnold's Laws of Documentation:	(1) If it should exist, it doesn't.	(2) If it does exist, it's out of date.	(3) Only documentation for useless programs transcends the	    first two laws.", NULL),
(NULL, "The truth is not free.  It's that simple.  If you change the truth, it is nolonger true - so the truth is not free!	-- Jules Bean about freeness of documentation", NULL),
(NULL, "<jim> Lemme make sure I'm not wasting time here... bcwhite will remove      pkgs that havent been fixed that have outstanding bugs of severity      \"important\".  True or false?<JHM> jim: \"important\" or higher.  True.<jim> Then we're about to lose ftp.debian.org and dpkg :)* netgod will miss dpkg -- it was occasionally useful<Joey> We still have rpm....	-- Seen on #Debian", NULL),
(NULL, "* JHM wonders what Joey did to earn \"I'd just like to say, for the record,  that Joey rules.\"	-- Seen on #Debian", NULL),
(NULL, "The problem here (as someon else stated) is that when multiple distsuse the same package format it only gives a \"false sense of compatibility\".	-- Stephen Carpenter <sjc@delphi.com>", NULL),
(NULL, "*** Rince is wagner@schizo.DAINet.de (We have Joey, we have Fun, we have Linux on a Sun)	-- Seen on #Debian", NULL),
(NULL, "... Linux und seine Programme sind damitso etwas wie ein real existierender Sozialismus der besseren Art...	-- Christian Seel in der Berliner Morgenpost v. 9.3.1997", NULL),
(NULL, "The most effective has probably been Linux/8086 - that was a jokethat got out of hand.  So far out of hand in fact its almost approachingusability because other folks thought it worth doing - Alistair Riddochespecially.	-- Alan Cox", NULL),
(NULL, "The only other people who might benefit from Linux8086 would be ownersof PDP/11's and other roomsized computers from the same era.	-- Alan Cox", NULL),
(NULL, "Ha. I say let them try -- even vi+perl couldn't match the power of aneditor which is, after all, its own OS.  ;-)	-- Johnie Ingram on debian-devel, about linking vim with libperl.so", NULL),
(NULL, "Being overloaded is the sign of a true Debian maintainer.	-- JHM on #Debian", NULL),
(NULL, "<alaint> joey--very clever !!!<alaint> joey--no wonder that Debian is a good distrib with coder like you	-- Seen on #Debian (referring to my RAID article for the LJ)", NULL),
(NULL, "There are 3 kinds of people: those who can count & those who can't.	-- Unknown source", NULL),
(NULL, "Despite the best efforts of a quantum bigfoot drive (yes I know everyonetold me they suck, now I know they were right) 2.1.109ac1 is now available	-- Alan Cox announcing Linux 2.1.109ac1", NULL),
(NULL, "<dark> Turns out that grep returns error code 1 when there are no matches.       I KNEW that.  Why did it take me half an hour?	-- Seen on #Debian", NULL),
(NULL, "It's simply unbelievable how much energy and creativity people haveinvested into creating contradictory, bogus and stupid licenses...	--- Sven Rudolph about licences in debian/non-free.", NULL),
(NULL, "<Overfiend> partycle: I seriously do need a vacation from this            package.  I actually had a DREAM about introducing a            stupid new bug into xbase-preinst last night.  That's a            Bad Sign.	-- Seen on #Debian shortly before the release of Debian 2.0", NULL),
(NULL, "<core> i'm glad Debian finally got into        polar-deep-freeze-we-arent-shitting-you state finally.	-- Seen on #Debian shortly before the release of Debian 2.0", NULL),
(NULL, "<dark> Looks like the channel is back to normal :)<jim> You mean it's not scrolling faster than anyone can read? :)	-- Seen on #Debian after the release of Debian 2.0", NULL),
(NULL, "Alex Buell:Or how about a Penguin logo painted in really really trippycolours, and emblazoned with the word LSD. :o)Geert Uytterhoeven:We already had that one, but unfortunately Russell King fixed that nastypalette bug in drivers/video/fbcon.c :-)	-- linux-kernel", NULL),
(NULL, "Writing non-free software is not an ethically legitimate activity,so if people who do this run into trouble, that's good!  All businessesbased on non-free software ought to fail, and the sooner the better.	-- Richard Stallman", NULL),
(NULL, "Außerdem noch [..] die Distribution für Puristen, denen technischeEleganz und Qualität und philosophisch reine Lehre der `freien Software'über totale Einfachheit geht (Debian) und viele mehr.	-- Anselm Lingnau in de.comp.os.unix.discussion", NULL),
(NULL, "Fehlermeldung von StarOffice:Das Dokument wurde fuer den Drucker Generic PostScript Printer formatiert.Der Drucker ist nicht vorhanden.  Soll der Standarddrucker GenericPostScript Printer verwendet werden?Ob Programme schizophren werden koennen?	-- Oliver Bedford <O.Bedford@uni-koeln.de>", NULL),
(NULL, "No, that's wrong too.  Now there's a race condition between the rm andthe mv.  Hmm, I need more coffee.	-- Guy Maor on Debian Bug#25228", NULL),
(NULL, "Perhaps the RBLing (Realtime Black Hole) of msn.com recently, whichprevented a large amount of mail going out for about 4 days, has had apositive influence in Redmond.  They did agree to work on their anti-relaycapabilities at their POPs to get the RBL lifted.	-- Bill Campbell on Smail3-users", NULL),
(NULL, "Microsoft DNS service terminates abnormally when it recieves a responseto a DNS query that was never made.  Fix Information: Run your DNSservice on a different platform.	-- bugtraq", NULL),
(NULL, "I am amazed that no-one's based a commercial distribution on Debianyet - it is by far the most solid UNIX-like OS I've ever installed,and I've played with HP/UX, Solaris, FreeBSD, BSDi, and SCO (not tomention OS/2, Novell, Win95/NT)	-- Nathan E. Norman", NULL),
(NULL, "Jim>   http://www.novare.net/~eam/kaffe/Joey>                           ^Joey> And now we all learn how to write Ean's name and the URL is complete.Jim> Hah!  I noticed that the instead I sent it, and I tried to hit ^g, but     I was too slow.  :-)	--- debian-devel", NULL),
(NULL, "Die TeX-Artikel [..] aber doch inzwischen wohl nicht mehr an denFingern zweier Hände abzählbar (außer vielleicht von Informatikern,die bekanntlich mit den Fingern bis 1023 zählen können.	-- Anselm Lingnau", NULL),
(NULL, "And Bruce is effectively building BruceIX	-- Alan Cox", NULL),
(NULL, "<Culus-> I will be known as Ian Black, Ean can be Ian Red, Netgod Ian Blue,         Che gets Ian Yellow, CQ is Ian Purple and Joey is Ian Indigo	-- Some #Debian channel", NULL),
(NULL, "When a float occurs on the same page as the start of a supertabularyou can expect unexpected results.	-- Documentation of supertabular.sty", NULL),
(NULL, "From: Ean Schuessler <ean@novare.net>The unrecognized minister of propaganda,E	-- Debian, joking", NULL),
(NULL, "* liw prefers not to have Linus run Debian, because then /me would  have to run Red Hat, just to keep the power balance :)	-- #Debian", NULL),
(NULL, "<\\swing> and if we're playing old distributions... whatever happened to Yggdrasil? :)<joost> \\swing: everybody who tried to pronounce it got their tongue in a knot and choked	-- #Debian", NULL),
(NULL, "I'm telling you that the kernel is stable not because it's a kernel,but because I refuse to listen to arguments like this.	-- Linus Torvalds", NULL),
(NULL, "> Tut mir Leid, Jost, aber Du bist ein unertraeglicher Troll.Was soll das? Du *beleidigst* die Trolle!	-- de.comp.os.unix.linux.misc", NULL),
(NULL, "Wenn also die KDE-Arbeit nochmal gemacht wird bei GNOME, hat das dieEntwicklungszeit für ein freies Desktop-System verkürzt.  Hast Du auchirgendwo die passende Algebra zu der Rechnung?	-- Sascha Ziemann in de.comp.os.unix.linux.misc", NULL),
(NULL, "* dpkg ponders: 'C++' should have been called 'D'	-- #Debian", NULL),
(NULL, "<rm_-rf_> The real value of KDE is that they inspired and push the          development of GNOME :-)	-- #Debian", NULL),
(NULL, "* dpkg hands stu a huge glass of vbeer* Joey takes the beer from stu, you're too young ;)* Cylord takes the beer from Joey, you're too drunk.* Cylord gives the beer to muggles.	-- #Debian, celebrating the 5th anniversary", NULL),
(NULL, "<stu> Stupid nick highlighting<stu> Whenever someone starts with \"stupid\" it highlights the nick.  Hmm.	-- #Debian", NULL),
(NULL, "<netgod> And once Diziet/CQ make the formal announcment that LSA         sucks, we can even reduce the Crisis Level rating and move         on to linuxfoundation.org.	-- #Debian", NULL),
(NULL, "* LG loves czech girls.<vincent> LG: do they have additional interesting \"features\" other girls don't have? ;)	-- #Debian", NULL),
(NULL, "The first is to ensure your partner understands that nature has rootprivileges - nature doesn't have to make sense.	-- Telsa Gwynne", NULL),
(NULL, "As to house maintenance, does it involve problem solfing?  If so,your hacker can safely be left to deall with the panning (for the musement value, if nothering ese).	-- Telsa Gwynne", NULL),
(NULL, "Remember: While root can do most everything, there are certainprivileges that only a partner can grant.	-- Telsa Gwynne", NULL),
(NULL, "<Skyhook> Where is 'bavaria' proper?  I thought it was austria.	-- Seen on #Linux", NULL),
(NULL, "Day X+4 months: Microsoft ships NT 5.0 for Intel.with a big media                event on TV. IBM begins to ship Debian 4.6 as the                standard OS on all machines from mainframe to PC                and announces the move on Slashdot.	-- Christoph Lameter", NULL),
(NULL, "How many chunks could checkchunk check if checkchunk could check chunks?	-- Alan Cox", NULL),
(NULL, "Q: How does a Unix guru have sex?A: unzip;strip;touch;finger;mount;fsck;more;yes;umount;sleep	-- unknown source", NULL),
(NULL, "Someone on IRC was very sad about the uptime of his machine wrappingfrom 497 days to 0.	-- linux-kernel", NULL),
(NULL, "<doogie> netgod:  8:42pm is not late.<netgod> doogie: its 2:42am in Joeyland	-- #Debian", NULL),
(NULL, "We knew from experience that the essence of communal computing, assupplied by remote-access, time-shared machines, is not just to typeprograms into a terminal instead of a keypunch, but to encourage closecommunication.	-- Dennis Ritchie", NULL),
(NULL, "modconf (0.2.37) stable unstable; urgency=medium  [...]  * Eduard Bloch:    - fixed Makefile broken Marcin Owsiany a while ago. The default manpage      has been overwritten with the polish translation. I still wonder why      nobody noticed this before. Closes: #117474  [...] -- Eduard Bloch <blade@debian.org>  Sun, 28 Oct 2001 12:53:27 +0100", NULL),
(NULL, "<|ryan|> I don't use deb<netgod> u poor man<Disconnect> netgod: heh<Kingsqueak> apt-get install task-p0rn", NULL),
(NULL, "", NULL),
(NULL, "Could somebody drag the Irix team kicking and screaming into the 1980's, please? I realize it might be quite painful for them, but maybe you could buy them a disco tape, so they'd feel a little bit more at home. 		-- Linus \"Stayin' alive, stayin' alive\" Torvalds", NULL),
(NULL, "> <magical +3 sigh of hyperbole deflection>The branden dodges your magical sigh. The branden attacks you with aslew of words! The branden misses!	-- Henning Makholm in <yahsmr7dk9k.fsf@pc-043.diku.dk>", NULL),
(NULL, "I don't think 'It's better than hurling yourself into a meat grinder'is a good rationale for doing something.		-- Andrew Suffield in 		   <20030905221055.GA22354@doc.ic.ac.uk> on debian-devel", NULL),
(NULL, "< Overfiend> whew.< Overfiend> I really need to get some sleep.< Overfiend> but it sure was fun talking guitars, politics, and lesbians.", NULL),
(NULL, "", NULL)
