
DROP TABLE IF EXISTS `bot_fortunes_paradoxum`;
CREATE TABLE `bot_fortunes_paradoxum` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `quote` text NOT NULL,
  `props` int(10) NOT NULL default 0,
  PRIMARY KEY  (`id`)
); 

INSERT INTO `bot_fortunes_paradoxum` VALUES
(NULL, "", NULL),
(NULL, "  A little pain never hurt anyone.", NULL),
(NULL, "  \"A unified, neutral Germany? Given that nation's heritage, such a  phrase may prove to be the oxymoron of the decade.\" -Kevin M.  Matarese, Fulda, West Germany; as seen in \"Letters\", Time  magazine, p. 5, March 5, 1990.", NULL),
(NULL, "  A verbal contract isn't worth the paper it's written on. Include  me out. -Samuel Goldwyn", NULL),
(NULL, "  Christ was born in 4 B.C.", NULL),
(NULL, "  Cum tacent, clamant. When they are silent, they shout. -Cicero", NULL),
(NULL, "  Gentlemen, I want you to know that I am not always right, but I am  never wrong. -Samuel Goldwyn", NULL),
(NULL, "  Goes (Went) over like a lead balloon.", NULL),
(NULL, "  Honk if you are against noise pollution!", NULL),
(NULL, "  I'll give you a definite maybe. -Samuel Goldwyn", NULL),
(NULL, "  I'm not going to say, \"I told you so.\"", NULL),
(NULL, "  I am a deeply superficial person. -Andy Warhol", NULL),
(NULL, "  I'm proud of my humility.", NULL),
(NULL, "  I can resist everything except temptation. -Oscar Wilde", NULL),
(NULL, "  If Roosevelt were alive, he'd turn over in his grave. -Samuel  Goldwyn", NULL),
(NULL, "  If I could drop dead right now, I'd be the happiest man alive!  -Samuel Goldwyn", NULL),
(NULL, "  If you fall and break your legs, don't come running to me. -Samuel  Goldwyn", NULL),
(NULL, "  I never put on a pair of shoes until I've worn them five years.  -Samuel Goldwyn", NULL),
(NULL, "  It isn't an optical illusion. It just looks like one.", NULL),
(NULL, "  It's more than magnificent-it's mediocre. -Samuel Goldwyn", NULL),
(NULL, "  May I ask a question?", NULL),
(NULL, "  No one goes to that restaurant anymore-it's always too crowded.  (attributed to Yogi Berra)", NULL),
(NULL, "  Our comedies are not to be laughed at. -Samuel Goldwyn", NULL),
(NULL, "  Parting is such sweet sorrow. -William Shakespeare", NULL),
(NULL, "  Procrastination means never having to say you're sorry.", NULL),
(NULL, "  \"Professional certification for car people may sound like an  oxymoron.\" -The Wall Street Journal, page B1, Tuesday, July 17,  1990.", NULL),
(NULL, "  Referring to a book: I read part of it all the way through.  -Samuel Goldwyn", NULL),
(NULL, "  Smoking is the leading cause of statistics.", NULL),
(NULL, "  Some bachelors want a meaningful overnight relationship.", NULL),
(NULL, "  Talking about a piece of movie dialogue: Let's have some new  cliches. -Samuel Goldwyn", NULL),
(NULL, "  The scene is dull. Tell him to put more life into his dying.  -Samuel Goldwyn", NULL),
(NULL, "  Thank God I'm an atheist.", NULL),
(NULL, "  This report is filled with omissions.", NULL),
(NULL, "  We are not anticipating any emergencies.", NULL),
(NULL, "  We're overpaying him, but he's worth it. -Samuel Goldwyn", NULL),
(NULL, "  His honour rooted in dishonour stood,  And faith unfaithful kept him falsely true.  -Alfred Lord Tennyson", NULL),
(NULL, "  The good oxymoron, to define it by a self-illustration, must be a  planned inadvertency. -Wilson Follett", NULL),
(NULL, "  An Irishman is never at peace except when he's fighting.", NULL),
(NULL, "  I marvel at the strength of human weakness.", NULL),
(NULL, "  Always be sincere, even when you don't mean it. -Irene Peter", NULL),
(NULL, "  Live within your income, even if you have to borrow to do so.  -Josh Billings", NULL),
(NULL, "  Of course I can keep secrets. It's the people I tell them to that  can't keep them. -Anthony Haden-Guest", NULL),
(NULL, "  The best cure for insomnia is to get a lot of sleep. -W.C. Fields", NULL),
(NULL, "  I distinctly remember forgetting that. -Clara Barton", NULL),
(NULL, "  We must believe in free will. We have no choice. -Isaac B. Singer", NULL),
(NULL, "  I'd give my right arm to be ambidextrous.", NULL),
(NULL, "  Monotheism is a gift from the gods.", NULL),
(NULL, "  After they got rid of capital punishment, they had to hang twice  as many people as before.", NULL),
(NULL, "  I never liked you, and I always will. -Samuel Goldwyn", NULL),
(NULL, "  Why don't you pair `em up in threes? -Yogi Berra", NULL),
(NULL, "  Our similarities are different. -Dale Berra, son of Yogi", NULL),
(NULL, "  After Donald Trump's stretch limousine was stolen and found  undamaged a few blocks away; he said, \"Nothing was stolen. I had  an honest thief.\"-International Herald Tribune, page 3, March 2,  1992", NULL),
(NULL, "  Some bird populations soaring down 	-Headline of an article in 	 Science News, page 126, February 20, 1993.", NULL),
(NULL, "  Most bacteria have the decency to be microscopic. Epulopiscium  fishelsoni is not among them. The newly identified one-celled  macro-microorganism is a full .5 mm long, large enough to be seen  with the naked eye. Described in the current Nature, \"It is a  million times as massive as a typical bacterium.\"-Time, page 25,  March 29, 1993", NULL),
(NULL, "  \"Triumph without Victory, The Unreported History of the Persian  Gulf War\", -Headline published in the U.S. News & World Report,  1992.", NULL),
(NULL, "  An empty cab drove up and Sarah Bernhardt got out. -Arthur Baer,  American comic and columnist", NULL),
(NULL, "  She used to diet on any kind of food she could lay her hands on.  -Arthur Baer, American comic and columnist", NULL),
(NULL, "  The first condition of immortality is death. -Stanislaw Lec", NULL),
(NULL, "  As famous as the unknown soldier.", NULL),
(NULL, "  I must follow the people. Am I not their leader? -Benjamin Disraeli", NULL),
(NULL, "  Hegel was right when he said that we learn from history that man  can never learn anything from history. -George Bernard Shaw", NULL),
(NULL, "  William Safire's rules for writing as seen in the New York Times     Do not put statements in the negative form.     And don't start sentences with a conjunction.     If you reread your work, you will find on rereading that a great     deal of repetition can be avoided by rereading and editing.     Never use a long word when a diminutive one will do.     Unqualified superlatives are the worst of all.     If any word is improper at the end of a sentence, a linking verb is.     Avoid trendy locutions that sound flaky.     Never, ever use repetitive redundancies.     Also, avoid awkward or affected alliteration.     Last, but not least, avoid cliche's like the plague.", NULL),
(NULL, "  Everyone writes on the walls except me. -Said to be graffiti seen in Pompeii", NULL),
(NULL, "  I tripped over a hole that was sticking up out of the ground.", NULL),
(NULL, "  I don't think anyone should write their autobiography until after  they're dead. -Samuel Goldwyn", NULL),
(NULL, "  This page intentionally left blank.", NULL),
(NULL, "  Evil isn't all bad.", NULL),
(NULL, "  I disagree with unanimity.", NULL),
(NULL, "  \"It's a step forward although there was no progress.\"  President Hosni Murbarak of Egypt attempting to put the best face  on a disappointing summit meeting between President Clinton and  the Syrian dictator Hafez Assad.", NULL),
(NULL, "  \"I always avoid prophesying beforehand because it is much better  to prophesy after the event has already taken place. \" - Winston  Churchill", NULL),
(NULL, " All truths are true to an extend, including this one.  -XA", NULL),
(NULL, " Assume a virtue, if you have it not.  -William Shakespeare", NULL),
(NULL, " All generalisations are dangerous, including this one.", NULL)
