
DROP TABLE IF EXISTS `bot_fortunes_riddles`;
CREATE TABLE `bot_fortunes_riddles` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `quote` text NOT NULL,
  `props` int(10) NOT NULL default 0,
  PRIMARY KEY  (`id`)
); 

INSERT INTO `bot_fortunes_riddles` VALUES
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #13A:	Doc, Happy, Bashful, Dopey, Sneezy, Sleepy, & GrumpyQ:	Who were the Democratic presidential candidates?", NULL),
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #15A:	The Royal Canadian Mounted Police.Q:	What was the greatest achievement in taxidermy?", NULL),
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #19A:	To be or not to be.Q:	What is the square root of 4b^2?", NULL),
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #21A:	Dr. Livingston I. Presume.Q:	What's Dr. Presume's full name?", NULL),
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #31A:	Chicken Teriyaki.Q:	What is the name of the world's oldest kamikaze pilot?", NULL),
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #4A:	Go west, young man, go west!Q:	What do wabbits do when they get tiwed of wunning awound?", NULL),
(NULL, "FORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #5A:	The Halls of Montezuma and the Shores of Tripoli.Q:	Name two families whose kids won't join the Marines.", NULL),
(NULL, "Knock, knock!	Who's there?Sam and Janet.	Sam and Janet who?Sam and Janet Evening...", NULL),
(NULL, "Knucklehead:	\"Knock, knock\"Pee Wee:	\"Who's there?\"Knucklehead:	\"Little ol' lady.\"Pee Wee:	\"Liddle ol' lady who?\"Knucklehead:	\"I didn't know you could yodel\"", NULL),
(NULL, "Q:	\"What is the burning question on the mind of every dyslexic	existentialist?\"A:	\"Is there a dog?\"", NULL),
(NULL, "Q:	Are we not men?A:	We are Vaxen.", NULL),
(NULL, "Q:	Do you know what the death rate around here is?A:	One per person.", NULL),
(NULL, "Q:	Heard about the <ethnic> who couldn't spell?A:	He spent the night in a warehouse.", NULL),
(NULL, "Q:	How can you tell when a Burroughs salesman is lying?A:	When his lips move.", NULL),
(NULL, "Q:	How did you get into artificial intelligence?A:	Seemed logical -- I didn't have any real intelligence.", NULL),
(NULL, "Q:	How do you catch a unique rabbit?A:	Unique up on it!Q:	How do you catch a tame rabbit?A:	The tame way!", NULL),
(NULL, "Q:	How do you keep a moron in suspense?", NULL),
(NULL, "Q:	How do you know when you're in the <ethnic> section of Vermont?A:	The maple sap buckets are hanging on utility poles.", NULL),
(NULL, "Q:	How do you play religious roulette?A:	You stand around in a circle and blaspheme and see who gets	struck by lightning first.", NULL),
(NULL, "Q:	How do you save a drowning lawyer?A:	Throw him a rock.", NULL),
(NULL, "Q:	How do you shoot a blue elephant?A:	With a blue-elephant gun.Q:	How do you shoot a pink elephant?A:	Twist its trunk until it turns blue, then shoot it with	a blue-elephant gun.", NULL),
(NULL, "Q:	How do you stop an elephant from charging?A:	Take away his credit cards.", NULL),
(NULL, "Q:	How does a hacker fix a function which	doesn't work for all of the elements in its domain?A:	He changes the domain.", NULL),
(NULL, "Q:	How does the Polish Constitution differ from the American?A:	Under the Polish Constitution citizens are guaranteed freedom of	speech, but under the United States constitution they are	guaranteed freedom after speech.		-- being told in Poland, 1987", NULL),
(NULL, "Q:	How many Bell Labs Vice Presidents does it take to change a light bulb?A:	That's proprietary information.  Answer available from AT&T on payment	of license fee (binary only).", NULL),
(NULL, "Q:	How many bureaucrats does it take to screw in a light bulb?A:	Two.  One to assure everyone that everything possible is being	done while the other screws the bulb into the water faucet.", NULL),
(NULL, "Q:	How many Californians does it take to screw in a light bulb?A:	Five.  One to screw in the light bulb and four to share the		experience.  (Actually, Californians don't screw in		light bulbs, they screw in hot tubs.)Q:	How many Oregonians does it take to screw in a light bulb?A:	Three.  One to screw in the light bulb and two to fend off all		those Californians trying to share the experience.", NULL),
(NULL, "Q:	How many college football players does it take to screw in a light bulb?A:	Only one, but he gets three credits for it.", NULL),
(NULL, "Q:	How many DEC repairman does it take to fix a flat?A:	Five; four to hold the car up and one to swap tires.Q:	How long does it take?A:	It's indeterminate.	It will depend upon how many flats they've brought with them.Q:	What happens if you've got TWO flats?A:	They replace your generator.", NULL),
(NULL, "Q:	How many elephants can you fit in a VW Bug?A:	Four.  Two in the front, two in the back.Q:	How can you tell if an elephant is in your refrigerator?A:	There's a footprint in the mayo.Q:	How can you tell if two elephants are in your refrigerator?A:	There's two footprints in the mayo.Q:	How can you tell if three elephants are in your refrigerator?A:	The door won't shut.Q:	How can you tell if four elephants are in your refrigerator?A:	There's a VW Bug in your driveway.", NULL),
(NULL, "Q:	How many existentialists does it take to screw in a light bulb?A:	Two.  One to screw it in and one to observe how the light bulb	itself symbolizes a single incandescent beacon of subjective	reality in a netherworld of endless absurdity reaching out toward a	maudlin cosmos of nothingness.", NULL),
(NULL, "Q:	How many gradual (sorry, that's supposed to be \"graduate\") students	does it take to screw in a light bulb?A:	\"I'm afraid we don't know, but make my stipend tax-free, give my	advisor a $30,000 grant of the taxpayer's money, and I'm sure he	can tell me how to do the shit work for him so he can take the	credit for answering this incredibly vital question.\"", NULL),
(NULL, "Q:	How many hardware engineers does it take to change a light bulb?A:	None.  We'll fix it in software.Q:	How many system programmers does it take to change a light bulb?A:	None.  The application can work around it.Q:	How many software engineers does it take to change a light bulb?A:	None.  We'll document it in the manual.Q:	How many tech writers does it take to change a light bulb?A:	None.  The user can figure it out.", NULL),
(NULL, "Q:	How many Harvard MBA's does it take to screw in a light bulb?A:	Just one.  He grasps it firmly and the universe revolves around him.", NULL),
(NULL, "Q:	How many IBM 370's does it take to execute a job?A:	Four, three to hold it down, and one to rip its head off.", NULL),
(NULL, "Q:	How many IBM CPU's does it take to do a logical right shift?A:	33.  1 to hold the bits and 32 to push the register.", NULL),
(NULL, "Q:	How many IBM types does it take to change a light bulb?A:	Fifteen.  One to do it, and fourteen to write document number	GC7500439-0001, Multitasking Incandescent Source System Facility,	of which 10% of the pages state only \"This page intentionally	left blank\", and 20% of the definitions are of the form \"A:.....	consists of sequences of non-blank characters separated by blanks\".", NULL),
(NULL, "Q:	How many journalists does it take to screw in a light bulb?A:	Three.  One to report it as an inspired government program to bring	light to the people, one to report it as a diabolical government plot	to deprive the poor of darkness, and one to win a Pulitzer prize for	reporting that Electric Company hired a light bulb-assassin to break	the bulb in the first place.", NULL),
(NULL, "Q:	How many lawyers does it take to change a light bulb?A:	One.  Only it's his light bulb when he's done.", NULL),
(NULL, "Q:	How many lawyers does it take to change a light bulb?A:	Whereas the party of the first part, also known as \"Lawyer\", and theparty of the second part, also known as \"Light Bulb\", do hereby and forthwithagree to a transaction wherein the party of the second part shall be removedfrom the current position as a result of failure to perform previously agreedupon duties, i.e., the lighting, elucidation, and otherwise illumination ofthe area ranging from the front (north) door, through the entryway, terminatingat an area just inside the primary living area, demarcated by the beginning ofthe carpet, any spillover illumination being at the option of the party of thesecond part and not required by the aforementioned agreement between theparties.	The aforementioned removal transaction shall include, but not belimited to, the following.  The party of the first part shall, with or withoutelevation at his option, by means of a chair, stepstool, ladder or any othermeans of elevation, grasp the party of the second part and rotate the partyof the second part in a counter-clockwise direction, this point being tenderednon-negotiable.  Upon reaching a point where the party of the second partbecomes fully detached from the receptacle, the party of the first part shallhave the option of disposing of the party of the second part in a mannerconsistent with all relevant and applicable local, state and federal statutes.Once separation and disposal have been achieved, the party of the first partshall have the option of beginning installation.  Aforesaid installation shalloccur in a manner consistent with the reverse of the procedures described instep one of this self-same document, being careful to note that the rotationshould occur in a clockwise direction, this point also being non-negotiable.The above described steps may be performed, at the option of the party of thefirst part, by any or all agents authorized by him, the objective being toproduce the most possible revenue for the Partnership.", NULL),
(NULL, "Q:	How many lawyers does it take to change a light bulb?A:	You won't find a lawyer who can change a light bulb.  Now, if	you're looking for a lawyer to screw a light bulb...", NULL),
(NULL, "Q:	How many marketing people does it take to change a light bulb?A:	I'll have to get back to you on that.", NULL),
(NULL, "Q:	How many Martians does it take to screw in a light bulb?A:	One and a half.", NULL),
(NULL, "Q:	How many Marxists does it take to screw in a light bulb?A:	None:  The light bulb contains the seeds of its own revolution.", NULL),
(NULL, "Q:	How many mathematicians does it take to screw in a light bulb?A:	One.  He gives it to six Californians, thereby reducing the problem	to the earlier joke.", NULL),
(NULL, "Q:	How many members of the U.S.S. Enterprise does it take to change a	light bulb?A:	Seven.  Scotty has to report to Captain Kirk that the light bulb in	the Engineering Section is getting dim, at which point Kirk will send	Bones to pronounce the bulb dead (although he'll immediately claim	that he's a doctor, not an electrician).  Scotty, after checking	around, realizes that they have no more new light bulbs, and complains	that he \"canna\" see in the dark.  Kirk will make an emergency stop at	the next uncharted planet, Alpha Regula IV, to procure a light bulb	from the natives, who, are friendly, but seem to be hiding something.	Kirk, Spock, Bones, Yeoman Rand and two red shirt security officers	beam down to the planet, where the two security officers are promply	killed by the natives, and the rest of the landing party is captured.	As something begins to develop between the Captain and Yeoman Rand,	Scotty, back in orbit, is attacked by a Klingon destroyer and must	warp out of orbit.  Although badly outgunned, he cripples the Klingon	and races back to the planet in order to rescue Kirk et. al. who have	just saved the natives' from an awful fate and, as a reward, been	given all light bulbs they can carry.  The new bulb is then inserted	and the Enterprise continues on its five year mission.", NULL),
(NULL, "Q:	How many Oregonians does it take to screw in a light bulb?A:	Three.  One to screw in the light bulb and two to fend off all those	Californians trying to share the experience.", NULL),
(NULL, "Q:	How many psychiatrists does it take to change a light bulb?A:	Only one, but it takes a long time, and the light bulb has	to really want to change.", NULL),
(NULL, "Q:	How many supply-siders does it take to change a light bulb?A:	None.  The darkness will cause the light bulb to change by itself.", NULL),
(NULL, "Q:	How many surrealists does it take to change a light bulb?A:	Two, one to hold the giraffe, and the other to fill the bathtub	with brightly colored machine tools.	[Surrealist jokes just aren't my cup of fur.  Ed.]", NULL),
(NULL, "Q:	How many WASPs does it take to change a light bulb?A:	One.", NULL),
(NULL, "Q:	How many Zen masters does it take to screw in a light bulb?A:	None.  The Universe spins the bulb, and the Zen master stays out	of the way.", NULL),
(NULL, "Q:	How much does it cost to ride the Unibus?A:	2 bits.", NULL),
(NULL, "Q:	How was Thomas J. Watson buried?A:	9 edge down.", NULL),
(NULL, "Q:	Know what the difference between your latest project	and putting wings on an elephant is?A:	Who knows?  The elephant *might* fly, heh, heh...", NULL),
(NULL, "Q:	Minnesotans ask, \"Why aren't there more pharmacists from Alabama?\"A:	Easy.  It's because they can't figure out how to get the little	bottles into the typewriter.", NULL),
(NULL, "Q:	What did Tarzan say when he saw the elephants coming over the hill?A:	\"The elephants are coming over the hill.\"Q:	What did he say when saw them coming over the hill wearing		sunglasses?A:	Nothing, for he didn't recognize them.", NULL),
(NULL, "Q:	What do agnostic, insomniac dyslexics do at night?A:	Stay awake and wonder if there's a dog.", NULL),
(NULL, "Q:	What do little WASPs want to be when they grow up?A:	The very best person they can possibly be.", NULL),
(NULL, "Q:	What do monsters eat?A:	Things.Q:	What do monsters drink?A:	Coke.  (Because Things go better with Coke.)", NULL),
(NULL, "Q:	What do they call the alphabet in Arkansas?A:	The impossible dream.", NULL),
(NULL, "Q:	What do Winnie the Pooh and John the Baptist have in common?A:	The same middle name.", NULL),
(NULL, "Q:	What do you call 15 blondes in a circle?A:	A dope ring.Q:	Why do blondes put their hair in ponytails?A:	To cover up the valve stem.", NULL),
(NULL, "Q:	What do you call a blind pre-historic animal?A:	Diyathinkhesaurus.Q:	What do you call a blind pre-historic animal with a dog?A:	Diyathinkhesaurus Rex.", NULL),
(NULL, "Q:	What do you call a blind, deaf-mute, quadraplegic Virginian?A:	Trustworthy.", NULL),
(NULL, "Q:	What do you call a boomerang that doesn't come back?A:	A stick.", NULL),
(NULL, "Q:	What do you call a half-dozen Indians with Asian flu?A:	Six sick Sikhs (sic).", NULL),
(NULL, "Q:	What do you call a principal female opera singer whose high C	is lower than those of other principal female opera singers?A:	A deep C diva.", NULL),
(NULL, "Q:	What do you call a WASP who doesn't work for his father, isn't a	lawyer, and believes in social causes?A:	A failure.", NULL),
(NULL, "Q:	What do you call the money you pay to the government when	you ride into the country on the back of an elephant?A:	A howdah duty.", NULL),
(NULL, "Q:	What do you call the scratches that you get when a female	sheep bites you?A:	Ewe nicks.", NULL),
(NULL, "Q:	What do you get when you cross a mobster with an international standard?A:	You get someone who makes you an offer that you can't understand!", NULL),
(NULL, "Q:	What do you get when you cross the Godfather with an attorney?A:	An offer you can't understand.", NULL),
(NULL, "Q:	What do you have when you have a lawyer buried up to his neck in sand?A:	Not enough sand.", NULL),
(NULL, "Q:	What do you say to a New Yorker with a job?A:	Big Mac, fries and a Coke, please!", NULL),
(NULL, "Q:	What does a WASP Mom make for dinner?A:	A crisp salad, a hearty soup, a lovely entree, followed by	a delicious dessert.", NULL),
(NULL, "Q:	What does friendship among Soviet nationalities mean?A:	It means that the Armenians take the Russians by the hand; the	Russians take the Ukrainians by the hand; the Ukranians take	the Uzbeks by the hand; and they all go and beat up the Jews.", NULL),
(NULL, "Q:	What does it say on the bottom of Coke cans in North Dakota?A:	Open other end.", NULL),
(NULL, "Q:	What happens when four WASPs find themselves in the same room?A:	A dinner party.", NULL),
(NULL, "Q:	What is green and lives in the ocean?A:	Moby Pickle.", NULL),
(NULL, "Q:	What is orange and goes \"click, click?\"A:	A ball point carrot.", NULL),
(NULL, "Q:	What is printed on the bottom of beer bottles in Minnesota?A:	Open other end.", NULL),
(NULL, "Q:	What is purple and commutes?A:	An Abelian grape.", NULL),
(NULL, "Q:	What is purple and concord the world?A:	Alexander the Grape.", NULL),
(NULL, "Q:	What is the difference between a duck?A:	One leg is both the same.", NULL),
(NULL, "Q:	What is the difference between Texas and yogurt?A:	Yogurt has culture.", NULL),
(NULL, "Q:	What is the sound of one cat napping?A:	Mu.", NULL),
(NULL, "Q:	What lies on the bottom of the ocean and twitches?A:	A nervous wreck.", NULL),
(NULL, "Q:	What looks like a cat, flies like a bat, brays like a donkey, and	plays like a monkey?A:	Nothing.", NULL),
(NULL, "Q:	What's a light-year?A:	One-third less calories than a regular year.", NULL),
(NULL, "Q:	What's a WASP's idea of open-mindedness?A:	Dating a Canadian.", NULL),
(NULL, "Q:	What's buried in Grant's tomb?A:	A corpse.", NULL),
(NULL, "Q:	What's hard going in and soft and sticky coming out?A:	Chewing gum.", NULL),
(NULL, "Q:	What's tan and black and looks great on a lawyer?A:	A doberman.", NULL),
(NULL, "Q:	What's the contour integral around Western Europe?A:	Zero, because all the Poles are in Eastern Europe!Addendum: Actually, there ARE some Poles in Western Europe, but they	are removable!Q:	An English mathematician (I forgot who) was asked by his	very religious colleague: Do you believe in one God?A:	Yes, up to isomorphism!Q:	What is a compact city?A:	It's a city that can be guarded by finitely many near-sighted	policemen!		-- Peter Lax", NULL),
(NULL, "Q:	What's the difference betweeen USL and the Graf Zeppelin?A:	The Graf Zeppelin represented cutting edge technology for its time.", NULL),
(NULL, "Q:	What's the difference between a dead dog in the road and a dead	lawyer in the road?A:	There are skid marks in front of the dog.", NULL),
(NULL, "Q:	What's the difference between a duck and an elephant?A:	You can't get down off an elephant.", NULL),
(NULL, "Q:	What's the difference between a Mac and an Etch-a-Sketch?A:	You don't have to shake the Mac to clear the screen.", NULL),
(NULL, "Q:	What's the difference between an Irish wedding and an Irish wake?A:	One less drunk.", NULL),
(NULL, "Q:	What's the difference between Bell Labs and the Boy Scouts of America?A:	The Boy Scouts have adult supervision.", NULL),
(NULL, "Q:	What's the difference between the 1950's and the 1980's?A:	In the 80's, a man walks into a drugstore and states loudly, \"I'd	like some condoms,\" and then, leaning over the counter, whispers,	\"and some cigarettes.\"", NULL),
(NULL, "Q:	What's the difference between USL and the Titanic?A:	The Titanic had a band.", NULL),
(NULL, "Q:	What's tiny and yellow and very, very, dangerous?A:	A canary with the super-user password.", NULL),
(NULL, "Q:	What's yellow, and equivalent to the Axiom of Choice?A:	Zorn's Lemon.", NULL),
(NULL, "Q:	Where's the Lone Ranger take his garbage?A:	To the dump, to the dump, to the dump dump dump!Q:	What's the Pink Panther say when he steps on an ant hill?A:	Dead ant, dead ant, dead ant dead ant dead ant...", NULL),
(NULL, "Q:	Who cuts the grass on Walton's Mountain?A:	Lawn Boy.", NULL),
(NULL, "Q:	Why did Menachem Begin invade Lebanon?A:	To impress Jodie Foster.", NULL),
(NULL, "Q:	Why did the astrophysicist order three hamburgers?A:	Because he was hungry.", NULL),
(NULL, "Q:	Why did the chicken cross the road?A:	He was giving it last rites.", NULL),
(NULL, "Q:	Why did the chicken cross the road?A:	To see his friend Gregory peck.Q:	Why did the chicken cross the playground?A:	To get to the other slide.", NULL),
(NULL, "Q:	Why did the germ cross the microscope?A:	To get to the other slide.", NULL),
(NULL, "Q:	Why did the lone ranger kill Tonto?A:	He found out what \"kimosabe\" really means.", NULL),
(NULL, "Q:	Why did the programmer call his mother long distance?A:	Because that was her name.", NULL),
(NULL, "Q:	Why did the tachyon cross the road?A:	Because it was on the other side.", NULL),
(NULL, "Q:	Why did the WASP cross the road?A:	To get to the middle.", NULL),
(NULL, "Q:	Why do ducks have big flat feet?A:	To stamp out forest fires.Q:	Why do elephants have big flat feet?A:	To stamp out flaming ducks.", NULL),
(NULL, "Q:	Why do firemen wear red suspenders?A:	To conform with departmental regulations concerning uniform dress.", NULL),
(NULL, "Q:	Why do mountain climbers rope themselves together?A:	To prevent the sensible ones from going home.", NULL),
(NULL, "Q:	Why do people who live near Niagara Falls have flat foreheads?A:	Because every morning they wake up thinking \"What *is* that noise?	Oh, right, *of course*!", NULL),
(NULL, "Q:	Why do the police always travel in threes?A:	One to do the reading, one to do the writing, and the other keeps	an eye on the two intellectuals.", NULL),
(NULL, "Q:	Why do WASPs play golf ?A:	So they can dress like pimps.", NULL),
(NULL, "Q:	Why does Washington have the most lawyers per capita and	New Jersey the most toxic waste dumps?A:	God gave New Jersey first choice.", NULL),
(NULL, "Q:	Why don't lawyers go to the beach?A:	The cats keep trying to bury them.", NULL),
(NULL, "Q:	Why don't Scotsmen ever have coffee the way they like it?A:	Well, they like it with two lumps of sugar.  If they drink	it at home, they only take one, and if they drink it while	visiting, they always take three.", NULL),
(NULL, "Q:	Why haven't you graduated yet?A:	Well, Dad, I could have finished years ago, but I wanted	my dissertation to rhyme.", NULL),
(NULL, "Q:	Why is Christmas just like a day at the office?A:	You do all of the work and the fat guy in the suit	gets all the credit.", NULL),
(NULL, "Q:	Why is it that Mexico isn't sending anyone to the '84 summer games?A:	Anyone in Mexico who can run, swim or jump is already in LA.", NULL),
(NULL, "Q:	Why is it that the more accuracy you demand from an interpolation	function, the more expensive it becomes to compute?A:	That's the Law of Spline Demand.", NULL),
(NULL, "Q:	Why is Poland just like the United States?A:	In the United States you can't buy anything for zlotys and in	Poland you can't either, while in the U.S. you can get whatever	you want for dollars, just as you can in Poland.		-- being told in Poland, 1987", NULL),
(NULL, "Q:	Why should you always serve a Southern Carolina football man	soup in a plate?A:	'Cause if you give him a bowl, he'll throw it away.", NULL),
(NULL, "Q:	Why was Stonehenge abandoned?A:	It wasn't IBM compatible.", NULL),
(NULL, "", NULL)
