
DROP TABLE IF EXISTS `bot_fortunes_startrek`;
CREATE TABLE `bot_fortunes_startrek` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `quote` text NOT NULL,
  `props` int(10) NOT NULL default 0,
  PRIMARY KEY  (`id`)
); 

INSERT INTO `bot_fortunes_startrek` VALUES
(NULL, "A father doesn't destroy his children.		-- Lt. Carolyn Palamas, \"Who Mourns for Adonais?\",		   stardate 3468.1.", NULL),
(NULL, "A little suffering is good for the soul.		-- Kirk, \"The Corbomite Maneuver\", stardate 1514.0", NULL),
(NULL, "A man either lives life as it happens to him, meets it head-on andlicks it, or he turns his back on it and starts to wither away.		-- Dr. Boyce, \"The Menagerie\" (\"The Cage\"), stardate unknown", NULL),
(NULL, "A princess should not be afraid -- not with a brave knight to protect her.		-- McCoy, \"Shore Leave\", stardate 3025.3", NULL),
(NULL, "A star captain's most solemn oath is that he will give his life, evenhis entire crew, rather than violate the Prime Directive.		-- Kirk, \"The Omega Glory\", stardate unknown", NULL),
(NULL, "A Vulcan can no sooner be disloyal than he can exist without breathing.		-- Kirk, \"The Menagerie\", stardate 3012.4", NULL),
(NULL, "A woman should have compassion.		-- Kirk, \"Catspaw\", stardate 3018.2", NULL),
(NULL, "Actual war is a very messy business.  Very, very messy business.		-- Kirk, \"A Taste of Armageddon\", stardate 3193.0", NULL),
(NULL, "After a time, you may find that \"having\" is not so pleasing a thing,after all, as \"wanting.\"  It is not logical, but it is often true.		-- Spock, \"Amok Time\", stardate 3372.7", NULL),
(NULL, "Ahead warp factor one, Mr. Sulu.", NULL),
(NULL, "All your people must learn before you can reach for the stars.		-- Kirk, \"The Gamesters of Triskelion\", stardate 3259.2", NULL),
(NULL, "Another Armenia, Belgium ... the weak innocents who always seem to belocated on a natural invasion route.		-- Kirk, \"Errand of Mercy\", stardate 3198.4", NULL),
(NULL, "Another dream that failed.  There's nothing sadder.		-- Kirk, \"This side of Paradise\", stardate 3417.3", NULL),
(NULL, "Another war ... must it always be so?  How many comrades have we lostin this way? ...  Obedience.  Duty.  Death, and more death ...		-- Romulan Commander, \"Balance of Terror\", stardate 1709.2", NULL),
(NULL, "... bacteriological warfare ... hard to believe we were once foolishenough to play around with that.		-- McCoy, \"The Omega Glory\", stardate unknown", NULL),
(NULL, "Beam me up, Scotty!", NULL),
(NULL, "Beam me up, Scotty!  It ate my phaser!", NULL),
(NULL, "Beam me up, Scotty, there's no intelligent life down here!", NULL),
(NULL, "	\"Beauty is transitory.\"	\"Beauty survives.\"		-- Spock and Kirk, \"That Which Survives\", stardate unknown", NULL),
(NULL, "Behind every great man, there is a woman -- urging him on.		-- Harry Mudd, \"I, Mudd\", stardate 4513.3", NULL),
(NULL, "Blast medicine anyway!  We've learned to tie into every organ in thehuman body but one.  The brain!  The brain is what life is all about.		-- McCoy, \"The Menagerie\", stardate 3012.4", NULL),
(NULL, "Bones: \"The man's DEAD, Jim!\"", NULL),
(NULL, "But Captain -- the engines can't take this much longer!", NULL),
(NULL, "But it's real.  And if it's real it can be affected ...  we may not be ableto break it, but, I'll bet you credits to Navy Beans we can put a dent in it.		-- deSalle, \"Catspaw\", stardate 3018.2", NULL),
(NULL, "\"Can you imagine how life could be improved if we could do away withjealousy, greed, hate ...\"\"It can also be improved by eliminating love, tenderness, sentiment --the other side of the coin\"		-- Dr. Roger Corby and Kirk, \"What are Little Girls Made Of?\",		   stardate 2712.4", NULL),
(NULL, "Captain's Log, star date 21:34.5...", NULL),
(NULL, "Change is the essential process of all existence.		-- Spock, \"Let That Be Your Last Battlefield\", stardate 5730.2", NULL),
(NULL, "Compassion -- that's the one things no machine ever had.  Maybe it'sthe one thing that keeps men ahead of them.		-- McCoy, \"The Ultimate Computer\", stardate 4731.3", NULL),
(NULL, "Computers make excellent and efficient servants, but I have no wish toserve under them.  Captain, a starship also runs on loyalty to oneman.  And nothing can replace it or him.		-- Spock, \"The Ultimate Computer\", stardate 4729.4", NULL),
(NULL, "Conquest is easy. Control is not.		-- Kirk, \"Mirror, Mirror\", stardate unknown", NULL),
(NULL, "Dammit Jim, I'm an actor, not a doctor.", NULL),
(NULL, "Death, when unnecessary, is a tragic thing.		-- Flint, \"Requiem for Methuselah\", stardate 5843.7", NULL),
(NULL, "Death.  Destruction.  Disease.  Horror.  That's what war is all about.That's what makes it a thing to be avoided.		-- Kirk, \"A Taste of Armageddon\", stardate 3193.0", NULL),
(NULL, "Deflector shields just came on, Captain.", NULL),
(NULL, "Do you know about being with somebody?  Wanting to be?  If I had thewhole universe, I'd give it to you, Janice.  When I see you, I feellike I'm hungry all over.  Do you know how that feels?		-- Charlie Evans, \"Charlie X\", stardate 1535.8", NULL),
(NULL, "Do you know the one -- \"All I ask is a tall ship, and a star to steerher by ...\"  You could feel the wind at your back, about you ...  thesounds of the sea beneath you.  And even if you take away the wind andthe water, it's still the same.  The ship is yours ... you can feel her... and the stars are still there.		-- Kirk, \"The Ultimate Computer\", stardate 4729.4", NULL),
(NULL, "[Doctors and Bartenders], We both get the same two kinds of customers-- the living and the dying.		-- Dr. Boyce, \"The Menagerie\" (\"The Cage\"), stardate unknown", NULL),
(NULL, "Each kiss is as the first.		-- Miramanee, Kirk's wife, \"The Paradise Syndrome\",		   stardate 4842.6", NULL),
(NULL, "EARL GREY PROFILESNAME:		Jean-Luc Perriwinkle PicardOCCUPATION:	Starship Big CheeseAGE:		94BIRTHPLACE:	Paris, Terra SectorEYES:		GreySKIN:		TannedHAIR:		Not muchLAST MAGAZINE READ:		Lobes 'n' Probes, the Ferengi-Betazoid Sex QuarterlyTEA:		Earl Grey.  Hot.EARL GREY NEVER VARIES.", NULL),
(NULL, "Earth -- mother of the most beautiful women in the universe.		-- Apollo, \"Who Mourns for Adonais?\" stardate 3468.1", NULL),
(NULL, "Either one of us, by himself, is expendable.  Both of us are not.		-- Kirk, \"The Devil in the Dark\", stardate 3196.1", NULL),
(NULL, "Emotions are alien to me.  I'm a scientist.		-- Spock, \"This Side of Paradise\", stardate 3417.3", NULL),
(NULL, "Even historians fail to learn from history -- they repeat the same mistakes.		-- John Gill, \"Patterns of Force\", stardate 2534.7", NULL),
(NULL, "Every living thing wants to survive.		-- Spock, \"The Ultimate Computer\", stardate 4731.3", NULL),
(NULL, "	\"Evil does seek to maintain power by suppressing the truth.\"	\"Or by misleading the innocent.\"		-- Spock and McCoy, \"And The Children Shall Lead\",		   stardate 5029.5.", NULL),
(NULL, "Extreme feminine beauty is always disturbing.		-- Spock, \"The Cloud Minders\", stardate 5818.4", NULL),
(NULL, "Fascinating is a word I use for the unexpected.		-- Spock, \"The Squire of Gothos\", stardate 2124.5", NULL),
(NULL, "Fascinating, a totally parochial attitude.		-- Spock, \"Metamorphosis\", stardate 3219.8", NULL),
(NULL, "First study the enemy.  Seek weakness.		-- Romulan Commander, \"Balance of Terror\", stardate 1709.2", NULL),
(NULL, "Four thousand throats may be cut in one night by a running man.		-- Klingon Soldier, \"Day of the Dove\", stardate unknown", NULL),
(NULL, "	\"... freedom ... is a worship word...\"	\"It is our worship word too.\"		-- Cloud William and Kirk, \"The Omega Glory\", stardate unknown", NULL),
(NULL, "Genius doesn't work on an assembly line basis.  You can't simply say,\"Today I will be brilliant.\"		-- Kirk, \"The Ultimate Computer\", stardate 4731.3", NULL),
(NULL, "	\"Get back to your stations!\"	\"We're beaming down to the planet, sir.\"		-- Kirk and Mr. Leslie, \"This Side of Paradise\",		   stardate 3417.3", NULL),
(NULL, "Hailing frequencies open, Captain.", NULL),
(NULL, "He's dead, Jim.		-- McCoy, \"The Devil in the Dark\", stardate 3196.1", NULL),
(NULL, "History tends to exaggerate.		-- Col. Green, \"The Savage Curtain\", stardate 5906.4", NULL),
(NULL, "Humans do claim a great deal for that particular emotion (love).		-- Spock, \"The Lights of Zetar\", stardate 5725.6", NULL),
(NULL, "I am pleased to see that we have differences.  May we together becomegreater than the sum of both of us.		-- Surak of Vulcan, \"The Savage Curtain\", stardate 5906.4", NULL),
(NULL, "I have never understood the female capacity to avoid a direct answer toany question.		-- Spock, \"This Side of Paradise\", stardate 3417.3", NULL),
(NULL, "I object to intellect without discipline;  I object to power withoutconstructive purpose.		-- Spock, \"The Squire of Gothos\", stardate 2124.5", NULL),
(NULL, "I realize that command does have its fascination, even undercircumstances such as these, but I neither enjoy the idea of commandnor am I frightened of it.  It simply exists, and I will do whateverlogically needs to be done.		-- Spock, \"The Galileo Seven\", stardate 2812.7", NULL),
(NULL, "	\"I think they're going to take all this money that we spend now on warand death --\"	\"And make them spend it on life.\"		-- Edith Keeler and Kirk, \"The City on the Edge of Forever\",		   stardate unknown.", NULL),
(NULL, "I thought my people would grow tired of killing.  But you were right,they see it is easier than trading.  And it has its pleasures.  I feelit myself.  Like the hunt, but with richer rewards.		-- Apella, \"A Private Little War\", stardate 4211.8", NULL),
(NULL, "\"I'm a doctor, not a mechanic.\"		-- \"The Doomsday Machine\", when asked if he had heard of		   the idea of a doomsday machine.\"I'm a doctor, not an escalator.\"		-- \"Friday's Child\", when asked to help the very pregnant		   Ellen up a steep incline.\"I'm a doctor, not a bricklayer.\"		-- Devil in the Dark\", when asked to patch up the Horta.\"I'm a doctor, not an engineer.\"		-- \"Mirror, Mirror\", when asked by Scotty for help in		   Engineering aboard the ISS Enterprise.\"I'm a doctor, not a coalminer.\"		-- \"The Empath\", on being beneath the surface of Minara 2.\"I'm a surgeon, not a psychiatrist.\"		-- \"City on the Edge of Forever\", on Edith Keeler's remark		   that Kirk talked strangely.\"I'm no magician, Spock, just an old country doctor.\"		-- \"The Deadly Years\", to Spock while trying to cure the		   aging effects of the rogue comet near Gamma Hydra 4.\"What am I, a doctor or a moonshuttle conductor?\"		-- \"The Corbomite Maneuver\", when Kirk rushed off from a		   physical exam to answer the alert.", NULL),
(NULL, "I'm a soldier, not a diplomat.  I can only tell the truth.		-- Kirk, \"Errand of Mercy\", stardate 3198.9", NULL),
(NULL, "I'm frequently appalled by the low regard you Earthmen have for life.		-- Spock, \"The Galileo Seven\", stardate 2822.3", NULL),
(NULL, "I've already got a female to worry about.  Her name is the Enterprise.		-- Kirk, \"The Corbomite Maneuver\", stardate 1514.0", NULL),
(NULL, "If a man had a child who'd gone anti-social, killed perhaps, he'd stilltend to protect that child.		-- McCoy, \"The Ultimate Computer\", stardate 4731.3", NULL),
(NULL, "If I can have honesty, it's easier to overlook mistakes.		-- Kirk, \"Space Seed\", stardate 3141.9", NULL),
(NULL, "If some day we are defeated, well, war has its fortunes, good and bad.		-- Commander Kor, \"Errand of Mercy\", stardate 3201.7", NULL),
(NULL, "If there are self-made purgatories, then we all have to live in them.		-- Spock, \"This Side of Paradise\", stardate 3417.7", NULL),
(NULL, "Immortality consists largely of boredom.		-- Zefrem Cochrane, \"Metamorphosis\", stardate 3219.8", NULL),
(NULL, "In the strict scientific sense we all feed on death -- even vegetarians.		-- Spock, \"Wolf in the Fold\", stardate 3615.4", NULL),
(NULL, "Insufficient facts always invite danger.		-- Spock, \"Space Seed\", stardate 3141.9", NULL),
(NULL, "Insults are effective only where emotion is present.		-- Spock, \"Who Mourns for Adonais?\"  stardate 3468.1", NULL),
(NULL, "Intuition, however illogical, is recognized as a command prerogative.		-- Kirk, \"Obsession\", stardate 3620.7", NULL),
(NULL, "Is not that the nature of men and women -- that the pleasure is in thelearning of each other?		-- Natira, the High Priestess of Yonada, \"For the World is		   Hollow and I Have Touched the Sky\", stardate 5476.3.", NULL),
(NULL, "Is truth not truth for all?		-- Natira, \"For the World is Hollow and I have Touched		   the Sky\", stardate 5476.4.", NULL),
(NULL, "It [being a Vulcan] means to adopt a philosophy, a way of life which islogical and beneficial.  We cannot disregard that philosophy merely forpersonal gain, no matter how important that gain might be.		-- Spock, \"Journey to Babel\", stardate 3842.4", NULL),
(NULL, "It is a human characteristic to love little animals, especially ifthey're attractive in some way.		-- McCoy, \"The Trouble with Tribbles\", stardate 4525.6", NULL),
(NULL, "It is more rational to sacrifice one life than six.		-- Spock, \"The Galileo Seven\", stardate 2822.3", NULL),
(NULL, "It is necessary to have purpose.		-- Alice #1, \"I, Mudd\", stardate 4513.3", NULL),
(NULL, "It is undignified for a woman to play servant to a man who is not hers.		-- Spock, \"Amok Time\", stardate 3372.7", NULL),
(NULL, "It would be illogical to assume that all conditions remain stable.		-- Spock, \"The Enterprise Incident\", stardate 5027.3", NULL),
(NULL, "It would be illogical to kill without reason.		-- Spock, \"Journey to Babel\", stardate 3842.4", NULL),
(NULL, "It would seem that evil retreats when forcibly confronted.		-- Yarnek of Excalbia, \"The Savage Curtain\", stardate 5906.5", NULL),
(NULL, "	\"It's hard to believe that something which is neither seen nor felt cando so much harm.\"	\"That's true.  But an idea can't be seen or felt.  And that's what keptthe Troglytes in the mines all these centuries.  A mistaken idea.\"		-- Vanna and Kirk, \"The Cloud Minders\", stardate 5819.0", NULL),
(NULL, "Killing is stupid; useless!		-- McCoy, \"A Private Little War\", stardate 4211.8", NULL),
(NULL, "Killing is wrong.		-- Losira, \"That Which Survives\", stardate unknown", NULL),
(NULL, "Kirk to Enterprise -- beam down yeoman Rand and a six-pack.", NULL),
(NULL, "Klingon phaser attack from front!!!!!100% Damage to life support!!!!", NULL),
(NULL, "Knowledge, sir, should be free to all!		-- Harry Mudd, \"I, Mudd\", stardate 4513.3", NULL),
(NULL, "Landru! Guide us!		-- A Beta 3-oid, \"The Return of the Archons\", stardate 3157.4", NULL),
(NULL, "Leave bigotry in your quarters; there's no room for it on the bridge.		-- Kirk, \"Balance of Terror\", stardate 1709.2", NULL),
(NULL, "	\"Life and death are seldom logical.\"	\"But attaining a desired goal always is.\"		-- McCoy and Spock, \"The Galileo Seven\", stardate 2821.7", NULL),
(NULL, "Live long and prosper.		-- Spock, \"Amok Time\", stardate 3372.7", NULL),
(NULL, "	\"Logic and practical information do not seem to apply here.\"	\"You admit that?\"	\"To deny the facts would be illogical, Doctor\"		-- Spock and McCoy, \"A Piece of the Action\", stardate unknown", NULL),
(NULL, "Lots of people drink from the wrong bottle sometimes.		-- Edith Keeler, \"The City on the Edge of Forever\",		   stardate unknown", NULL),
(NULL, "Love sometimes expresses itself in sacrifice.		-- Kirk, \"Metamorphosis\", stardate 3220.3", NULL),
(NULL, "Madness has no purpose.  Or reason.  But it may have a goal.		-- Spock, \"The Alternative Factor\", stardate 3088.7", NULL),
(NULL, "Many Myths are based on truth		-- Spock, \"The Way to Eden\",  stardate 5832.3", NULL),
(NULL, "Men of peace usually are [brave].		-- Spock, \"The Savage Curtain\", stardate 5906.5", NULL),
(NULL, "Men will always be men -- no matter where they are.		-- Harry Mudd, \"Mudd's Women\", stardate 1329.8", NULL),
(NULL, "Military secrets are the most fleeting of all.		-- Spock, \"The Enterprise Incident\", stardate 5027.4", NULL),
(NULL, "Mind your own business, Spock.  I'm sick of your halfbreed interference.", NULL),
(NULL, "Most legends have their basis in facts.		-- Kirk, \"And The Children Shall Lead\", stardate 5029.5", NULL),
(NULL, "Murder is contrary to the laws of man and God.		-- M-5 Computer, \"The Ultimate Computer\", stardate 4731.3", NULL),
(NULL, "No more blah, blah, blah!		-- Kirk, \"Miri\", stardate 2713.6", NULL),
(NULL, "No one can guarantee the actions of another.		-- Spock, \"Day of the Dove\", stardate unknown", NULL),
(NULL, "No one may kill a man.  Not for any purpose.  It cannot be condoned.		-- Kirk, \"Spock's Brain\", stardate 5431.6", NULL),
(NULL, "	\"No one talks peace unless he's ready to back it up with war.\"	\"He talks of peace if it is the only way to live.\"		-- Colonel Green and Surak of Vulcan, \"The Savage Curtain\",		   stardate 5906.5.", NULL),
(NULL, "No one wants war.		-- Kirk, \"Errand of Mercy\", stardate 3201.7", NULL),
(NULL, "No problem is insoluble.		-- Dr. Janet Wallace, \"The Deadly Years\", stardate 3479.4", NULL),
(NULL, "Not one hundred percent efficient, of course ... but nothing ever is.		-- Kirk, \"Metamorphosis\", stardate 3219.8", NULL),
(NULL, "Oblivion together does not frighten me, beloved.		-- Thalassa (in Anne Mulhall's body), \"Return to Tomorrow\",		   stardate 4770.3.", NULL),
(NULL, "Oh, that sound of male ego.  You travel halfway across the galaxy andit's still the same song.		-- Eve McHuron, \"Mudd's Women\", stardate 1330.1", NULL),
(NULL, "On my planet, to rest is to rest -- to cease using energy.  To me, itis quite illogical to run up and down on green grass, using energy,instead of saving it.		-- Spock, \"Shore Leave\", stardate 3025.2", NULL),
(NULL, "One does not thank logic.		-- Sarek, \"Journey to Babel\", stardate 3842.4", NULL),
(NULL, "One of the advantages of being a captain is being able to ask foradvice without necessarily having to take it.		-- Kirk, \"Dagger of the Mind\", stardate 2715.2", NULL),
(NULL, "Only a fool fights in a burning house.		-- Kank the Klingon, \"Day of the Dove\", stardate unknown", NULL),
(NULL, "Our missions are peaceful -- not for conquest.  When we do battle, itis only because we have no choice.		-- Kirk, \"The Squire of Gothos\", stardate 2124.5", NULL),
(NULL, "Our way is peace.		-- Septimus, the Son Worshiper, \"Bread and Circuses\",		   stardate 4040.7.", NULL),
(NULL, "Pain is a thing of the mind.  The mind can be controlled.		-- Spock, \"Operation -- Annihilate!\" stardate 3287.2", NULL),
(NULL, "Peace was the way.		-- Kirk, \"The City on the Edge of Forever\", stardate unknown", NULL),
(NULL, "Phasers locked on target, Captain.", NULL),
(NULL, "Power is danger.		-- The Centurion, \"Balance of Terror\", stardate 1709.2", NULL),
(NULL, "Prepare for tomorrow -- get ready.		-- Edith Keeler, \"The City On the Edge of Forever\",		   stardate unknown", NULL),
(NULL, "Punishment becomes ineffective after a certain point.  Men become insensitive.		-- Eneg, \"Patterns of Force\", stardate 2534.7", NULL),
(NULL, "Respect is a rational process		-- McCoy, \"The Galileo Seven\", stardate 2822.3", NULL),
(NULL, "Romulan women are not like Vulcan females.  We are not dedicated topure logic and the sterility of non-emotion.		-- Romulan Commander, \"The Enterprise Incident\",		   stardate 5027.3", NULL),
(NULL, "Schshschshchsch.		-- The Gorn, \"Arena\", stardate 3046.2", NULL),
(NULL, "She won' go Warp 7, Cap'n!  The batteries are dead!", NULL),
(NULL, "Sometimes a feeling is all we humans have to go on.		-- Kirk, \"A Taste of Armageddon\", stardate 3193.9", NULL),
(NULL, "Sometimes a man will tell his bartender things he'll never tell his doctor.		-- Dr. Phillip Boyce, \"The Menagerie\" (\"The Cage\"),		   stardate unknown.", NULL),
(NULL, "Space: the final frontier.  These are the voyages of the starship Enterprise.Its five-year mission: to explore strange new worlds; to seek out new lifeand new civilizations; to boldly go where no man has gone before.		-- Captain James T. Kirk", NULL),
(NULL, "Spock: The odds of surviving another attack are 13562190123 to 1, Captain.", NULL),
(NULL, "Spock: We suffered 23 casualties in that attack, Captain.", NULL),
(NULL, "Star Trek Lives!", NULL),
(NULL, "Suffocating together ... would create heroic camaraderie.		-- Khan Noonian Singh, \"Space Seed\", stardate 3142.8", NULL),
(NULL, "Superior ability breeds superior ambition.		-- Spock, \"Space Seed\", stardate 3141.9", NULL),
(NULL, "	\"That unit is a woman.\"	\"A mass of conflicting impulses.\"		-- Spock and Nomad, \"The Changeling\", stardate 3541.9", NULL),
(NULL, "The best diplomat I know is a fully activated phaser bank.		-- Scotty", NULL),
(NULL, "	\"The combination of a number of things to make existence worthwhile.\"	\"Yes, the philosophy of 'none,' meaning 'all.'\"		-- Spock and Lincoln, \"The Savage Curtain\", stardate 5906.4", NULL),
(NULL, "The face of war has never changed.  Surely it is more logical to healthan to kill.		-- Surak of Vulcan, \"The Savage Curtain\", stardate 5906.5", NULL),
(NULL, "The games have always strengthened us.  Death becomes a familiarpattern.  We don't fear it as you do.		-- Proconsul Marcus Claudius, \"Bread and Circuses\",		   stardate 4041.2", NULL),
(NULL, "	\"The glory of creation is in its infinite diversity.\"	\"And in the way our differences combine to create meaning and beauty.\"		-- Dr. Miranda Jones and Spock, \"Is There in Truth No Beauty?\",		   stardate 5630.8", NULL),
(NULL, "The heart is not a logical organ.		-- Dr. Janet Wallace, \"The Deadly Years\", stardate 3479.4", NULL),
(NULL, "The idea of male and female are universal constants.		-- Kirk, \"Metamorphosis\", stardate 3219.8", NULL),
(NULL, "The joys of love made her human and the agonies of love destroyed her.		-- Spock, \"Requiem for Methuselah\", stardate 5842.8", NULL),
(NULL, "The man on tops walks a lonely street; the \"chain\" of command is often a noose.", NULL),
(NULL, "The more complex the mind, the greater the need for the simplicity of play.		-- Kirk, \"Shore Leave\", stardate 3025.8", NULL),
(NULL, "The only solution is ... a balance of power.  We arm our side with exactlythat much more.  A balance of power -- the trickiest, most difficult,dirtiest game of them all.  But the only one that preserves both sides.		-- Kirk, \"A Private Little War\", stardate 4211.8", NULL),
(NULL, "The people of Gideon have always believed that life is sacred.  Thatthe love of life is the greatest gift ... We are incapable ofdestroying or interfering with the creation of that which we love sodeeply -- life in every form from fetus to developed being.		-- Hodin of Gideon, \"The Mark of Gideon\", stardate 5423.4", NULL),
(NULL, "... The prejudices people feel about each other disappear when they getto know each other.		-- Kirk, \"Elaan of Troyius\", stardate 4372.5", NULL),
(NULL, "	\"The release of emotion is what keeps us health.  Emotionally healthy.\"	\"That may be, Doctor.  However, I have noted that the healthy releaseof emotion is frequently unhealthy for those closest to you.\"		-- McCoy and Spock, \"Plato's Stepchildren\", stardate 5784.3", NULL),
(NULL, "The sight of death frightens them [Earthers].		-- Kras the Klingon, \"Friday's Child\", stardate 3497.2", NULL),
(NULL, "The sooner our happiness together begins, the longer it will last.		-- Miramanee, \"The Paradise Syndrome\", stardate 4842.6", NULL),
(NULL, "... The things love can drive a man to -- the ecstasies, thethe miseries, the broken rules, the desperate chances, the gloriousfailures and the glorious victories.		-- McCoy, \"Requiem for Methuselah\", stardate 5843.7", NULL),
(NULL, "There are always alternatives.		-- Spock, \"The Galileo Seven\", stardate 2822.3", NULL),
(NULL, "There are certain things men must do to remain men.		-- Kirk, \"The Ultimate Computer\", stardate 4929.4", NULL),
(NULL, "There are some things worth dying for.		-- Kirk, \"Errand of Mercy\", stardate 3201.7", NULL),
(NULL, "There comes to all races an ultimate crisis which you have yet to face.... One day our minds became so powerful we dared think of ourselves as gods.		-- Sargon, \"Return to Tomorrow\", stardate 4768.3", NULL),
(NULL, "There is a multi-legged creature crawling on your shoulder.		-- Spock, \"A Taste of Armageddon\", stardate 3193.9", NULL),
(NULL, "There is an old custom among my people.  When a woman saves a man'slife, he is grateful.		-- Nona, the Kanuto witch woman, \"A Private Little War\",		   stardate 4211.8.", NULL),
(NULL, "There is an order of things in this universe.		-- Apollo, \"Who Mourns for Adonais?\" stardate 3468.1", NULL),
(NULL, "There's a way out of any cage.		-- Captain Christopher Pike, \"The Menagerie\" (\"The Cage\"),		   stardate unknown.", NULL),
(NULL, "There's another way to survive.  Mutual trust -- and help.		-- Kirk, \"Day of the Dove\", stardate unknown", NULL),
(NULL, "There's no honorable way to kill, no gentle way to destroy.  There isnothing good in war.  Except its ending.		-- Abraham Lincoln, \"The Savage Curtain\", stardate 5906.5", NULL),
(NULL, "There's nothing disgusting about it [the Companion].  It's just anotherlife form, that's all.  You get used to those things.		-- McCoy, \"Metamorphosis\", stardate 3219.8", NULL),
(NULL, "	\"There's only one kind of woman ...\"	\"Or man, for that matter.  You either believe in yourself or you don't.\"		-- Kirk and Harry Mudd, \"Mudd's Women\", stardate 1330.1", NULL),
(NULL, "This cultural mystique surrounding the biological function -- yourealize humans are overly preoccupied with the subject.		-- Kelinda the Kelvan, \"By Any Other Name\", stardate 4658.9", NULL),
(NULL, "Those who hate and fight must stop themselves -- otherwise it is not stopped.		-- Spock, \"Day of the Dove\", stardate unknown", NULL),
(NULL, "Time is fluid ... like a river with currents, eddies, backwash.		-- Spock, \"The City on the Edge of Forever\", stardate 3134.0", NULL),
(NULL, "To live is always desirable.		-- Eleen the Capellan, \"Friday's Child\", stardate 3498.9", NULL),
(NULL, "Too much of anything, even love, isn't necessarily a good thing.		-- Kirk, \"The Trouble with Tribbles\", stardate 4525.6", NULL),
(NULL, "Totally illogical, there was no chance.		-- Spock, \"The Galileo Seven\", stardate 2822.3", NULL),
(NULL, "Uncontrolled power will turn even saints into savages.  And we can allbe counted on to live down to our lowest impulses.		-- Parmen, \"Plato's Stepchildren\", stardate 5784.3", NULL),
(NULL, "Violence in reality is quite different from theory.		-- Spock, \"The Cloud Minders\", stardate 5818.4", NULL),
(NULL, "Virtue is a relative term.		-- Spock, \"Friday's Child\", stardate 3499.1", NULL),
(NULL, "Vulcans believe peace should not depend on force.		-- Amanda, \"Journey to Babel\", stardate 3842.3", NULL),
(NULL, "Vulcans do not approve of violence.		-- Spock, \"Journey to Babel\", stardate 3842.4", NULL),
(NULL, "Vulcans never bluff.		-- Spock, \"The Doomsday Machine\", stardate 4202.1", NULL),
(NULL, "Vulcans worship peace above all.		-- McCoy, \"Return to Tomorrow\", stardate 4768.3", NULL),
(NULL, "Wait!  You have not been prepared!		-- Mr. Atoz, \"Tomorrow is Yesterday\", stardate 3113.2", NULL),
(NULL, "War is never imperative.		-- McCoy, \"Balance of Terror\", stardate 1709.2", NULL),
(NULL, "War isn't a good life, but it's life.		-- Kirk, \"A Private Little War\", stardate 4211.8", NULL),
(NULL, "[War] is instinctive.  But the instinct can be fought.  We're humanbeings with the blood of a million savage years on our hands!  But wecan stop it.  We can admit that we're killers ... but we're not goingto kill today.  That's all it takes!  Knowing that we're not going tokill today!		-- Kirk, \"A Taste of Armageddon\", stardate 3193.0", NULL),
(NULL, "Warp 7 -- It's a law we can live with.", NULL),
(NULL, "We do not colonize.  We conquer.  We rule.  There is no other way for us.		-- Rojan, \"By Any Other Name\", stardate 4657.5", NULL),
(NULL, "We fight only when there is no other choice.  We prefer the ways ofpeaceful contact.		-- Kirk, \"Spectre of the Gun\", stardate 4385.3", NULL),
(NULL, "We have found all life forms in the galaxy are capable of superiordevelopment.		-- Kirk, \"The Gamesters of Triskelion\", stardate 3211.7", NULL),
(NULL, "We have phasers, I vote we blast 'em!		-- Bailey, \"The Corbomite Maneuver\", stardate 1514.2", NULL),
(NULL, "	\"We have the right to survive!\"	\"Not by killing others.\"		-- Deela and Kirk, \"Wink of An Eye\", stardate 5710.5", NULL),
(NULL, "We Klingons believe as you do -- the sick should die.  Only the strongshould live.		-- Kras, \"Friday's Child\", stardate 3497.2", NULL),
(NULL, "We'll pivot at warp 2 and bring all tubes to bear, Mr. Sulu!", NULL),
(NULL, "We're all sorry for the other guy when he loses his job to a machine.But when it comes to your job -- that's different.  And it always willbe different.		-- McCoy, \"The Ultimate Computer\", stardate 4729.4", NULL),
(NULL, "Well, Jim, I'm not much of an actor either.", NULL),
(NULL, "	\"What happened to the crewman?\"	\"The M-5 computer needed a new power source, the crewman merely got inthe way.\"		-- Kirk and Dr. Richard Daystrom, \"The Ultimate Computer\",		   stardate 4731.3.", NULL),
(NULL, "What kind of love is that?  Not to be loved; never to have shown love.		-- Commissioner Nancy Hedford, \"Metamorphosis\",		   stardate 3219.8", NULL),
(NULL, "	\"What terrible way to die.\"	\"There are no good ways.\"		-- Sulu and Kirk, \"That Which Survives\", stardate unknown", NULL),
(NULL, "When a child is taught ... its programmed with simple instructions --and at some point, if its mind develops properly, it exceeds the sum ofwhat it was taught, thinks independently.		-- Dr. Richard Daystrom, \"The Ultimate Computer\",		   stardate 4731.3.", NULL),
(NULL, "When dreams become more important than reality, you give up travel,building, creating; you even forget how to repair the machines leftbehind by your ancestors.  You just sit living and reliving other livesleft behind in the thought records.		-- Vina, \"The Menagerie\" (\"The Cage\"), stardate unknown", NULL),
(NULL, "Where there's no emotion, there's no motive for violence.		-- Spock, \"Dagger of the Mind\", stardate 2715.1", NULL),
(NULL, "Witch!  Witch!  They'll burn ya!		-- Hag, \"Tomorrow is Yesterday\", stardate unknown", NULL),
(NULL, "Without facts, the decision cannot be made logically.  You must rely onyour human intuition.		-- Spock, \"Assignment: Earth\", stardate unknown", NULL),
(NULL, "Without followers, evil cannot spread.		-- Spock, \"And The Children Shall Lead\", stardate 5029.5", NULL),
(NULL, "Without freedom of choice there is no creativity.		-- Kirk, \"The return of the Archons\", stardate 3157.4", NULL),
(NULL, "Women are more easily and more deeply terrified ... generating moresheer horror than the male of the species.		-- Spock, \"Wolf in the Fold\", stardate 3615.4", NULL),
(NULL, "Women professionals do tend to over-compensate.		-- Dr. Elizabeth Dehaver, \"Where No Man Has Gone Before\",		   stardate 1312.9.", NULL),
(NULL, "Worlds are conquered, galaxies destroyed -- but a woman is always a woman.		-- Kirk, \"The Conscience of the King\", stardate 2818.9", NULL),
(NULL, "Yes, it is written.  Good shall always destroy evil.		-- Sirah the Yang, \"The Omega Glory\", stardate unknown", NULL),
(NULL, "You are an excellent tactician, Captain.  You let your second incommand attack while you sit and watch for weakness.		-- Khan Noonian Singh, \"Space Seed\", stardate 3141.9", NULL),
(NULL, "You can't evaluate a man by logic alone.		-- McCoy, \"I, Mudd\", stardate 4513.3", NULL),
(NULL, "You canna change the laws of physics, Captain; I've got to have thirty minutes!", NULL),
(NULL, "You Earth people glorified organized violence for forty centuries.  Butyou imprison those who employ it privately.		-- Spock, \"Dagger of the Mind\", stardate 2715.1", NULL),
(NULL, "You go slow, be gentle.  It's no one-way street -- you know how youfeel and that's all.  It's how the girl feels too.  Don't press.  Ifthe girl feels anything for you at all, you'll know.		-- Kirk, \"Charlie X\", stardate 1535.8", NULL),
(NULL, "You humans have that emotional need to express gratitude.  \"You'rewelcome,\" I believe, is the correct response.		-- Spock, \"Bread and Circuses\", stardate 4041.2", NULL),
(NULL, "You say you are lying.  But if everything you say is a lie, then you aretelling the truth.  You cannot tell the truth because everything you sayis a lie.  You lie, you tell the truth ... but you cannot, for you lie.		-- Norman the android, \"I, Mudd\", stardate 4513.3", NULL),
(NULL, "You speak of courage.  Obviously you do not know the difference betweencourage and foolhardiness.  Always it is the brave ones who die, the soldiers.		-- Kor, the Klingon Commander, \"Errand of Mercy\",		   stardate 3201.7", NULL),
(NULL, "You!  What PLANET is this!		-- McCoy, \"The City on the Edge of Forever\", stardate 3134.0", NULL),
(NULL, "You'll learn something about men and women -- the way they're supposedto be.  Caring for each other, being happy with each other, being goodto each other.  That's what we call love.  You'll like that a lot.		-- Kirk, \"The Apple\", stardate 3715.6", NULL),
(NULL, "You're dead, Jim.		-- McCoy, \"Amok Time\", stardate 3372.7", NULL),
(NULL, "You're dead, Jim.		-- McCoy, \"The Tholian Web\", stardate unknown", NULL),
(NULL, "You're too beautiful to ignore.  Too much woman.		-- Kirk to Yeoman Rand, \"The Enemy Within\", stardate unknown", NULL),
(NULL, "Youth doesn't excuse everything.		-- Dr. Janice Lester (in Kirk's body), \"Turnabout Intruder\",		   stardate 5928.5.", NULL),
(NULL, "There's coffee in that nebula!		-- Capt. Kathryn Janeway, Star Trek: Voyager, \"The Cloud\"", NULL),
(NULL, "Dismissed.  That's a Star Fleet expression for, \"Get out.\"		-- Capt. Kathryn Janeway, Star Trek: Voyager, \"The Cloud\"", NULL),
(NULL, "", NULL)
