DROP TABLE IF EXISTS `bot_quotes_starwars`;
CREATE TABLE `bot_quotes_starwars` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `quote` text NOT NULL,
  `props` int(10) NOT NULL default 0,
  PRIMARY KEY  (`id`)
);

INSERT INTO `bot_quotes_starwars` VALUES
(NULL, "Beware, Viceroy. The Federation has gone too far this time. --- Queen Padme Amidala", NULL),
(NULL, "I will not condone a course of action that will lead us to war. --- Queen Padme Amidala", NULL),
(NULL, "I was not elected to watch my people suffer and die while you discuss this invasion in a committee! --- Queen Padme Amidala", NULL),
(NULL, "I will sign no treaty, Senator. My fate will be no different from that of my people. --- Queen Padme Amidala", NULL),
(NULL, "I ask you to help us…No, I beg you to help us. We are your humble servants. Our fate is in your hands. --- Queen Padme Amidala", NULL),
(NULL, "Mesa called Jar Jar Binks, mesa your humble servant! --- Jar Jar Binks", NULL),
(NULL, "Ex-squeeze me, but the mostest safest place would be Gunga City, 'tis where I grew up, 'tis a hidden city. --- Jar Jar Binks", NULL),
(NULL, "Yousa should follow me now, okeeday? My warning yous. Gungans no like outsiders. Don't spect a warm welcome. --- Jar Jar Binks", NULL),
(NULL, "Count me outta dis one. Better dead here than dead in the Core. Ye gods, whatta me sayin'?! --- Jar Jar Binks", NULL),
(NULL, "Gungans no dyin withouta fight. Wesa warriors. Wesa got a grand army. That's why you no liken us mesa thinks. --- Jar Jar Binks", NULL),
(NULL, "Don't center on your anxieties, Obi-Wan. Keep your concentration here and now, where it belongs. --- Qui-Gon Jinn", NULL),
(NULL, "The ability to speak does not make you intelligent, now get out of here. --- Qui-Gon Jinn", NULL),
(NULL, "Remember, concentrate on the moment. Feel, don't think. Use your instincts. --- Qui-Gon Jinn", NULL),
(NULL, "He is the Chosen One, you must see it. --- Qui-Gon Jinn", NULL),
(NULL, "Remember: Your focus determines your reality. --- Qui-Gon Jinn", NULL),
(NULL, "Obi-Wan, promise me you will train the boy. He…is the Chosen One…he will bring balance. Train him. --- Qui-Gon Jinn", NULL),
(NULL, "There's always a bigger fish. --- Qui-Gon Jinn", NULL),
(NULL, "I have a bad feeling about this. --- Obi-Wan Kenobi", NULL),
(NULL, "If they find us, they will crush us, grind us into tiny pieces, and blast us into oblivion! --- Obi-Wan Kenobi", NULL),
(NULL, "You and the Naboo form a symbiont circle. What happens to one of you will affect the other. You must understand this. --- Obi-Wan Kenobi", NULL),
(NULL, "Why do I sense we've picked up another pathetic life form? --- Obi-Wan Kenobi", NULL),
(NULL, "Do not defy the council, Master, not again. --- Obi-Wan Kenobi", NULL),
(NULL, "The boy is dangerous. They all sense it; why can't you? --- Obi-Wan Kenobi", NULL),
(NULL, "At last, we will reveal ourselves to the Jedi. At last, we will have our revenge. --- Darth Maul", NULL),
(NULL, "Tatooine is sparcely populated. If the trace was correct, I will find them quickly master. --- Darth Maul", NULL),
(NULL, "You have been well trained, my young apprentice. They will be no match for you. --- Darth Sidious", NULL),
(NULL, "Wipe them out. All of them. --- Darth Sidious", NULL),
(NULL, "Now they will elect a new Chancellor. A strong Chancellor. One who will not let our tragedy continue. --- Palpatine", NULL),
(NULL, "We are indebted to you for your bravery, Obi-Wan Kenobi. And you, young Skywalker; we will watch your career with great interest. --- Palpatine", NULL),
(NULL, "I'm a person, and my name is Anakin! --- Anakin Skywalker", NULL),
(NULL, "No one can kill a Jedi. --- Anakin Skywalker", NULL),
(NULL, "Mom, you said that the biggest problem in the universe is no one helps each other. --- Anakin Skywalker", NULL),
(NULL, "Now this is podracing! --- Anakin Skywalker", NULL),
(NULL, "There was no father. I carried him, I gave birth, I raised him. I can't explained what happened. --- Shmi Skywalker", NULL),
(NULL, "You can't stop the change any more than you can stop the suns from setting. --- Shmi Skywalker", NULL),
(NULL, "Now be brave and don't look back. Don't look back. --- Shmi Skywalker", NULL),
(NULL, "You refer to the prophecy of the one who will bring balance to the Force. You believe it's this boy? --- Mace Windu", NULL),
(NULL, "Fear is the path to the dark side. Fear leads to anger; anger leads to hate; hate leads to suffering. I sense much fear in you. --- Master Yoda", NULL),
(NULL, "Clouded this boy's future is. --- Master Yoda", NULL),
(NULL, "Qui-Gon's defiance, I sense in you. Need that, you do not. Agree with you, the council does. Your apprentice, Skywalker will be. --- Master Yoda", NULL),
(NULL, "For a mechanic, you seem to do an excessive amount of thinking. --- C-3PO", NULL),
(NULL, "Oh! Have you no sense at all? Idiot! --- C-3PO", NULL),
(NULL, "Oh! No. --- C-3PO", NULL),
(NULL, "You must join me, Obi-Wan, and together, we will destroy the Sith! --- Count Dooku", NULL),
(NULL, "Master Windu, you have fought gallantly. Worthy of recognition in the archives of the Jedi Order. Now... it is finished. --- Count Dooku", NULL),
(NULL, "It is obvious that this contest cannot be decided by our knowledge of the Force... but by our skills with a lightsaber. --- Count Dooku", NULL),
(NULL, "Why do I get the feeling you're going to be the death of me? --- Obi-Wan Kenobi", NULL),
(NULL, "Be mindful of your thoughts, Anakin, they betray you. You have made a commitment to the Jedi Order, a commitment not easily broken. --- Obi-Wan Kenobi", NULL),
(NULL, "Patience, use the Force, think! --- Obi-Wan Kenobi", NULL),
(NULL, "I don't mind flying, but what you're doing is suicide! --- Obi-Wan Kenobi", NULL),
(NULL, "It is with great reluctance that I have agreed to this calling. I love democracy... I love the Republic. The power you give me I will lay down when this crisis has abated. And as my first act with this new authority, I will create a Grand Army of the Republic to counter the increasing threats of the Separatists. --- Chancellor Palpatine", NULL),
(NULL, "Just being around her again is intoxicating. --- Anakin Skywalker", NULL),
(NULL, "Jedi business, go back to your drinks. --- Anakin Skywalker", NULL),
(NULL, "Don't say that master, you're the closest thing I have to a father. --- Anakin Skywalker", NULL),
(NULL, "Attachment is forbidden. Possession is forbidden. Compassion, which I would define as…unconditional love…is essential to a Jedi's life. So, you might say that we are encouraged to love. --- Anakin Skywalker", NULL),
(NULL, "I don't like sand. It's coarse, rough, irritating and it gets everywhere. Not like here. Here everything is soft…and smooth. --- Anakin Skywalker", NULL),
(NULL, "I'm haunted by the kiss you should never have given me. --- Anakin Skywalker", NULL),
(NULL, "I killed them. I killed them all. They're dead. Every single one of them. And not just the men, but the women, and the children, too! They're like animals, and I slaughtered them like animals! I hate them! --- Anakin Skywalker", NULL),
(NULL, "From the moment I met you, all those years ago, not a day has gone by when I haven't thought of you. And now that I'm with you again…I'm in agony. The closer I get to you, the worse it gets. The thought of not being with you—I can't breathe. I'm haunted by the kiss that you should never have given me. My heart is beating…hoping that kiss will not become a scar. You are in my very soul, tormenting me…what can I do? I will do anything you ask. [pause] If you are suffering as much as I am, please, tell me. --- Anakin Skywalker", NULL),
(NULL, "If they do, you must realize there aren't enough Jedi to protect the Republic. We're keepers of the peace, not soldiers. --- Mace Windu", NULL),
(NULL, "We will not be hostages to be bartered with, Dooku. --- Mace Windu", NULL),
(NULL, "Nevertheless, I think we should keep a closer eye on the Senate. --- Mace Windu", NULL),
(NULL, "This party's over. --- Mace Windu", NULL),
(NULL, "Lost a planet Master Obi-Wan has. How embarrassing... how embarrassing. --- Master Yoda", NULL),
(NULL, "Truly wonderful the mind of a child is. --- Master Yoda", NULL),
(NULL, "Powerful you have become, Dooku. The Dark Side I sense in you. --- Master Yoda", NULL),
(NULL, "The dark side clouds everything. Impossible to see the future is. --- Master Yoda", NULL),
(NULL, "Victory? Victory you say? Master Obi-Wan, not victory. The shroud of the Dark Side has fallen. Begun the Clone War has. --- Master Yoda", NULL),
(NULL, "I'm just a simple man, trying to make my way in the universe. --- Jango Fett", NULL),
(NULL, "Always a pleasure to meet a Jedi. --- Jango Fett", NULL),
(NULL, "So this is how liberty dies. With thunderous applause. --- Padmé Amidala", NULL),
(NULL, "Come away with me. Help me raise our child. Leave everything behind while you still can! --- Padmé Amidala", NULL),
(NULL, "I don't know you anymore! Anakin, you're breaking my heart! You're going down a path I can't follow. --- Padmé Amidala", NULL),
(NULL, "Obi-Wan, there is still good in him... there is... still... --- Padmé Amidala", NULL),
(NULL, "I think I'm finally getting the hang of this flying business. --- C-3PO", NULL),
(NULL, "Master Kenobi! We have Miss Padmé on board. Please, please hurry. We should leave this dreadful place. --- C-3PO", NULL),
(NULL, "I sense great fear in you, Skywalker. You have hate… you have anger… but you don't use them. --- Count Dooku", NULL),
(NULL, "Your swords please. We wouldn't want to make a mess of things in front of the Chancellor. --- Count Dooku", NULL),
(NULL, "Twice the pride, double the fall. --- Count Dooku", NULL),
(NULL, "Crush them! Make them suffer! --- General Grievous", NULL),
(NULL, "General Kenobi, [laughs] You ARE a bold one. [laughs] Kill him! --- General Grievous", NULL),
(NULL, "Back away! I will deal with this Jedi slime myself! --- General Grievous", NULL),
(NULL, "You fool! I have been trained in your Jedi arts by Count Dooku. --- General Grievous", NULL),
(NULL, "You lose, General Kenobi! [Said after confronted by Anakin and Obi-Wan] --- General Grievous", NULL),
(NULL, "Anakin Skywalker, I was expecting somone with you reputation to be a little...older. --- General Grievous", NULL),
(NULL, "Oh, I see it, this is going to be easy. --- Obi-Wan Kenobi", NULL),
(NULL, "I have a bad feeling about this. --- Obi-Wan Kenobi", NULL),
(NULL, "Wait a minute, how did this happen? We're smarter than this! --- Obi-Wan Kenobi", NULL),
(NULL, "Not to worry, we're still flying half a ship. --- Obi-Wan Kenobi", NULL),
(NULL, "Anakin, let's be fair. Today, you are the hero, and you deserve your glorious day with the politicians. --- Obi-Wan Kenobi", NULL),
(NULL, "Another happy landing. --- Obi-Wan Kenobi", NULL),
(NULL, "Anakin is the father, isn't he? I'm so sorry. --- Obi-Wan Kenobi", NULL),
(NULL, "You have allowed this dark lord to twist your mind, until now…until now you have become the very thing you swore to destroy. --- Obi-Wan Kenobi", NULL),
(NULL, "Then, you are lost!! --- Obi-Wan Kenobi", NULL),
(NULL, "You were the Chosen One! It was said that you would destroy the Sith, not join them! Bring balance to the force, not leave it in darkness! --- Obi-Wan Kenobi", NULL),
(NULL, "You were my brother, Anakin. I loved you! --- Obi-Wan Kenobi", NULL),
(NULL, "Hello there! --- Obi-Wan Kenobi", NULL),
(NULL, "Don't kill me. Plea'. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "No! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "No! No! you will die! [shocks Mace Windu with Force lightning] He's a traitor! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Power! Unlimited... POWER! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "I need your help son... I am counting on you to be the eyes, ears and voice of the Republic. Anakin, I am appointing you to be my personal representative on the Jedi Council. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "All who gain power are afraid to lose it, even the Jedi. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Only through me can you achieve a power greater than any Jedi. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Know the power of the Dark Side, Anakin... power to save Padmé. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Every single Jedi, including your friend, Obi-Wan Kenobi, is now an enemy of the Republic… Do what must be done, Lord Vader. Do not hesitate, show no mercy. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Your arrogance blinds you, Master Yoda. Now you will experience the full power of the dark side [shocks Yoda with force lightning] --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "You will not stop me! Darth Vader will become more powerful than either of us. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "To ensure the security and continuing stability, the Republic will be reorganized into the first Galactic Empire! For a safe and secure... society! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Once more the Sith will rule the galaxy... and we shall have peace. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "The remaining Jedi will be hunted down and defeated! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "I can feel your anger... it gives you focus, it makes you stronger! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "The attempt on my life has left me scarred and deformed, but I assure you…my resolve has never been stronger! --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "I have waited a long time for this moment, my little green friend. At last, the Jedi are no more. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "The dark side of the force is a pathway to many abilities some consider to be... unnatural. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Commander Cody, the time has come. Execute Order 66. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Because the Counsel did not trust you, my young apprentice, I believe you are the only Jedi with no knowledge of this plot. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "What? Surely we're smarter than this. (Upon being blocked by ray shields on Grievious' Ship) --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "Rise Lord Vader. --- Chancellor Palpatine / Darth Sidious", NULL),
(NULL, "He was an unarmed prisoner... I shouldn't have done that; it is not the Jedi way. --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "Something's happening. I'm not the Jedi I should be. I want more and I know I shouldn't. --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "Love won't save you, Padmé, only my new powers can do that! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "I don't want to hear anymore about Obi-Wan. The Jedi turned against me! Don't you turn against me! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "I pledge myself to your teachings. --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "Obi-Wan and the council don't trust me. --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "I will do... whatever you ask... just help me save Padme's life. I can't live without her! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "Liar! You're with him! You brought him here to kill me! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "You turned her against me! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "You will not take her from me! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "Don't lecture me, Obi-Wan, I see through the lies of the Jedi. I do not fear the dark side as you do. --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "I have brought peace, freedom, justice and securty to my new empire! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "You underestimate my power! --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "This is the end for you, my master. --- Anakin Skywalker / Darth Vader", NULL),
(NULL, "Death is a natural part of life. Rejoice for those around you who transform into the Force. Mourn them, do not. Miss them, do not. Attachment leads to jealousy. The shadow of greed that is. --- Master Yoda", NULL),
(NULL, "If into the security recordings you go, only pain will you find. --- Master Yoda", NULL),
(NULL, "The fear of loss is a path to the Dark Side. --- Master Yoda", NULL),
(NULL, "Train yourself to let go of everything you fear to lose. --- Master Yoda", NULL),
(NULL, "Destroy the Sith, we must. --- Master Yoda", NULL),
(NULL, "If so powerful you are, why leave? --- Master Yoda", NULL),
(NULL, "At an end your rule is, and not short enough it was. --- Master Yoda", NULL),
(NULL, "Into exile I must go; failed I have. --- Master Yoda", NULL),
(NULL, "Twisted by the dark side Skywalker has become. The boy you trained, gone he is, consumed by Darth Vader. --- Master Yoda", NULL),
(NULL, "I sense a great deal of confusion in you, young Skywalker. There's much fear that clouds your judgment. --- Mace Windu", NULL),
(NULL, "I sense a plot to destroy the Jedi. The dark side of the Force surrounds the Chancellor. --- Mace Windu", NULL),
(NULL, "The oppression of the Sith will never return! You have lost! --- Mace Windu", NULL),
(NULL, "Help me, Obi-Wan Kenobi; you're my only hope. --- Princess Leia", NULL),
(NULL, "Will someone get this walking carpet out of my way? --- Princess Leia", NULL),
(NULL, "Aren't you a little short for a stormtrooper? --- Princess Leia", NULL),
(NULL, "If they traced the robots here they may have learned who they sold them to and that would lead them back... home! --- Luke Skywalker", NULL),
(NULL, "I want to come with you to Alderaan. There's nothing for me here now. I want to learn the ways of the Force and become a Jedi like my father. --- Luke Skywalker", NULL),
(NULL, "Ten thousand!? We can almost buy our own ship for that! --- Luke Skywalker", NULL),
(NULL, "I have a very bad feeling about this. --- Luke Skywalker", NULL),
(NULL, "They're going to execute her. Look, a few minutes ago you said you didn't want to just wait here to be captured. Now all you want to do is stay? --- Luke Skywalker", NULL),
(NULL, "Shut down all the garbage compactors on the detention level! --- Luke Skywalker", NULL),
(NULL, "I'm Luke Skywalker, I'm here to rescue you! --- Luke Skywalker", NULL),
(NULL, "Red 5 standing by. --- Luke Skywalker", NULL),
(NULL, "Don't you call me a mindless philosopher, you overweight glob of grease! Now come on before somebody sees you. --- C-3PO", NULL),
(NULL, "[to R2-D2] We are made to suffer, it's our lot in life. --- C-3PO", NULL),
(NULL, "Go that way! You'll be malfunctioning within a day, you nearsighted scrap pile. And don't let me catch you following me, begging for help because you won't get it! --- C-3PO", NULL),
(NULL, "Listen to them! They're dying R2. Curse my metal body. I wasn't fast enough. It's all my fault. My poor master. --- C-3PO", NULL),
(NULL, "[to R2-D2] Hang on tight, R2. You've got to come back. You wouldn't want my life to be boring, would you? --- C-3PO", NULL),
(NULL, "The Sand People are easily startled, but they'll soon be back, and in greater numbers. --- Obi-Wan Kenobi", NULL),
(NULL, "Mos Eisley spaceport. You will never find a more wretched hive of scum and villainy. We must be cautious. --- Obi-Wan Kenobi", NULL),
(NULL, "The Force can have a strong influence on the weak-minded. --- Obi-Wan Kenobi", NULL),
(NULL, "I feel a great disturbance in the Force. As if millions of voices suddenly cried out in terror, and were suddenly silenced. --- Obi-Wan Kenobi", NULL),
(NULL, "Your eyes can deceive you; don't trust them. --- Obi-Wan Kenobi", NULL),
(NULL, "In my experience there's no such thing as luck. --- Obi-Wan Kenobi", NULL),
(NULL, "That's no moon... it's a space station. --- Obi-Wan Kenobi", NULL),
(NULL, "Who is more foolish? The fool, or the fool who follows him? --- Obi-Wan Kenobi", NULL),
(NULL, "Your destiny lies along a different path from mine. --- Obi-Wan Kenobi", NULL),
(NULL, "You can't win, Darth. If you strike me down, I shall become more powerful than you could possibly imagine. --- Obi-Wan Kenobi", NULL),
(NULL, "Run, Luke! Run! --- Obi-Wan Kenobi", NULL),
(NULL, "Use the Force, Luke. Let go, Luke. Luke, trust me. --- Obi-Wan Kenobi", NULL),
(NULL, "Remember, the Force will be with you, always. --- Obi-Wan Kenobi", NULL),
(NULL, "Sorry about the mess. --- Han Solo", NULL),
(NULL, "Watch your mouth kid or you'll find yourself floating home! --- Han Solo", NULL),
(NULL, "Hokey religions and ancient weapons are no match for a good blaster at your side, kid. --- Han Solo", NULL),
(NULL, "Look, good against remotes is one thing. Good against the living? That's something else. --- Han Solo", NULL),
(NULL, "Bring 'em on, I prefer a straight fight to all this sneakin' around! --- Han Solo", NULL),
(NULL, "What an incredible smell you've discovered! --- Han Solo", NULL),
(NULL, "I've got a bad feeling about this. --- Han Solo", NULL),
(NULL, "One thing's for sure, we're all gonna be a lot thinner. --- Han Solo", NULL),
(NULL, "No reward is worth this! --- Han Solo", NULL),
(NULL, "Great, kid! Don't get cocky! --- Han Solo", NULL),
(NULL, "You know, sometimes I amaze even myself. --- Han Solo", NULL),
(NULL, "YAHOOOOO! You're all clear, kid! Now let's blow this thing and go home! --- Han Solo", NULL),
(NULL, "Commander, tear this ship apart until you have found those plans, and bring me the passengers, I want them alive! --- Darth Vader", NULL),
(NULL, "You are part of the Rebel Alliance and a traitor. Take her away. --- Darth Vader", NULL),
(NULL, "This will be a day long remembered. It has seen the end of Kenobi, and will soon see the end of the Rebellion. --- Darth Vader", NULL),
(NULL, "You underestimate the power of the Dark Side! --- Darth Vader", NULL),
(NULL, "The Force is strong with this one. --- Darth Vader", NULL),
(NULL, "Oh! No. Chewie. They are behind you. --- C-3PO", NULL),
(NULL, "Don't blame me. I'm just an interpreter. I'm not supposed to know a power socket from a computer terminal. --- C-3PO", NULL),
(NULL, "I thought that hairy beast would be the end of me. --- C-3PO", NULL),
(NULL, "The city's central computer told you? R2-D2, you know better than to trust a strange computer. --- C-3PO", NULL),
(NULL, "(to Artoo) I'm sitting here in pieces and you're having delusions of grandeur! --- C-3PO", NULL),
(NULL, "What if he doesn't survive? He's worth a lot to me. --- Boba Fett", NULL),
(NULL, "He's no good to me dead. --- Boba Fett", NULL),
(NULL, "Put captain Solo in the cargo hold. --- Boba Fett", NULL),
(NULL, "As you wish. --- Boba Fett", NULL),
(NULL, "Hurry up, Goldenrod, or you're gonna be a permanent resident! --- Han Solo", NULL),
(NULL, "Lando Calrissian. He's a card player, a gambler. A scoundrel, you'd like him. --- Han Solo", NULL),
(NULL, "Chewie, this won't help me! Save your strength, there'll be another time! The princess, you have to take care of her! Do ya hear me, huh? --- Han Solo", NULL),
(NULL, "I feel horrible. --- Han Solo", NULL),
(NULL, "Why, you slimy, double-crossing, no-good swindler. You got a lot of guts coming here after what you pulled. --- Lando Calrissian", NULL),
(NULL, "You know, seeing you sure brings back a few things. Yeah, I'm responsible now, the price you pay for being successful. --- Lando Calrissian", NULL),
(NULL, "They told me they fixed it! It's not my fault! --- Lando Calrissian", NULL),
(NULL, "No light speed. --- Princess Leia Organa", NULL),
(NULL, "Watch what? --- Princess Leia Organa", NULL),
(NULL, "I don't know. I have a bad feeling about this. --- Princess Leia Organa", NULL),
(NULL, "I am altering the deal. Pray I don't alter it any further. --- Darth Vader", NULL),
(NULL, "The Force is with you, young Skywalker... but you are not a Jedi yet. --- Darth Vader", NULL),
(NULL, "You are beaten! It is useless to resist! Don't let yourself be destroyed as Obi-Wan did! --- Darth Vader", NULL),
(NULL, "I am your father --- Darth Vader", NULL),
(NULL, "Luke, you can destroy the Emperor. He has foreseen this. It is your destiny. Join me, and together we will rule the galaxy as father and son. Come with me. It is the only way. --- Darth Vader", NULL),
(NULL, "Impressive. Most impressive. Obi-Wan has taught you well. You have controlled your fear. Now, release your anger. Only your hatred can destroy me. --- Darth Vader", NULL),
(NULL, "Oh, great warrior, hmm? War does not make one great. --- Master Yoda", NULL),
(NULL, "Mudhole? Slimy? My home this is! --- Master Yoda", NULL),
(NULL, "Told you did I, reckless is he! Now, matters are worse. --- Master Yoda", NULL),
(NULL, "Size matters not. Look at me. Judge me by my size do you? --- Master Yoda", NULL),
(NULL, "My ally is the Force, and a powerful ally it is. It energy surrounds us --- Master Yoda", NULL),
(NULL, "Luminous beings are we, not this crude matter! --- Master Yoda", NULL),
(NULL, "Mind what you have learned. Save you it can. --- Master Yoda", NULL),
(NULL, "Mine! Or I will help you not! --- Master Yoda", NULL),
(NULL, "It's against my programming to impersonate a deity. --- C-3PO", NULL),
(NULL, "I'm rather embarrassed, General Solo, but it seems you are to be the main course at a banquet in my honor. --- C-3PO", NULL),
(NULL, "How could they be jamming us if they don't know... that we're coming. --- Lando Calrissian", NULL),
(NULL, "Don't worry, my friends are down there. They'll have that shield down on time...(to himself) or this'll be the shortest offensive of all time. --- Lando Calrissian", NULL),
(NULL, "That blast came from the Death Star! That thing's operational! --- Lando Calrissian", NULL),
(NULL, "Han will have that shield down, we've gotta give him more time!", NULL),
(NULL, "I'm out of it for a little while, and everybody gets delusions of grandeur. --- Han Solo", NULL),
(NULL, "Threepio, you tell that slimy piece of worm-ridden filth he'll get no such pleasure from us! ...Right? --- Han Solo", NULL),
(NULL, "Good luck. You're gonna need it. --- Han Solo", NULL),
(NULL, "Yeah, I just got a funny feeling. Like I'm never gonna see her again. --- Han Solo", NULL),
(NULL, "Great, Chewie, great. Always thinkin' with your stomach. --- Han Solo", NULL),
(NULL, "Not bad for a little fur ball. There's only one left. --- Han Solo", NULL),
(NULL, "Jabba, this is your last chance; free us or die! --- Luke Skywalker", NULL),
(NULL, "Never. I'll never turn to the Dark Side. You have failed, your highness. I am a Jedi like my father before me. --- Luke Skywalker", NULL),
(NULL, "Your father was seduced by the Dark Side of the Force. He ceased to be Anakin Skywalker and became Darth Vader. When that happened, the good man who was your father was destroyed. So what I told you was true—from a certain point of view. --- Obi-Wan Kenobi", NULL),
(NULL, "Luke, you're going to find that many of the truths we cling to depend greatly on our own point of view. --- Obi-Wan Kenobi", NULL),
(NULL, "Welcome, young Skywalker. I have been expecting you. --- Emperor Palpatine", NULL),
(NULL, "Good! Use your aggressive feelings, boy. Let the hate flow through you. --- Emperor Palpatine", NULL),
(NULL, "If you will not be turned you will be destroyed! Young fool. Only now, at the end, do you understand. Your feeble skills are no match for the power of the dark side! You have paid the price for your lack of vision! --- Emperor Palpatine", NULL),
(NULL, "Now, young Skywalker... you will die. --- Emperor Palpatine", NULL),
(NULL, "It was I that let the alliance know the location of the shield generator. An entire legion of my best troops await them. Oh, I'm afraid the deflector shields will be quite operational when your friends arrive -evil smile-. --- Emperor Palpatine", NULL),
(NULL, "The Emperor is not as forgiving as I am. --- Darth Vader", NULL),
(NULL, "I see you have constructed a new lightsaber. Your skills are complete. Indeed you are powerful, as the Emperor has foreseen. --- Darth Vader", NULL),
(NULL, "You underestimate the power of the Dark Side. --- Darth Vader", NULL),
(NULL, "Give yourself to the Dark Side. It is the only way you can save your friends. Yes, your thoughts betray you. Your feelings for them are strong. --- Darth Vader", NULL),
(NULL, "Sister. So you have a twin sister. Your feelings have betrayed her too. --- Darth Vader", NULL),
(NULL, "It's a trap! --- Admiral Ackbar", NULL),
(NULL, "The shield is down! Commence attack on the Death Star's main reactor. --- Admiral Ackbar", NULL),
(NULL, "We've got to give those fighters more time. Concentrate all fire on that Super Star Destroyer. --- Admiral Ackbar", NULL),
(NULL, "Move the fleet away from the Death Star. --- Admiral Ackbar", NULL),
(NULL, "Our cruisers can't repel firepower of that magnitude! --- Admiral Ackbar", NULL),
(NULL, "May the force be with us. --- Admiral Ackbar", NULL)

